# Generated by Django 5.1.1 on 2026-03-06 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0046_grn_gate_entry_invoice_no_grnitem_batch_heat"),
        (
            "product",
            "0055_remove_temper_unique_active_temper_name_code_section_and_more",
        ),
        ("scrap_entry", "0002_scrapentryitem_process_and_indexes"),
        ("store", "0004_alter_store_store_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="scrapstorestock",
            name="scrap_store_stock_store_item_uniq",
        ),
        migrations.RenameIndex(
            model_name="scrapentry",
            new_name="scrap_entry_entry_n_c05aba_idx",
            old_name="scrap_entry_entry_no_idx",
        ),
        migrations.RenameIndex(
            model_name="scrapentry",
            new_name="scrap_entry_status_cfc68f_idx",
            old_name="scrap_entry_status_idx",
        ),
        migrations.RenameIndex(
            model_name="scrapentry",
            new_name="scrap_entry_date_0c1647_idx",
            old_name="scrap_entry_date_idx",
        ),
        migrations.RenameIndex(
            model_name="scrapentry",
            new_name="scrap_entry_plant_i_a8f95c_idx",
            old_name="scrap_entry_plant_id_idx",
        ),
        migrations.RenameIndex(
            model_name="scrapentry",
            new_name="scrap_entry_source__11038b_idx",
            old_name="scrap_entry_src_dept_idx",
        ),
        migrations.RenameIndex(
            model_name="scrapentry",
            new_name="scrap_entry_is_arch_3571f1_idx",
            old_name="scrap_entry_is_archived_idx",
        ),
        migrations.RenameIndex(
            model_name="scrapentry",
            new_name="scrap_entry_status_c16eb9_idx",
            old_name="scrap_entry_status_arch_idx",
        ),
        migrations.RenameIndex(
            model_name="scrapentryitem",
            new_name="scrap_entry_scrap_e_5d76e7_idx",
            old_name="scrap_entry_item_entry_idx",
        ),
        migrations.RenameIndex(
            model_name="scrapentryitem",
            new_name="scrap_entry_item_id_270e7e_idx",
            old_name="scrap_entry_item_item_idx",
        ),
        migrations.RenameIndex(
            model_name="scrapentryitem",
            new_name="scrap_entry_scrap_t_340ac4_idx",
            old_name="scrap_entry_item_st_idx",
        ),
        migrations.RenameIndex(
            model_name="scrapentryitem",
            new_name="scrap_entry_store_i_e51d40_idx",
            old_name="scrap_entry_item_store_idx",
        ),
        migrations.RenameIndex(
            model_name="scrapentryitem",
            new_name="scrap_entry_process_3d757d_idx",
            old_name="scrap_entry_item_pr_idx",
        ),
        migrations.AlterField(
            model_name="scrapentryitem",
            name="from_process",
            field=models.CharField(
                blank=True,
                help_text="Free text when Process master is not selected; or override display.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scrapentryitem",
            name="scrap_type",
            field=models.ForeignKey(
                help_text="Reference to Scrap Type master.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scrap_entry_items",
                to="scrap_entry.scraptype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scrapstorestock",
            unique_together={("store", "item")},
        ),
        migrations.AddIndex(
            model_name="process",
            index=models.Index(fields=["code"], name="process_code_ed35a6_idx"),
        ),
        migrations.AddIndex(
            model_name="process",
            index=models.Index(
                fields=["is_archived"], name="process_is_arch_c0ce9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapstorestock",
            index=models.Index(
                fields=["store", "item"], name="scrap_store_store_i_12a0e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scraptype",
            index=models.Index(fields=["code"], name="scrap_type_code_b44f73_idx"),
        ),
        migrations.AddIndex(
            model_name="scraptype",
            index=models.Index(
                fields=["is_archived"], name="scrap_type_is_arch_be7b90_idx"
            ),
        ),
    ]
