# Generated by Django 5.1.1 on 2026-08-27 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0051_remove_grnitem_grn_remove_grnitem_item_and_more'),
        ('die', '0123_dietool_status_alter_dietool_location'),
        ('product', '0062_alter_temper_hardness'),
        ('production', '0027_production_status'),
        ('shift', '0002_remove_shiftmaster_deleted_and_more'),
        ('vendor', '0004_alter_vendor_updated_at'),
        ('workorder', '0032_mechanical_test_always_after_dimension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobworkInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('shift_name_snapshot', models.CharField(blank=True, max_length=50, null=True)),
                ('shift_start_snapshot', models.TimeField(blank=True, null=True)),
                ('shift_end_snapshot', models.TimeField(blank=True, null=True)),
                ('challan_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('challan_date', models.DateField(db_index=True)),
                ('vendor_invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_invoice_date', models.DateField(blank=True, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=50, null=True)),
                ('gate_pass_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('taxable_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('attachment', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('jobwork_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobwork_invoices', to='common.jobworktype')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobwork_invoices', to='common.plant')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_shift', to='shift.shiftmaster')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobwork_invoices', to='vendor.vendor')),
            ],
            options={
                'db_table': 'jobwork_invoice',
                'ordering': ['-challan_date', '-id'],
                'permissions': [('print_jobwork_invoice_pdf_copy', 'Can print jobwork invoice PDF'), ('print_jobwork_invoice_excel_copy', 'Can print jobwork invoice Excel')],
            },
        ),
        migrations.CreateModel(
            name='JobworkInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('pieces', models.IntegerField(blank=True, null=True)),
                ('cut_length_mm', models.IntegerField(blank=True, null=True)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('jobwork_description', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('alloy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobwork_invoice_lines_alloy', to='product.alloy')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('die_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobwork_invoice_lines_die', to='die.dietool')),
                ('jobwork_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines', to='jobwork_invoice.jobworkinvoice')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobwork_invoice_lines', to='production.production')),
                ('section_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobwork_invoice_lines_section', to='die.die')),
                ('temper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobwork_invoice_lines_temper', to='product.temper')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobwork_invoice_lines', to='workorder.workorder')),
                ('workorder_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobwork_invoice_lines', to='workorder.workorderdetail')),
            ],
            options={
                'db_table': 'jobwork_invoice_line',
                'ordering': ['id'],
            },
        ),
    ]
