# Generated by Django 5.1.1 on 2026-08-27 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_remove_customer_customer_cu_custome_d3a0b9_idx_and_more'),
        ('jobwork_invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobworkinvoice',
            name='vendor',
            field=models.ForeignKey(limit_choices_to={'company_type__in': ['vendor', 'customer_vendor']}, on_delete=django.db.models.deletion.PROTECT, related_name='jobwork_invoices', to='customer.customer'),
        ),
    ]
