# Generated by Django 5.1.1 on 2025-10-15 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0002_initial"),
        ("inquiry", "0001_initial"),
        ("product", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InquiryQuotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quotation_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("quotation_date", models.DateField(auto_now=True)),
                ("terms_and_condition", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Quotation", "Quotation"),
                            ("WorkOrder", "WorkOrder"),
                        ],
                        default="Quotation",
                        max_length=100,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("converted_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiry_quotation_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiry_quotation_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiry_quotations",
                        to="inquiry.inquiry",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiry_quotation_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "inquiry_quotation",
                "permissions": [
                    ("print_inquiry_quotation_pdf_copy", "Can print inquiry quotation"),
                    (
                        "download_inquiry_quotation_excel_copy",
                        "Can download inquiry quotation Excel",
                    ),
                    (
                        "download_inquiry_quotation_pdf_copy",
                        "Can download inquiry quotation PDF",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InquiryQuotationDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_no", models.CharField(blank=True, max_length=100, null=True)),
                ("length", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "price_per_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("quantity", models.IntegerField(blank=True, default=0, null=True)),
                ("out_source", models.BooleanField(default=False, null=True)),
                ("cutting", models.BooleanField(default=False, null=True)),
                ("machining", models.BooleanField(default=False, null=True)),
                ("deburring", models.BooleanField(default=False, null=True)),
                (
                    "cutting_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "machining_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "deburring_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("anodising", models.BooleanField(default=False, null=True)),
                ("powder_coating", models.BooleanField(default=False, null=True)),
                ("pvdf", models.BooleanField(default=False, null=True)),
                (
                    "anodising_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("anodising_description", models.CharField(max_length=250, null=True)),
                (
                    "powder_coating_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "powder_coating_description",
                    models.CharField(max_length=250, null=True),
                ),
                (
                    "pvdf_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("pvdf_description", models.CharField(max_length=250, null=True)),
                (
                    "laser_marking_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "laser_marking_description",
                    models.CharField(max_length=250, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "alloy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.alloy",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiry_quotation_detail_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiry_quotation_detail_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inquiry_quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiry_quotation_details",
                        to="inquiry_quotation.inquiryquotation",
                    ),
                ),
                (
                    "surface_finish",
                    models.ManyToManyField(
                        blank=True,
                        related_name="inquiry_quotation_surface_finish",
                        to="common.jobworktype",
                    ),
                ),
                (
                    "temper",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.temper",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiry_quotation_detail_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "inquiry_quotation_detail",
                "permissions": [
                    (
                        "download_inquiry_quotation_detail_excel_copy",
                        "Can download inquiry quotation detail Excel",
                    ),
                    (
                        "download_inquiry_quotation_detail_pdf_copy",
                        "Can download inquiry quotation detail PDF",
                    ),
                ],
            },
        ),
    ]
