# Generated by Django 5.1.1 on 2025-10-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry_quotation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiryquotation",
            name="status",
            field=models.CharField(
                choices=[
                    ("Quotation", "Quotation"),
                    ("WorkOrder", "WorkOrder"),
                    ("SalesOrder", "SalesOrder"),
                ],
                default="Quotation",
                max_length=100,
            ),
        ),
    ]
