# Generated by Django 5.1.1 on 2025-11-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry_quotation", "0002_alter_inquiryquotation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiryquotationdetail",
            name="conversion",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="inquiryquotationdetail",
            name="net_weight",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="inquiryquotationdetail",
            name="packing_cost",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
