# Generated by Django 5.1.1 on 2025-11-03 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry_quotation", "0003_inquiryquotationdetail_conversion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inquiryquotationdetail",
            name="quantity",
        ),
    ]
