# Generated by Django 5.1.1 on 2025-11-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry_quotation", "0004_remove_inquiryquotationdetail_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiryquotationdetail",
            name="quantity",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
