# Generated by Django 5.1.1 on 2026-06-09 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry_quotation", "0005_inquiryquotationdetail_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inquiryquotationdetail",
            name="length",
        ),
    ]
