# Generated by Django 5.1.1 on 2026-06-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry_quotation", "0006_remove_inquiryquotationdetail_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiryquotationdetail",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
