# Generated by Django 5.1.1 on 2026-06-12 04:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry", "0017_inquirydetail_length"),
        ("inquiry_quotation", "0008_inquiryquotation_revision_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="inquiryquotation",
            index=models.Index(
                fields=["quotation_no", "revision_number"], name="iq_quote_rev_idx"
            ),
        ),
    ]
