# Generated by Django 5.1.1 on 2026-06-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry_quotation", "0009_inquiryquotation_iq_quote_rev_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiryquotationdetail",
            name="conversion",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="inquiryquotationdetail",
            name="packing_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
