# Generated by Django 5.1.1 on 2025-09-25 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("customer", "0001_initial"),
        ("die", "0002_initial"),
        ("product", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                ("order_date", models.DateField(null=True)),
                ("delivery_date", models.DateField(null=True)),
                ("purchase_order_no", models.CharField(blank=True, max_length=25)),
                ("purchase_order_date", models.DateField(null=True)),
                (
                    "packing_type",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("Strech Film", "Strech Film"),
                            ("HDPE Packing", "HDPE Packing"),
                            ("Inter Leaving", "Inter Leaving"),
                            ("Bubble Wrap", "Bubble Wrap"),
                            ("Corrugated Box", "Corrugated Box"),
                            ("Wooden Box", "Wooden Box"),
                            ("Other", "Other"),
                        ],
                        default="Strech Film",
                        null=True,
                    ),
                ),
                ("project_name", models.CharField(max_length=250, null=True)),
                (
                    "nalco_rate",
                    models.CharField(
                        choices=[("Fixed", "Fixed"), ("Variable", "Variable")],
                        default="Fixed",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "tolerance",
                    models.CharField(
                        choices=[
                            ("Zero(0)", "Zero(0)"),
                            ("+-3%", "+-3%"),
                            ("+-5%", "+-5%"),
                            ("+-7%", "+-7%"),
                            ("+-10%", "+-10%"),
                            ("+3%", "+3%"),
                            ("+5%", "+5%"),
                            ("+7%", "+7%"),
                            ("+10%", "+10%"),
                            ("-3%", "-3%"),
                            ("-5%", "-5%"),
                            ("-7%", "-7%"),
                            ("-10%", "-10%"),
                        ],
                        default="Zero(0)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("W/o create", "W/o create"),
                            ("App- MKT Dpt", "App- MKT Dpt"),
                            ("App- Design Dpt", "App- Design Dpt"),
                            ("App-Management", "App-Management"),
                            ("Open", "Open"),
                            ("Planning", "Planning"),
                            (
                                "Under Production- Extru / Insp / Ageing/QC",
                                "Under Production- Extru / Insp / Ageing/QC",
                            ),
                            ("Wating for packing", "Wating for packing"),
                            ("Packed", "Packed"),
                            ("Dispatched", "Dispatched"),
                            ("Closed", "Closed"),
                        ],
                        default="W/o create",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "order_no",
                    models.CharField(db_index=True, max_length=100, null=True),
                ),
                ("planning_status", models.BooleanField(default=False)),
                (
                    "packing_type_other_reason",
                    models.CharField(max_length=250, null=True),
                ),
                ("po_copy", models.CharField(max_length=250, null=True)),
                ("reason_to_close", models.TextField(blank=True, null=True)),
                ("wo_closing_doc", models.CharField(max_length=250, null=True)),
                (
                    "workorder_type",
                    models.CharField(
                        choices=[("In House", "In House"), ("Job Work", "Job Work")],
                        default="In House",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "bill_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workorder_customer_bill_to",
                        to="customer.customer",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reference_wo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_workorders",
                        to="workorder.workorder",
                    ),
                ),
                (
                    "ship_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workorder_customer_ship_to",
                        to="customer.customer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workorder",
                "permissions": [
                    ("print_workorder_copy", "Can print workorder copy"),
                    ("print_production_copy", "Can print production copy"),
                    ("print_packing_copy", "Can print packing copy"),
                    ("print_account_sales_copy", "Can print account sales copy"),
                    ("print_workorder_report", "Can print workorder report"),
                    (
                        "download_workorder_report_excel_copy",
                        "Can download workorder report Excel",
                    ),
                    ("download_workorder_excel_copy", "Can download workorder Excel"),
                    ("change_profile_over_weight", "Can change profile over weight"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                ("jobwork", models.CharField(blank=True, max_length=255, null=True)),
                ("out_source", models.BooleanField(default=False, null=True)),
                (
                    "laser_marking_description",
                    models.CharField(max_length=250, null=True),
                ),
                (
                    "laser_marking_price",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                ("cutting", models.BooleanField(default=False, null=True)),
                ("machinings", models.BooleanField(default=False, null=True)),
                ("deburring", models.BooleanField(default=False, null=True)),
                (
                    "cutting_price",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "machinings_price",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "deburring_price",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                ("anodising", models.BooleanField(default=False, null=True)),
                ("powder_coating", models.BooleanField(default=False, null=True)),
                ("pvdf", models.BooleanField(default=False, null=True)),
                ("anodising_description", models.CharField(max_length=250, null=True)),
                (
                    "anodising_price",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "powder_coating_description",
                    models.CharField(max_length=250, null=True),
                ),
                (
                    "powder_coating_price",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                ("pvdf_description", models.CharField(max_length=250, null=True)),
                (
                    "pvdf_price",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                ("length", models.IntegerField(default=0, null=True)),
                ("pieces", models.IntegerField(default=0, null=True)),
                (
                    "net_weight",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "max_weight",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "min_weight",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "nalco_rate",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "packing_charge",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "customer_reference_number",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "conversion",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                ("description", models.CharField(max_length=250, null=True)),
                ("modify_nalco_rate", models.BooleanField(default=False)),
                ("nalco_rate_change_reason", models.TextField(blank=True, null=True)),
                (
                    "packed_weight",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "dispatched_weight",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "pending_weight",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "palnning_weight",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                ("packed_pieces", models.IntegerField(default=0, null=True)),
                ("dispatched_pieces", models.IntegerField(default=0, null=True)),
                ("pending_pieces", models.IntegerField(default=0, null=True)),
                ("planning_pieces", models.IntegerField(default=0, null=True)),
                ("die_over_weight", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Packed", "Packed"),
                            ("Pending", "Pending"),
                            ("In-Process", "In-Process"),
                            ("Dispatched", "Dispatched"),
                        ],
                        default="Pending",
                        max_length=250,
                        null=True,
                    ),
                ),
                ("is_palnning", models.BooleanField(default=False)),
                ("is_priority", models.BooleanField(default=False)),
                ("priority_added_at", models.DateTimeField(blank=True, null=True)),
                ("priority_removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "alloy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workorder_detail_alloy",
                        to="product.alloy",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "die_profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workorder_detail_die",
                        to="die.die",
                    ),
                ),
                (
                    "jobworks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="workorder_details",
                        to="common.jobworktype",
                    ),
                ),
                (
                    "priority_added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="priority_added_workorders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "priority_removed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="priority_removed_workorders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "temper",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workorder_detail_temper",
                        to="product.temper",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workorder",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workorder_detail_workorder",
                        to="workorder.workorder",
                    ),
                ),
            ],
            options={
                "db_table": "workorder_detail",
            },
        ),
    ]
