# Generated by Django 5.1.1 on 2025-11-14 10:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workorder",
            name="approve",
        ),
        migrations.RemoveField(
            model_name="workorder",
            name="approve_remarks",
        ),
        migrations.RemoveField(
            model_name="workorder",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="workorder",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="workorder",
            name="done_flag",
        ),
        migrations.RemoveField(
            model_name="workorder",
            name="f_id",
        ),
        migrations.RemoveField(
            model_name="workorder",
            name="reject",
        ),
        migrations.RemoveField(
            model_name="workorderdetail",
            name="approve",
        ),
        migrations.RemoveField(
            model_name="workorderdetail",
            name="approve_remarks",
        ),
        migrations.RemoveField(
            model_name="workorderdetail",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="workorderdetail",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="workorderdetail",
            name="done_flag",
        ),
        migrations.RemoveField(
            model_name="workorderdetail",
            name="f_id",
        ),
        migrations.RemoveField(
            model_name="workorderdetail",
            name="reject",
        ),
        migrations.AddField(
            model_name="workorder",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="deleted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workorder_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workorderdetail",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorderdetail",
            name="deleted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workorderdetail_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workorder",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workorder_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workorder",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workorder_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workorderdetail",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workorderdetail",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workorderdetail_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workorderdetail",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workorderdetail",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workorderdetail_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
