# Generated by Django 5.1.1 on 2025-12-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0002_remove_workorder_approve_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workorder",
            old_name="nalco_rate",
            new_name="nalco_type",
        ),
        migrations.RemoveField(
            model_name="workorder",
            name="packing_type",
        ),
        migrations.RemoveField(
            model_name="workorder",
            name="packing_type_other_reason",
        ),
    ]
