# Generated by Django 5.1.1 on 2025-12-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_packingmode_created_at_packingmode_created_by_and_more"),
        ("workorder", "0003_rename_nalco_rate_workorder_nalco_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="packing_mode",
            field=models.ManyToManyField(
                blank=True,
                related_name="workorder_packing_modes",
                to="common.packingmode",
            ),
        ),
    ]
