# Generated by Django 5.1.1 on 2025-12-03 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0004_workorder_packing_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workorder_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="nalco_type",
            field=models.CharField(
                choices=[("Fixed", "Fixed"), ("Variable", "Variable")],
                default="Variable",
                max_length=100,
                null=True,
            ),
        ),
    ]
