# Generated by Django 5.1.1 on 2026-01-06 07:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0019_make_department_plant_nullable"),
        ("customer", "0010_alter_customer_company_type"),
        ("die", "0043_alter_diesubcategory_name"),
        ("product", "0015_alter_temper_name"),
        ("workorder", "0005_workorder_approved_by_alter_workorder_nalco_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="workorder",
            old_name="nalco_type",
            new_name="nalco_rate",
        ),
        migrations.AddField(
            model_name="workorder",
            name="packing_type_other_reason",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="workorderdetail",
            name="status",
            field=models.CharField(
                choices=[
                    ("Packed", "Packed"),
                    ("Pending", "Pending"),
                    ("In-Process", "In-Process"),
                    ("Dispatched", "Dispatched"),
                    ("In-Planning", "In-Planning"),
                    ("In-Production", "In-Production"),
                    ("In-Priority", "In-Priority"),
                ],
                default="Pending",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["deleted", "status"], name="wo_deleted_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["deleted", "-order_date"], name="wo_deleted_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["deleted", "bill_to", "status"], name="wo_customer_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["status", "deleted"], name="wo_status_deleted_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorderdetail",
            index=models.Index(
                fields=["workorder", "deleted"], name="wod_wo_deleted_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorderdetail",
            index=models.Index(
                fields=["deleted", "status"], name="wod_deleted_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorderdetail",
            index=models.Index(
                fields=["workorder", "die_profile", "alloy", "temper", "length"],
                name="wod_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workorderdetail",
            index=models.Index(
                fields=["status", "deleted"], name="wod_status_deleted_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorderdetail",
            index=models.Index(
                fields=["is_priority", "status"], name="wod_priority_status_idx"
            ),
        ),
    ]
