# Generated by Django 5.1.1 on 2026-01-06 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0006_rename_nalco_type_workorder_nalco_rate_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workorder",
            old_name="packing_type_other_reason",
            new_name="packing_mode_other_reason",
        ),
    ]
