# Generated by Django 5.1.1 on 2026-01-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0008_alter_workorder_created_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workorderdetail",
            old_name="machinings",
            new_name="machining",
        ),
        migrations.RemoveField(
            model_name="workorderdetail",
            name="machinings_price",
        ),
        migrations.AddField(
            model_name="workorderdetail",
            name="machining_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="workorderdetail",
            name="anodising_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="workorderdetail",
            name="cutting_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="workorderdetail",
            name="deburring_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="workorderdetail",
            name="laser_marking_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="workorderdetail",
            name="powder_coating_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="workorderdetail",
            name="pvdf_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
