# Generated by Django 5.1.1 on 2026-01-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0009_rename_machinings_workorderdetail_machining_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workorder",
            old_name="nalco_rate",
            new_name="nalco_type",
        ),
    ]
