# Generated by Django 5.1.1 on 2026-01-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0010_rename_nalco_rate_workorder_nalco_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorderdetail",
            name="conversion",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="workorderdetail",
            name="packing_charge",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
