# Generated by Django 5.1.1 on 2026-01-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0011_alter_workorderdetail_conversion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorderdetail",
            name="nalco_rate",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
