# Generated by Django 5.1.1 on 2026-01-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0012_alter_workorderdetail_nalco_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workorderdetail",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
