# Generated by Django 5.1.1 on 2026-04-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0013_alter_workorder_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="workorder_type",
            field=models.CharField(
                choices=[("In_House", "In_House"), ("Job_Work", "Job_Work")],
                default="In House",
                max_length=250,
                null=True,
            ),
        ),
    ]
