# Generated by Django 4.2.8 on 2026-04-13 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0014_alter_workorder_workorder_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workorderdetail",
            old_name="packing_charge",
            new_name="packing_cost",
        ),
    ]
