# Generated by Django 4.2.8 on 2026-04-13 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0015_rename_packing_charge_workorderdetail_packing_cost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workorderdetail",
            old_name="jobworks",
            new_name="surface_finish",
        ),
        migrations.RemoveField(
            model_name="workorderdetail",
            name="jobwork",
        ),
    ]
