# Generated by Django 4.2.8 on 2026-04-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0016_rename_jobworks_workorderdetail_surface_finish_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="workorder_type",
            field=models.CharField(
                choices=[("In_House", "In_House"), ("Job_Work", "Job_Work")],
                default="In_House",
                max_length=250,
                null=True,
            ),
        ),
    ]
