# Generated by Django 4.2.8 on 2026-04-13 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry_salesorder", "0016_inquirysalesorderdetail_salesorder_type_and_more"),
        ("workorder", "0017_alter_workorder_workorder_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="salesorder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workorder_inquiry_salesorder",
                to="inquiry_salesorder.inquirysalesorder",
            ),
        ),
    ]
