# Generated by Django 5.1.1 on 2026-05-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0018_workorder_salesorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="order_type",
            field=models.CharField(
                choices=[("order", "Order"), ("trial", "Trial")],
                default="order",
                max_length=50,
            ),
        ),
    ]
