# Generated by Django 5.1.1 on 2026-05-28 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry_salesorder", "0017_inquirysalesorder_order_type"),
        ("workorder", "0019_workorder_order_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderdetail",
            name="salesorder_detail",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workorder_detail_salesorder",
                to="inquiry_salesorder.inquirysalesorderdetail",
            ),
        ),
    ]
