# Generated by Django 5.1.1 on 2026-06-01 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry_salesorder", "0017_inquirysalesorder_order_type"),
        ("workorder", "0020_workorderdetail_salesorder_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="salesorder",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workorder_inquiry_salesorder",
                to="inquiry_salesorder.inquirysalesorder",
            ),
        ),
    ]
