# Generated by Django 5.1.1 on 2026-07-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0021_alter_workorder_salesorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="terms_and_condition",
            field=models.TextField(blank=True, null=True),
        ),
    ]
