# Generated by Django 5.1.1 on 2026-08-24 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0022_planning_act_ext_len_planning_actbltwt_and_more'),
        ('workorder', '0022_workorder_terms_and_condition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='process_status',
            field=models.CharField(blank=True, choices=[('WO_CREATED', 'Work Order Created'), ('MKT_APPROVED', 'Marketing Approved'), ('DESIGN_APPROVED', 'Design Approved'), ('MGMT_APPROVED', 'Management Approved'), ('OPEN', 'Open'), ('IN_PLANNING', 'Planning'), ('IN_PRODUCTION', 'Under Production'), ('QC_INSPECTION', 'QC Inspection'), ('AGEING', 'Ageing'), ('FINAL_QC', 'Final QC'), ('WAITING_FOR_PACKING', 'Waiting For Packing'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('CLOSED', 'Closed')], db_index=True, default='WO_CREATED', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workorderdetail',
            name='process_status',
            field=models.CharField(blank=True, choices=[('WO_CREATED', 'Work Order Created'), ('MKT_APPROVED', 'Marketing Approved'), ('DESIGN_APPROVED', 'Design Approved'), ('MGMT_APPROVED', 'Management Approved'), ('OPEN', 'Open'), ('IN_PLANNING', 'Planning'), ('IN_PRODUCTION', 'Under Production'), ('QC_INSPECTION', 'QC Inspection'), ('AGEING', 'Ageing'), ('FINAL_QC', 'Final QC'), ('WAITING_FOR_PACKING', 'Waiting For Packing'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('CLOSED', 'Closed')], db_index=True, default='WO_CREATED', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='WorkOrderProcessTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('scope', models.CharField(choices=[('ITEM', 'Item'), ('PLANNING', 'Planning')], db_index=True, default='ITEM', max_length=20)),
                ('current_stage', models.CharField(choices=[('WO_CREATED', 'Work Order Created'), ('MKT_APPROVED', 'Marketing Approved'), ('DESIGN_APPROVED', 'Design Approved'), ('MGMT_APPROVED', 'Management Approved'), ('OPEN', 'Open'), ('IN_PLANNING', 'Planning'), ('IN_PRODUCTION', 'Under Production'), ('QC_INSPECTION', 'QC Inspection'), ('AGEING', 'Ageing'), ('FINAL_QC', 'Final QC'), ('WAITING_FOR_PACKING', 'Waiting For Packing'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('CLOSED', 'Closed')], db_index=True, default='WO_CREATED', max_length=50)),
                ('requires_ageing', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('planning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_tracks', to='planning.planning')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_tracks', to='workorder.workorder')),
                ('workorder_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_tracks', to='workorder.workorderdetail')),
            ],
            options={
                'db_table': 'workorder_process_track',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderProcessStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('stage_code', models.CharField(choices=[('WO_CREATED', 'Work Order Created'), ('MKT_APPROVED', 'Marketing Approved'), ('DESIGN_APPROVED', 'Design Approved'), ('MGMT_APPROVED', 'Management Approved'), ('OPEN', 'Open'), ('IN_PLANNING', 'Planning'), ('IN_PRODUCTION', 'Under Production'), ('QC_INSPECTION', 'QC Inspection'), ('AGEING', 'Ageing'), ('FINAL_QC', 'Final QC'), ('WAITING_FOR_PACKING', 'Waiting For Packing'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('CLOSED', 'Closed')], db_index=True, max_length=50)),
                ('stage_label', models.CharField(max_length=100)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('is_applicable', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wo_process_stages_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='workorder.workorderprocesstrack')),
            ],
            options={
                'db_table': 'workorder_process_stage',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='workorderprocesstrack',
            index=models.Index(fields=['workorder', 'deleted', 'scope'], name='wopt_wo_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderprocesstrack',
            index=models.Index(fields=['workorder_detail', 'deleted'], name='wopt_detail_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderprocesstrack',
            index=models.Index(fields=['planning', 'deleted'], name='wopt_planning_idx'),
        ),
        migrations.AddConstraint(
            model_name='workorderprocesstrack',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('planning__isnull', True), ('scope', 'ITEM')), fields=('workorder_detail',), name='uniq_item_process_track'),
        ),
        migrations.AddConstraint(
            model_name='workorderprocesstrack',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('planning__isnull', False), ('scope', 'PLANNING')), fields=('planning',), name='uniq_planning_process_track'),
        ),
        migrations.AddIndex(
            model_name='workorderprocessstage',
            index=models.Index(fields=['track', 'stage_code'], name='wops_track_stage_idx'),
        ),
        migrations.AddConstraint(
            model_name='workorderprocessstage',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('track', 'stage_code'), name='uniq_track_stage_code'),
        ),
    ]
