# Generated by Django 5.1.1 on 2026-08-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0025_resync_jobwork_process_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='process_status',
            field=models.CharField(blank=True, choices=[('WO_CREATED', 'Work Order Created'), ('MKT_APPROVED', 'Marketing Approved'), ('DESIGN_APPROVED', 'Design Approved'), ('MGMT_APPROVED', 'Management Approved'), ('OPEN', 'Open'), ('IN_PLANNING', 'Planning'), ('IN_PRODUCTION', 'Under Production'), ('QC_INSPECTION', 'QC Inspection'), ('AGEING', 'Ageing'), ('JW_ENGINEERING', 'Jobwork — Engineering'), ('JW_CUTTING', 'Jobwork — Cutting'), ('JW_MACHINING', 'Jobwork — Machining'), ('JW_DEBURRING', 'Jobwork — Deburring'), ('JW_SURFACE_TREATMENT', 'Jobwork — Surface Treatment'), ('JW_ANODISING', 'Jobwork — Anodising'), ('JW_POWDER_COATING', 'Jobwork — Powder Coating'), ('JW_PVDF', 'Jobwork — PVDF'), ('JW_LASER_MARKING', 'Jobwork — Laser Marking'), ('JW_THERMAL_BREAK', 'Jobwork — Thermal Break'), ('JW_VENDOR_OUT', 'Sent to Third Party Vendor'), ('JW_INVOICE_LINKED', 'Jobwork Invoice Linked'), ('JW_RETURN_QC', 'Return QC Inspection'), ('FINAL_QC', 'Final QC'), ('WAITING_FOR_PACKING', 'Waiting For Packing'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('CLOSED', 'Closed')], db_index=True, default='WO_CREATED', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workorderdetail',
            name='process_status',
            field=models.CharField(blank=True, choices=[('WO_CREATED', 'Work Order Created'), ('MKT_APPROVED', 'Marketing Approved'), ('DESIGN_APPROVED', 'Design Approved'), ('MGMT_APPROVED', 'Management Approved'), ('OPEN', 'Open'), ('IN_PLANNING', 'Planning'), ('IN_PRODUCTION', 'Under Production'), ('QC_INSPECTION', 'QC Inspection'), ('AGEING', 'Ageing'), ('JW_ENGINEERING', 'Jobwork — Engineering'), ('JW_CUTTING', 'Jobwork — Cutting'), ('JW_MACHINING', 'Jobwork — Machining'), ('JW_DEBURRING', 'Jobwork — Deburring'), ('JW_SURFACE_TREATMENT', 'Jobwork — Surface Treatment'), ('JW_ANODISING', 'Jobwork — Anodising'), ('JW_POWDER_COATING', 'Jobwork — Powder Coating'), ('JW_PVDF', 'Jobwork — PVDF'), ('JW_LASER_MARKING', 'Jobwork — Laser Marking'), ('JW_THERMAL_BREAK', 'Jobwork — Thermal Break'), ('JW_VENDOR_OUT', 'Sent to Third Party Vendor'), ('JW_INVOICE_LINKED', 'Jobwork Invoice Linked'), ('JW_RETURN_QC', 'Return QC Inspection'), ('FINAL_QC', 'Final QC'), ('WAITING_FOR_PACKING', 'Waiting For Packing'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('CLOSED', 'Closed')], db_index=True, default='WO_CREATED', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workorderprocessstage',
            name='stage_code',
            field=models.CharField(choices=[('WO_CREATED', 'Work Order Created'), ('MKT_APPROVED', 'Marketing Approved'), ('DESIGN_APPROVED', 'Design Approved'), ('MGMT_APPROVED', 'Management Approved'), ('OPEN', 'Open'), ('IN_PLANNING', 'Planning'), ('IN_PRODUCTION', 'Under Production'), ('QC_INSPECTION', 'QC Inspection'), ('AGEING', 'Ageing'), ('JW_ENGINEERING', 'Jobwork — Engineering'), ('JW_CUTTING', 'Jobwork — Cutting'), ('JW_MACHINING', 'Jobwork — Machining'), ('JW_DEBURRING', 'Jobwork — Deburring'), ('JW_SURFACE_TREATMENT', 'Jobwork — Surface Treatment'), ('JW_ANODISING', 'Jobwork — Anodising'), ('JW_POWDER_COATING', 'Jobwork — Powder Coating'), ('JW_PVDF', 'Jobwork — PVDF'), ('JW_LASER_MARKING', 'Jobwork — Laser Marking'), ('JW_THERMAL_BREAK', 'Jobwork — Thermal Break'), ('JW_VENDOR_OUT', 'Sent to Third Party Vendor'), ('JW_INVOICE_LINKED', 'Jobwork Invoice Linked'), ('JW_RETURN_QC', 'Return QC Inspection'), ('FINAL_QC', 'Final QC'), ('WAITING_FOR_PACKING', 'Waiting For Packing'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('CLOSED', 'Closed')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='workorderprocesstrack',
            name='current_stage',
            field=models.CharField(choices=[('WO_CREATED', 'Work Order Created'), ('MKT_APPROVED', 'Marketing Approved'), ('DESIGN_APPROVED', 'Design Approved'), ('MGMT_APPROVED', 'Management Approved'), ('OPEN', 'Open'), ('IN_PLANNING', 'Planning'), ('IN_PRODUCTION', 'Under Production'), ('QC_INSPECTION', 'QC Inspection'), ('AGEING', 'Ageing'), ('JW_ENGINEERING', 'Jobwork — Engineering'), ('JW_CUTTING', 'Jobwork — Cutting'), ('JW_MACHINING', 'Jobwork — Machining'), ('JW_DEBURRING', 'Jobwork — Deburring'), ('JW_SURFACE_TREATMENT', 'Jobwork — Surface Treatment'), ('JW_ANODISING', 'Jobwork — Anodising'), ('JW_POWDER_COATING', 'Jobwork — Powder Coating'), ('JW_PVDF', 'Jobwork — PVDF'), ('JW_LASER_MARKING', 'Jobwork — Laser Marking'), ('JW_THERMAL_BREAK', 'Jobwork — Thermal Break'), ('JW_VENDOR_OUT', 'Sent to Third Party Vendor'), ('JW_INVOICE_LINKED', 'Jobwork Invoice Linked'), ('JW_RETURN_QC', 'Return QC Inspection'), ('FINAL_QC', 'Final QC'), ('WAITING_FOR_PACKING', 'Waiting For Packing'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('CLOSED', 'Closed')], db_index=True, default='WO_CREATED', max_length=50),
        ),
    ]
