# Generated by Django 5.1.1 on 2025-10-15 04:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0002_initial"),
        ("product", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inquiry_number", models.CharField(max_length=20, unique=True)),
                (
                    "inquiry_date",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("customer_name", models.CharField(db_index=True, max_length=100)),
                ("contact_persons", models.JSONField(default=list)),
                ("initial_requirement", models.CharField(max_length=250)),
                ("annual_requirement", models.CharField(max_length=250)),
                (
                    "inquiry_source",
                    models.CharField(
                        choices=[
                            ("Open_Form", "Open_Form"),
                            ("Whatsapp", "Whatsapp"),
                            ("Email", "Email"),
                            ("Call", "Call"),
                            ("Expo", "Expo"),
                            ("Reference", "Reference"),
                        ],
                        default="Open_Form",
                        max_length=100,
                    ),
                ),
                (
                    "source_attachment",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Assigned", "Assigned"),
                            ("Feasible", "Feasible"),
                            ("Regretted", "Regretted"),
                            ("Quotation_Sent", "Quotation_Sent"),
                            ("SalesOrder_Generated", "SalesOrder_Generated"),
                        ],
                        db_index=True,
                        default="Pending",
                        max_length=100,
                    ),
                ),
                (
                    "regret_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "special_notes",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "certifications_required",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "packaging_requirements",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "additional_notes",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "assigned_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiry_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiry_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiry_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Inquiry",
                "permissions": [
                    ("print_inquiry_pdf_copy", "Can print inquiry"),
                    ("download_inquiry_excel_copy", "Can download inquiry Excel"),
                    ("download_inquiry_pdf_copy", "Can download inquiry PDF"),
                ],
            },
        ),
        migrations.CreateModel(
            name="InquiryDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_no", models.CharField(db_index=True, max_length=20)),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "drawing_attachment",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "standard_confirmation",
                    models.CharField(
                        choices=[
                            ("EN", "EN"),
                            ("IS", "IS"),
                            ("ASTM", "ASTM"),
                            ("JIS", "JIS"),
                            ("OTHERS", "OTHERS"),
                        ],
                        default="EN",
                        max_length=20,
                    ),
                ),
                (
                    "standard_confirmation_other",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("length", models.IntegerField(default=0, null=True)),
                ("tolerance", models.CharField(blank=True, max_length=20, null=True)),
                ("out_source", models.BooleanField(default=False, null=True)),
                ("cutting", models.BooleanField(default=False, null=True)),
                ("machining", models.BooleanField(default=False, null=True)),
                ("deburring", models.BooleanField(default=False, null=True)),
                (
                    "cutting_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "machining_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "deburring_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("anodising", models.BooleanField(default=False, null=True)),
                ("powder_coating", models.BooleanField(default=False, null=True)),
                ("pvdf", models.BooleanField(default=False, null=True)),
                (
                    "anodising_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("anodising_description", models.CharField(max_length=250, null=True)),
                (
                    "powder_coating_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "powder_coating_description",
                    models.CharField(max_length=250, null=True),
                ),
                (
                    "pvdf_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("pvdf_description", models.CharField(max_length=250, null=True)),
                (
                    "laser_marking_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "laser_marking_description",
                    models.CharField(max_length=250, null=True),
                ),
                (
                    "post_operation",
                    models.CharField(
                        choices=[
                            ("Drilling", "Drilling"),
                            ("Punching", "Punching"),
                            ("Machining", "Machining"),
                            ("Tapping", "Tapping"),
                            ("Banding", "Banding"),
                        ],
                        default="Drilling",
                        max_length=100,
                    ),
                ),
                ("end_application", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "alloy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiry_detail_alloy",
                        to="product.alloy",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiry_detail_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiry_detail_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inquiry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiry_details",
                        to="inquiry.inquiry",
                    ),
                ),
                (
                    "surface_finish",
                    models.ManyToManyField(
                        blank=True,
                        related_name="inquiry_detail_jobwork",
                        to="common.jobworktype",
                    ),
                ),
                (
                    "temper",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiry_detail_temper",
                        to="product.temper",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiry_detail_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Inquiry_Detail",
                "permissions": [
                    (
                        "download_inquiry_detail_excel_copy",
                        "Can download inquiry detail Excel",
                    ),
                    (
                        "download_inquiry_detail_pdf_copy",
                        "Can download inquiry detail PDF",
                    ),
                ],
            },
        ),
    ]
