# Generated by Django 5.1.1 on 2025-10-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiry",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Assigned", "Assigned"),
                    ("Feasible", "Feasible"),
                    ("Regretted", "Regretted"),
                    ("Quotation", "Quotation"),
                    ("SalesOrder", "SalesOrder"),
                ],
                db_index=True,
                default="Pending",
                max_length=100,
            ),
        ),
    ]
