# Generated by Django 5.1.1 on 2025-10-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry", "0002_alter_inquiry_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquirydetail",
            name="post_operation_custom",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="inquirydetail",
            name="post_operation",
            field=models.CharField(
                choices=[
                    ("Drilling", "Drilling"),
                    ("Punching", "Punching"),
                    ("Machining", "Machining"),
                    ("Tapping", "Tapping"),
                    ("Banding", "Banding"),
                    ("Others", "Others"),
                ],
                default="Drilling",
                max_length=100,
            ),
        ),
    ]
