# Generated by Django 5.1.1 on 2025-10-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry", "0003_inquirydetail_post_operation_custom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquirydetail",
            name="tolerance_minus",
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="inquirydetail",
            name="tolerance_plus",
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
