# Generated by Django 5.1.1 on 2025-10-31 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry", "0004_inquirydetail_tolerance_minus_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inquirydetail",
            old_name="post_operation_custom",
            new_name="post_operation_other",
        ),
    ]
