# Generated by Django 5.1.1 on 2025-10-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inquiry",
            "0005_rename_post_operation_custom_inquirydetail_post_operation_other",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquirydetail",
            name="standard_confirmation",
            field=models.CharField(
                choices=[
                    ("EN", "EN"),
                    ("IS", "IS"),
                    ("ASTM", "ASTM"),
                    ("JIS", "JIS"),
                    ("Others", "Others"),
                ],
                default="EN",
                max_length=20,
            ),
        ),
    ]
