# Generated by Django 5.1.1 on 2025-11-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry", "0006_alter_inquirydetail_standard_confirmation"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="feasiblity_attachment",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="feasiblity_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
