# Generated by Django 5.1.1 on 2025-12-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry", "0007_inquiry_feasiblity_attachment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquirydetail",
            name="post_operation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Drilling", "Drilling"),
                    ("Punching", "Punching"),
                    ("Machining", "Machining"),
                    ("Tapping", "Tapping"),
                    ("Banding", "Banding"),
                    ("Others", "Others"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inquirydetail",
            name="standard_confirmation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EN", "EN"),
                    ("IS", "IS"),
                    ("ASTM", "ASTM"),
                    ("JIS", "JIS"),
                    ("Others", "Others"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inquirydetail",
            name="tolerance_minus",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="inquirydetail",
            name="tolerance_plus",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
