# Generated by Django 5.2.5 on 2025-12-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry", "0008_alter_inquirydetail_post_operation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiry",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Assigned", "Assigned"),
                    ("Feasible", "Feasible"),
                    ("Regretted", "Regretted"),
                    ("Quotation", "Quotation"),
                    ("SalesOrder", "SalesOrder"),
                    ("Quotation_Sent", "Quotation_Sent"),
                    ("SalesOrder_Generated", "SalesOrder_Generated"),
                ],
                db_index=True,
                default="Pending",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="inquirydetail",
            name="standard_confirmation",
            field=models.CharField(
                choices=[
                    ("EN", "EN"),
                    ("IS", "IS"),
                    ("ASTM", "ASTM"),
                    ("JIS", "JIS"),
                    ("Others", "Others"),
                ],
                default="EN",
                max_length=20,
            ),
        ),
    ]
