# Generated by Django 4.2.8 on 2026-01-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry", "0009_alter_inquiry_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquirydetail",
            name="alloy",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.RemoveField(
            model_name="inquirydetail",
            name="surface_finish",
        ),
        migrations.AlterField(
            model_name="inquirydetail",
            name="temper",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="inquirydetail",
            name="surface_finish",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
