# Generated by Django 5.1.1 on 2026-01-28 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0034_remove_plant_plant_created_dea005_idx_and_more"),
        ("inquiry", "0010_alter_inquirydetail_alloy_and_more"),
        ("product", "0036_temper_electrical_conductivity_max_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquirydetail",
            name="alloy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inquiry_detail_alloy",
                to="product.alloy",
            ),
        ),
        migrations.RemoveField(
            model_name="inquirydetail",
            name="surface_finish",
        ),
        migrations.AlterField(
            model_name="inquirydetail",
            name="temper",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inquiry_detail_temper",
                to="product.temper",
            ),
        ),
        migrations.AddField(
            model_name="inquirydetail",
            name="surface_finish",
            field=models.ManyToManyField(
                blank=True,
                related_name="inquiry_detail_jobwork",
                to="common.jobworktype",
            ),
        ),
    ]
