# Generated by Django 5.1.1 on 2026-04-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry", "0011_alter_inquirydetail_alloy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquirydetail",
            name="tolerance_minus",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="inquirydetail",
            name="tolerance_plus",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
