# Generated by Django 5.1.1 on 2026-06-08 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry", "0012_alter_inquirydetail_tolerance_minus_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inquirydetail",
            name="drawing_attachment",
        ),
        migrations.CreateModel(
            name="InquiryDetailDrawing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inquiry_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drawings",
                        to="inquiry.inquirydetail",
                    ),
                ),
            ],
            options={
                "db_table": "Inquiry_Detail_Drawing",
            },
        ),
    ]
