# Generated by Django 5.1.1 on 2026-06-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry", "0013_remove_inquirydetail_drawing_attachment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiry",
            name="inquiry_source",
            field=models.CharField(
                choices=[
                    ("Open_Form", "Open_Form"),
                    ("Whatsapp", "Whatsapp"),
                    ("Email", "Email"),
                    ("Call", "Call"),
                    ("Expo", "Expo"),
                    ("Reference", "Reference"),
                    ("Visit", "Visit"),
                    ("Agents", "Agents"),
                    ("Marketing_Person", "Marketing_Person"),
                ],
                default="Open_Form",
                max_length=100,
            ),
        ),
    ]
