# Generated by Django 5.1.1 on 2026-06-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry", "0014_alter_inquiry_inquiry_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquirydetail",
            name="section_no",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
