# Generated by Django 5.1.1 on 2026-06-09 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry", "0015_alter_inquirydetail_section_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inquirydetail",
            name="length",
        ),
    ]
