# Generated by Django 5.1.1 on 2026-06-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry", "0016_remove_inquirydetail_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquirydetail",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
