# Generated by Django 5.1.1 on 2025-09-25 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0002_initial"),
        ("customer", "0002_initial"),
        ("die", "0003_initial"),
        ("product", "0002_initial"),
        ("quotation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotation_customer",
                to="customer.customer",
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quotationdetail",
            name="alloy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotation_alloy",
                to="product.alloy",
            ),
        ),
        migrations.AddField(
            model_name="quotationdetail",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quotationdetail",
            name="die_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotation_die_profile",
                to="die.die",
            ),
        ),
        migrations.AddField(
            model_name="quotationdetail",
            name="jobworks",
            field=models.ManyToManyField(
                blank=True, related_name="quotation_details", to="common.jobworktype"
            ),
        ),
        migrations.AddField(
            model_name="quotationdetail",
            name="quotation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotation_quotation_detail",
                to="quotation.quotation",
            ),
        ),
        migrations.AddField(
            model_name="quotationdetail",
            name="temper",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotation_temper",
                to="product.temper",
            ),
        ),
        migrations.AddField(
            model_name="quotationdetail",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
