# Generated by Django 5.1.1 on 2025-11-12 05:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotation", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quotation",
            name="approve",
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="approve_remarks",
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="done_flag",
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="f_id",
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="reject",
        ),
        migrations.RemoveField(
            model_name="quotationdetail",
            name="approve",
        ),
        migrations.RemoveField(
            model_name="quotationdetail",
            name="approve_remarks",
        ),
        migrations.RemoveField(
            model_name="quotationdetail",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="quotationdetail",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="quotationdetail",
            name="done_flag",
        ),
        migrations.RemoveField(
            model_name="quotationdetail",
            name="f_id",
        ),
        migrations.RemoveField(
            model_name="quotationdetail",
            name="reject",
        ),
        migrations.AddField(
            model_name="quotation",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quotation",
            name="deleted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotation_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quotationdetail",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quotationdetail",
            name="deleted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotationdetail_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="converted_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="quotation",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotation_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="project_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="quotation_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="terms_and_condition",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="quotation",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotation_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="workorder_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="anodising",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="anodising_description",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="anodising_price",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="conversion",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotationdetail_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="customer_reference_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="cutting",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="cutting_price",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="deburring",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="deburring_price",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="description",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="laser_marking_description",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="laser_marking_price",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="length",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="machinings",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="machinings_price",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="net_weight",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="out_source",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="pieces",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="powder_coating",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="powder_coating_description",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="powder_coating_price",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="price_per_kg",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="pvdf",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="pvdf_description",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="pvdf_price",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotationdetail_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
