# Generated by Django 5.1.1 on 2026-01-05 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quotation", "0003_remove_quotation_approve_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quotation",
            name="packing_type",
        ),
    ]
