# Generated by Django 4.2.8 on 2026-01-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0012_merge_20251231_1655"),
        ("quotation", "0004_remove_quotation_packing_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="packing_mode",
            field=models.ManyToManyField(
                blank=True,
                related_name="quotation_packing_modes",
                to="common.packingmode",
            ),
        ),
    ]
