# Generated by Django 4.2.8 on 2026-01-05 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quotation", "0005_quotation_packing_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quotationdetail",
            name="jobwork",
        ),
    ]
