# Generated by Django 5.1.1 on 2026-01-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotation", "0006_remove_quotationdetail_jobwork"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotationdetail",
            name="anodising_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="cutting_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="deburring_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="laser_marking_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="machinings_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="powder_coating_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="price_per_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="pvdf_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
