# Generated by Django 5.1.1 on 2026-01-05 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quotation", "0007_alter_quotationdetail_anodising_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quotationdetail",
            old_name="machinings",
            new_name="machining",
        ),
        migrations.RenameField(
            model_name="quotationdetail",
            old_name="machinings_price",
            new_name="machining_price",
        ),
    ]
