# Generated by Django 5.1.1 on 2026-01-06 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0019_make_department_plant_nullable"),
        ("customer", "0010_alter_customer_company_type"),
        ("die", "0043_alter_diesubcategory_name"),
        ("product", "0015_alter_temper_name"),
        ("quotation", "0008_rename_machinings_quotationdetail_machining_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(
                fields=["-created_at", "deleted"], name="quotation_created_3aa093_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(
                fields=["customer", "deleted"], name="quotation_custome_2f8351_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(
                fields=["status", "deleted"], name="quotation_status_a2266e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(
                fields=["quotation_no"], name="quotation_quotati_36c9bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quotationdetail",
            index=models.Index(
                fields=["quotation", "deleted"], name="quotation_d_quotati_938c51_idx"
            ),
        ),
    ]
