# Generated by Django 5.1.1 on 2025-09-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proforma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                (
                    "workorder_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "packing_type",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("Strech Film", "Strech Film"),
                            ("HDPE Packing", "HDPE Packing"),
                            ("Inter Leaving", "Inter Leaving"),
                            ("Bubble Wrap", "Bubble Wrap"),
                            ("Corrugated Box", "Corrugated Box"),
                            ("Wooden Box", "Wooden Box"),
                        ],
                        default="Strech Film",
                        null=True,
                    ),
                ),
                ("proforma_date", models.DateField(auto_now=True)),
                (
                    "freight_charges",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "advance_amount",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("terms_and_condition", models.TextField(blank=True, null=True)),
                (
                    "delivery_schedule",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "weight_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("proforma_no", models.CharField(max_length=100, null=True)),
            ],
            options={
                "db_table": "proforma",
                "permissions": [
                    ("print_proforma_pdf_copy", "Can print die quotation"),
                    ("download_proforma_excel_copy", "Can download proforma Excel"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProformaDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                (
                    "customer_reference_no",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("jobwork", models.CharField(blank=True, max_length=255, null=True)),
                ("out_source", models.BooleanField(default=False, null=True)),
                (
                    "laser_marking_description",
                    models.CharField(max_length=250, null=True),
                ),
                (
                    "laser_marking_price",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                ("cutting", models.BooleanField(default=False, null=True)),
                ("machinings", models.BooleanField(default=False, null=True)),
                ("deburring", models.BooleanField(default=False, null=True)),
                (
                    "cutting_price",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "machinings_price",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "deburring_price",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                ("anodising", models.BooleanField(default=False, null=True)),
                ("powder_coating", models.BooleanField(default=False, null=True)),
                ("pvdf", models.BooleanField(default=False, null=True)),
                ("anodising_description", models.CharField(max_length=250, null=True)),
                (
                    "anodising_price",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "powder_coating_description",
                    models.CharField(max_length=250, null=True),
                ),
                (
                    "powder_coating_price",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                ("pvdf_description", models.CharField(max_length=250, null=True)),
                (
                    "pvdf_price",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                ("length", models.DecimalField(decimal_places=3, max_digits=10)),
                ("pieces", models.IntegerField(default=0, null=True)),
                (
                    "net_weight",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "nalco_rate",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "packed_weight",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                ("dispatch_qty", models.FloatField(default=0.0, null=True)),
            ],
            options={
                "db_table": "proforma_details",
            },
        ),
    ]
