# Generated by Django 5.1.1 on 2025-09-25 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0002_initial"),
        ("customer", "0002_initial"),
        ("die", "0003_initial"),
        ("product", "0002_initial"),
        ("proforma", "0001_initial"),
        ("workorder", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="proforma",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="proforma",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proforma_customer",
                to="customer.customer",
            ),
        ),
        migrations.AddField(
            model_name="proforma",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="proforma",
            name="workorder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proforma_workorder",
                to="workorder.workorder",
            ),
        ),
        migrations.AddField(
            model_name="proformadetails",
            name="alloy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proforma_detail_alloy",
                to="product.alloy",
            ),
        ),
        migrations.AddField(
            model_name="proformadetails",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="proformadetails",
            name="jobworks",
            field=models.ManyToManyField(
                blank=True, related_name="proforma_details", to="common.jobworktype"
            ),
        ),
        migrations.AddField(
            model_name="proformadetails",
            name="profile_no",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proforma_detail_die",
                to="die.die",
            ),
        ),
        migrations.AddField(
            model_name="proformadetails",
            name="proforma",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proforma_details_proforma",
                to="proforma.proforma",
            ),
        ),
        migrations.AddField(
            model_name="proformadetails",
            name="temper",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proforma_detail_temper",
                to="product.temper",
            ),
        ),
        migrations.AddField(
            model_name="proformadetails",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
