# Generated by Django 5.1.1 on 2026-01-13 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0022_alter_packingmode_created_by_and_more"),
        ("customer", "0016_alter_accountgroup_created_by_and_more"),
        ("die", "0045_merge_20260108_1600"),
        ("product", "0025_temper_section_thickness_over_and_more"),
        ("proforma", "0003_remove_proforma_approve_and_more"),
        ("workorder", "0012_alter_workorderdetail_nalco_rate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proforma",
            name="packing_type",
        ),
        migrations.RemoveField(
            model_name="proformadetails",
            name="jobwork",
        ),
        migrations.RemoveField(
            model_name="proformadetails",
            name="machinings",
        ),
        migrations.RemoveField(
            model_name="proformadetails",
            name="machinings_price",
        ),
        migrations.AddField(
            model_name="proforma",
            name="packing_mode",
            field=models.ManyToManyField(
                blank=True,
                related_name="proforma_packing_mode",
                to="common.packingmode",
            ),
        ),
        migrations.AddField(
            model_name="proformadetails",
            name="machining",
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="proformadetails",
            name="machining_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="proforma",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="proforma",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="proforma",
            name="proforma_date",
            field=models.DateField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="proforma",
            name="proforma_no",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="proforma",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="proforma",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="proforma",
            name="workorder_no",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="proformadetails",
            name="anodising",
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="proformadetails",
            name="anodising_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="proformadetails",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="proformadetails",
            name="customer_reference_no",
            field=models.CharField(
                blank=True, db_index=True, max_length=250, null=True
            ),
        ),
        migrations.AlterField(
            model_name="proformadetails",
            name="cutting",
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="proformadetails",
            name="cutting_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="proformadetails",
            name="deburring",
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="proformadetails",
            name="deburring_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="proformadetails",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="proformadetails",
            name="dispatch_qty",
            field=models.FloatField(db_index=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="proformadetails",
            name="laser_marking_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="proformadetails",
            name="length",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="proformadetails",
            name="out_source",
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="proformadetails",
            name="pieces",
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="proformadetails",
            name="powder_coating",
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="proformadetails",
            name="powder_coating_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="proformadetails",
            name="pvdf",
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="proformadetails",
            name="pvdf_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="proformadetails",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="proformadetails",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="proforma",
            index=models.Index(fields=["workorder"], name="workorder_proforma_idx"),
        ),
        migrations.AddIndex(
            model_name="proforma",
            index=models.Index(fields=["customer"], name="customer_proforma_idx"),
        ),
        migrations.AddIndex(
            model_name="proforma",
            index=models.Index(fields=["proforma_no"], name="proforma_no_idx"),
        ),
        migrations.AddIndex(
            model_name="proforma",
            index=models.Index(
                fields=["workorder_no"], name="workorder_no_proforma_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proforma",
            index=models.Index(fields=["proforma_date"], name="proforma_date_idx"),
        ),
        migrations.AddIndex(
            model_name="proforma",
            index=models.Index(
                fields=["workorder", "proforma_date"],
                name="workorder_date_proforma_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="proforma",
            index=models.Index(
                fields=["customer", "proforma_date"], name="customer_date_proforma_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proforma",
            index=models.Index(fields=["deleted", "created_at"], name="pf_del_cr_idx"),
        ),
        migrations.AddIndex(
            model_name="proforma",
            index=models.Index(fields=["deleted", "deleted_at"], name="pf_del_del_idx"),
        ),
        migrations.AddIndex(
            model_name="proforma",
            index=models.Index(
                fields=["created_by", "created_at"], name="pf_crby_crat_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proforma",
            index=models.Index(
                fields=["-created_at"], name="created_at_desc_proforma_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proforma",
            index=models.Index(
                fields=["-proforma_date"], name="proforma_date_desc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proformadetails",
            index=models.Index(
                fields=["proforma"], name="proforma_details_proforma_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proformadetails",
            index=models.Index(fields=["profile_no"], name="profile_no_idx"),
        ),
        migrations.AddIndex(
            model_name="proformadetails",
            index=models.Index(fields=["alloy"], name="alloy_details_idx"),
        ),
        migrations.AddIndex(
            model_name="proformadetails",
            index=models.Index(fields=["temper"], name="temper_details_idx"),
        ),
        migrations.AddIndex(
            model_name="proformadetails",
            index=models.Index(
                fields=["customer_reference_no"], name="customer_ref_no_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proformadetails",
            index=models.Index(fields=["out_source"], name="out_source_idx"),
        ),
        migrations.AddIndex(
            model_name="proformadetails",
            index=models.Index(fields=["cutting"], name="cutting_idx"),
        ),
        migrations.AddIndex(
            model_name="proformadetails",
            index=models.Index(fields=["machining"], name="machining_idx"),
        ),
        migrations.AddIndex(
            model_name="proformadetails",
            index=models.Index(fields=["deburring"], name="deburring_idx"),
        ),
        migrations.AddIndex(
            model_name="proformadetails",
            index=models.Index(fields=["anodising"], name="anodising_idx"),
        ),
        migrations.AddIndex(
            model_name="proformadetails",
            index=models.Index(fields=["powder_coating"], name="powder_coating_idx"),
        ),
        migrations.AddIndex(
            model_name="proformadetails",
            index=models.Index(fields=["pvdf"], name="pvdf_idx"),
        ),
        migrations.AddIndex(
            model_name="proformadetails",
            index=models.Index(fields=["pieces"], name="pieces_details_idx"),
        ),
        migrations.AddIndex(
            model_name="proformadetails",
            index=models.Index(fields=["dispatch_qty"], name="dispatch_qty_idx"),
        ),
        migrations.AddIndex(
            model_name="proformadetails",
            index=models.Index(
                fields=["proforma", "profile_no"], name="proforma_die_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proformadetails",
            index=models.Index(
                fields=["proforma", "alloy", "temper"], name="proforma_alloy_temper_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proformadetails",
            index=models.Index(
                fields=["profile_no", "alloy", "temper"], name="pfdet_die_alloy_tmp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proformadetails",
            index=models.Index(
                fields=["out_source", "cutting", "machining"], name="jobwork_flags_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proformadetails",
            index=models.Index(
                fields=["anodising", "powder_coating", "pvdf"],
                name="finishing_flags_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="proformadetails",
            index=models.Index(
                fields=["deleted", "created_at"], name="deleted_created_at_details_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proformadetails",
            index=models.Index(
                fields=["-created_at"], name="created_at_desc_details_idx"
            ),
        ),
    ]
