# Generated by Django 5.1.1 on 2026-01-16 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proforma", "0004_remove_proforma_packing_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="proforma",
            options={
                "permissions": [
                    ("print_proforma_copy", "Can print proforma copy"),
                    ("print_proforma_pdf_copy", "Can print die quotation"),
                    ("download_proforma_excel_copy", "Can download proforma Excel"),
                ]
            },
        ),
    ]
