# Generated by Django 5.1.1 on 2026-01-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proforma", "0005_alter_proforma_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proforma",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="proformadetails",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
