# Generated by Django 5.1.1 on 2026-03-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proforma", "0006_alter_proforma_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proforma",
            name="advance_amount",
        ),
        migrations.RemoveField(
            model_name="proforma",
            name="freight_charges",
        ),
    ]
