# Generated by Django 5.1.1 on 2026-03-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proforma", "0007_remove_proforma_advance_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proforma",
            name="advance_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="proforma",
            name="freight_charges",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="proforma",
            name="insurance_charges",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="proforma",
            name="other_charges",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="proforma",
            name="transport_charges",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
