# Generated by Django 5.1.1 on 2026-03-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proforma", "0008_proforma_advance_amount_proforma_freight_charges_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proformadetails",
            name="nalco_rate",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
