# Generated by Django 5.1.1 on 2026-07-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proforma", "0009_alter_proformadetails_nalco_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="proforma",
            name="type",
            field=models.CharField(
                choices=[("NORMAL", "NORMAL"), ("WORKORDER", "WORKORDER")],
                default="WORKORDER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="proformadetails",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
