# Generated by Django 5.1.1 on 2026-07-21 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proforma", "0010_proforma_type_proformadetails_description"),
        ("workorder", "0022_workorder_terms_and_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proforma",
            name="workorder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proforma_workorder",
                to="workorder.workorder",
            ),
        ),
    ]
