# Generated by Django 5.1.1 on 2026-07-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proforma", "0011_alter_proforma_workorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="proformadetails",
            name="conversion",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
