# Generated by Django 5.1.1 on 2026-08-27 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0051_remove_grnitem_grn_remove_grnitem_item_and_more'),
        ('customer', '0025_remove_customer_customer_cu_custome_d3a0b9_idx_and_more'),
        ('die', '0123_dietool_status_alter_dietool_location'),
        ('jobwork_invoice', '0002_alter_vendor_to_customer'),
        ('product', '0062_alter_temper_hardness'),
        ('production', '0027_production_status'),
        ('shift', '0002_remove_shiftmaster_deleted_and_more'),
        ('workorder', '0032_mechanical_test_always_after_dimension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnQC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('shift_name_snapshot', models.CharField(blank=True, max_length=50, null=True)),
                ('shift_start_snapshot', models.TimeField(blank=True, null=True)),
                ('shift_end_snapshot', models.TimeField(blank=True, null=True)),
                ('inspection_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('inspection_date', models.DateField(db_index=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=50, null=True)),
                ('gate_entry_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('overall_result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('REWORK', 'Rework'), ('PARTIAL', 'Partial Pass')], default='PASS', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('attachment', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('jobwork_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_qc_inspections', to='jobwork_invoice.jobworkinvoice')),
                ('jobwork_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_qc_inspections', to='common.jobworktype')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_qc_inspections', to='common.plant')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_shift', to='shift.shiftmaster')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(limit_choices_to={'company_type__in': ['vendor', 'customer_vendor']}, on_delete=django.db.models.deletion.PROTECT, related_name='return_qc_inspections', to='customer.customer')),
            ],
            options={
                'db_table': 'return_qc',
                'ordering': ['-inspection_date', '-id'],
                'permissions': [('print_return_qc_pdf_copy', 'Can print return QC PDF'), ('print_return_qc_excel_copy', 'Can print return QC Excel')],
            },
        ),
        migrations.CreateModel(
            name='ReturnQCLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('pieces_sent', models.IntegerField(blank=True, null=True)),
                ('pieces_received', models.IntegerField(blank=True, null=True)),
                ('pieces_accepted', models.IntegerField(blank=True, null=True)),
                ('pieces_rejected', models.IntegerField(blank=True, null=True)),
                ('cut_length_mm', models.IntegerField(blank=True, null=True)),
                ('weight_received', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('qc_result', models.CharField(blank=True, choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('REWORK', 'Rework'), ('PARTIAL', 'Partial Pass')], default='PASS', max_length=20, null=True)),
                ('defect_type', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('alloy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_qc_lines_alloy', to='product.alloy')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('die_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_qc_lines_die', to='die.dietool')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_qc_lines', to='production.production')),
                ('return_qc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_lines', to='return_qc.returnqc')),
                ('section_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_qc_lines_section', to='die.die')),
                ('temper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_qc_lines_temper', to='product.temper')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_qc_lines', to='workorder.workorder')),
                ('workorder_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_qc_lines', to='workorder.workorderdetail')),
            ],
            options={
                'db_table': 'return_qc_line',
                'ordering': ['id'],
            },
        ),
    ]
