# Generated by Django 5.1.1 on 2026-02-04 07:11

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("melting_furnace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additivecategory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 10, 39, 769053, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="additivecategory",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 10, 41, 235953, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="additivemaster",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 10, 42, 637980, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="additivemaster",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 10, 44, 374720, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="furnace",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 10, 46, 266642, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="furnace",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 10, 47, 796145, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recoverystandard",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 10, 49, 217013, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recoverystandard",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 10, 50, 661336, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
