# Generated by Django 5.1.1 on 2026-02-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("melting_furnace", "0002_alter_additivecategory_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="furnace",
            name="remark",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="furnace",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                db_index=True,
                default="Active",
                max_length=20,
            ),
        ),
    ]
