# Generated by Django 5.1.1 on 2026-02-08 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("melting_furnace", "0003_furnace_remark_alter_furnace_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="additivemaster",
            options={
                "ordering": ["-id"],
                "permissions": [
                    (
                        "download_additive_master_pdf_copy",
                        "Can download additive_master PDF",
                    ),
                    (
                        "download_additive_master_excel_copy",
                        "Can download additive_master Excel",
                    ),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="furnace",
            options={
                "ordering": ["-id"],
                "permissions": [
                    ("download_furnace_pdf_copy", "Can download furnace PDF"),
                    ("download_furnace_excel_copy", "Can download furnace Excel"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="recoverystandard",
            options={
                "ordering": ["-id"],
                "permissions": [
                    (
                        "download_recovery_standard_pdf_copy",
                        "Can download recovery_standard PDF",
                    ),
                    (
                        "download_recovery_standard_excel_copy",
                        "Can download recovery_standard Excel",
                    ),
                ],
            },
        ),
    ]
