# Generated by Django 5.1.1 on 2026-02-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "melting_furnace",
            "0004_alter_additivemaster_options_alter_furnace_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="additivecategory",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="additivemaster",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="furnace",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recoverystandard",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
