# Generated by Django 5.2.4

from django.db import migrations, models
import django.db.models.deletion


def backfill_material_type(apps, schema_editor):
    MaterialType = apps.get_model("melting_furnace", "MaterialType")
    RecoveryStandard = apps.get_model("melting_furnace", "RecoveryStandard")
    default_mt, _ = MaterialType.objects.get_or_create(
        code="GEN",
        defaults={"name": "General", "is_active": True},
    )
    seen = {"": default_mt}
    for rs in RecoveryStandard.objects.all():
        legacy = (getattr(rs, "material_type_legacy", None) or "").strip()
        if legacy not in seen:
            code = (
                legacy[:4].upper() if len(legacy) >= 4 else legacy.upper().ljust(4, "X")
            )[:4]
            mt, _ = MaterialType.objects.get_or_create(
                code=code,
                defaults={"name": legacy, "is_active": True},
            )
            seen[legacy] = mt
        rs.material_type = seen[legacy]
        rs.save(update_fields=["material_type"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("melting_furnace", "0005_alter_additivecategory_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=10, unique=True, verbose_name="Code"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name": "Material Type",
                "verbose_name_plural": "Material Types",
                "db_table": "material_type",
                "ordering": ["name"],
            },
        ),
        migrations.RenameField(
            model_name="recoverystandard",
            old_name="material_type",
            new_name="material_type_legacy",
        ),
        migrations.AddField(
            model_name="recoverystandard",
            name="material_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recovery_standards",
                to="melting_furnace.materialtype",
            ),
        ),
        migrations.RunPython(backfill_material_type, noop),
        migrations.RemoveField(
            model_name="recoverystandard",
            name="material_type_legacy",
        ),
        migrations.AlterField(
            model_name="recoverystandard",
            name="material_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recovery_standards",
                to="melting_furnace.materialtype",
            ),
        ),
    ]
