# Generated by Django 5.1.1 on 2026-02-17 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("melting_furnace", "0006_materialtype_and_recoverystandard_material_type_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recoverystandard",
            name="furnace_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recovery_standards",
                to="melting_furnace.furnacetype",
            ),
        ),
    ]
