# Generated by Django 5.1.1 on 2026-06-03 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receipt_notes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goodsreceiptnotedetail",
            name="received_by",
        ),
    ]
