# Generated by Django 5.1.1 on 2026-06-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipt_notes", "0002_remove_goodsreceiptnotedetail_received_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceiptnotedetail",
            name="received_qty",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceiptnotedetail",
            name="accepted_qty",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceiptnotedetail",
            name="excess_qty",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceiptnotedetail",
            name="ordered_qty",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceiptnotedetail",
            name="pending_qty",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceiptnotedetail",
            name="rejected_qty",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
