# Generated by Django 5.1.1 on 2026-07-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipt_notes", "0003_goodsreceiptnotedetail_received_qty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="grn_no",
            field=models.CharField(
                db_index=True, default="", max_length=50, unique=True
            ),
            preserve_default=False,
        ),
    ]
