# Generated by Django 5.1.1 on 2026-07-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipt_notes", "0004_goodsreceiptnote_grn_no"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goodsreceiptnote",
            old_name="vendor_name",
            new_name="vendor",
        ),
        migrations.RenameField(
            model_name="goodsreceiptnotedetail",
            old_name="item_name",
            new_name="item",
        ),
        migrations.RenameField(
            model_name="goodsreceiptnotedetail",
            old_name="target_store",
            new_name="store",
        ),
        migrations.AlterField(
            model_name="goodsreceiptnotedetail",
            name="accepted_qty",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceiptnotedetail",
            name="excess_qty",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceiptnotedetail",
            name="ordered_qty",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceiptnotedetail",
            name="pending_qty",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceiptnotedetail",
            name="received_qty",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceiptnotedetail",
            name="rejected_qty",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
