# Generated by Django 5.1.1 on 2026-07-30 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receipt_notes", "0005_rename_vendor_name_goodsreceiptnote_vendor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goodsreceiptnote",
            name="gate_entry",
        ),
        migrations.RemoveField(
            model_name="goodsreceiptnote",
            name="purchase_order",
        ),
        migrations.RemoveField(
            model_name="goodsreceiptnote",
            name="received_by",
        ),
        migrations.RemoveField(
            model_name="goodsreceiptnote",
            name="vendor",
        ),
    ]
