# Generated by Django 5.1.1 on 2026-07-30 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0025_remove_customer_customer_cu_custome_d3a0b9_idx_and_more"),
        ("purchase_order", "0006_purchaseorderdetail_item"),
        ("receipt_notes", "0006_remove_goodsreceiptnote_gate_entry_and_more"),
        ("store", "0004_alter_store_store_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grn_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.customer",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="purchase_order.purchaseorder",
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceiptnotedetail",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.store",
            ),
        ),
    ]
