# Generated by Django 5.1.1 on 2026-07-30 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receipt_notes", "0007_goodsreceiptnote_approved_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goodsreceiptnotedetail",
            name="item",
        ),
    ]
