# Generated by Django 5.1.1 on 2026-07-31 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0061_rename_standard_name_alloy_standard_and_more"),
        ("receipt_notes", "0008_remove_goodsreceiptnotedetail_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceiptnotedetail",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="product.item",
            ),
        ),
    ]
