# Generated by Django 5.1.1 on 2026-07-31 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipt_notes", "0009_goodsreceiptnotedetail_item"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="goodsreceiptnote",
            old_name="customer",
            new_name="vendor",
        ),
        migrations.RemoveField(
            model_name="goodsreceiptnote",
            name="approved_by",
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grn_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
