# Generated by Django 5.1.1 on 2026-08-03 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receipt_notes", "0010_rename_customer_goodsreceiptnote_vendor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goodsreceiptnote",
            name="vendor",
        ),
    ]
