# Generated by Django 5.1.1 on 2026-08-03 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0025_remove_customer_customer_cu_custome_d3a0b9_idx_and_more"),
        ("receipt_notes", "0011_remove_goodsreceiptnote_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grn_vendor",
                to="customer.customer",
            ),
        ),
    ]
