# Generated by Django 5.1.1 on 2026-08-03 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipt_notes", "0012_goodsreceiptnote_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsreceiptnotedetail",
            name="grn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grn_details",
                to="receipt_notes.goodsreceiptnote",
            ),
        ),
    ]
