# Generated by Django 5.1.1 on 2026-08-04 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0025_remove_customer_customer_cu_custome_d3a0b9_idx_and_more"),
        ("purchase_order", "0007_rename_tax_purchaseorderdetail_gst_percent_and_more"),
        ("receipt_notes", "0013_alter_goodsreceiptnotedetail_grn"),
        ("store", "0004_alter_store_store_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goodsreceiptnotedetail",
            name="accepted_qty",
        ),
        migrations.RemoveField(
            model_name="goodsreceiptnotedetail",
            name="item",
        ),
        migrations.RemoveField(
            model_name="goodsreceiptnotedetail",
            name="pending_qty",
        ),
        migrations.RemoveField(
            model_name="goodsreceiptnotedetail",
            name="rejected_qty",
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="challan_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="challan_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="grn_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="invoice_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="invoice_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("RECEIVED", "Received"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptnotedetail",
            name="po_detail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="po_details",
                to="purchase_order.purchaseorderdetail",
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceiptnote",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grn_po",
                to="purchase_order.purchaseorder",
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceiptnote",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grn_vendor",
                to="customer.customer",
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceiptnotedetail",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="store.store",
            ),
        ),
    ]
