# Generated by Django 5.1.1 on 2026-06-02 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_order", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchaseorderdetail",
            options={
                "permissions": [
                    (
                        "download_purchase_order_detail_excel_copy",
                        "Can download purchase order detail Excel",
                    ),
                    (
                        "download_purchase_order_detail_pdf_copy",
                        "Can download purchase order detail PDF",
                    ),
                ]
            },
        ),
    ]
