# Generated by Django 5.1.1 on 2026-07-12 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_order", "0002_alter_purchaseorderdetail_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderdetail",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="po_details",
                to="purchase_order.purchaseorder",
            ),
        ),
    ]
