# Generated by Django 5.1.1 on 2026-07-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_order", "0003_purchaseorderdetail_purchase_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="request_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
