# Generated by Django 5.1.1 on 2026-07-27 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_order", "0004_purchaseorder_request_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorderdetail",
            name="material",
        ),
    ]
