# Generated by Django 5.1.1 on 2026-07-27 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0061_rename_standard_name_alloy_standard_and_more"),
        ("purchase_order", "0005_remove_purchaseorderdetail_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderdetail",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="po_item",
                to="product.item",
            ),
        ),
    ]
