# Generated by Django 5.1.1 on 2026-08-04 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0025_remove_customer_customer_cu_custome_d3a0b9_idx_and_more"),
        ("purchase_order", "0006_purchaseorderdetail_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchaseorderdetail",
            old_name="tax",
            new_name="gst_percent",
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("PARTIALLY_RECEIVED", "Partially Received"),
                    ("FULLY_RECEIVED", "Fully Received"),
                    ("CANCELLED", "Cancelled"),
                    ("CLOSED", "Closed"),
                ],
                default="DRAFT",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderdetail",
            name="basic_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderdetail",
            name="discount_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderdetail",
            name="received_qty",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderdetail",
            name="taxable_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderdetail",
            name="total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="po_vendor",
                to="customer.customer",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderdetail",
            name="pending_qty",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
