# Generated by Django 5.1.1 on 2025-09-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NalcoMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                ("date", models.DateField()),
                ("ignot_grade", models.CharField(max_length=100)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "rate_per_mt",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Rate / MT"
                    ),
                ),
                ("difference", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "permissions": [
                    ("download_nalco_rate_pdf_copy", "Can download nalco rate PDF"),
                    ("download_nalco_rate_excel_copy", "Can download nalco rate Excel"),
                ],
            },
        ),
    ]
