# Generated by Django 5.1.1 on 2026-02-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nalco", "0003_remove_nalcomaster_approve_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nalcomaster",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
