# Generated by Django 5.1.1 on 2026-04-08 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nalco", "0004_alter_nalcomaster_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nalcomaster",
            name="difference",
        ),
        migrations.RemoveField(
            model_name="nalcomaster",
            name="rate",
        ),
    ]
