# Generated by Django 5.1.1 on 2026-04-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nalco", "0005_remove_nalcomaster_difference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nalcomaster",
            name="adjustment_type",
            field=models.CharField(
                blank=True,
                choices=[("Increase", "Increase"), ("Decrease", "Decrease")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="nalcomaster",
            name="adjustment_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="nalcomaster",
            name="diff_kg",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="nalcomaster",
            name="diff_mt",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="nalcomaster",
            name="final_rate_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="nalcomaster",
            name="final_rate_mt",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="nalcomaster",
            name="percentage_change",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="nalcomaster",
            name="rate_per_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Rate / KG",
            ),
        ),
        migrations.AlterField(
            model_name="nalcomaster",
            name="rate_per_mt",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Rate / MT",
            ),
        ),
    ]
