# Generated by Django 5.1.1 on 2025-10-27 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0002_initial"),
        ("inquiry", "0001_initial"),
        ("product", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InquirySalesOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sales_order_no",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("order_date", models.DateField(auto_now=True)),
                (
                    "purchase_order_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("purchase_order_date", models.DateField(blank=True, null=True)),
                (
                    "mode_of_packing",
                    models.TextField(
                        default="Strech_Film", help_text="Comma-separated packing types"
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "purchase_order_copy",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("workorder_converted_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SalesOrder", "SalesOrder"),
                            ("WorkOrder", "WorkOrder"),
                        ],
                        default="SalesOrder",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiry_sales_orders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiry_sales_orders_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiry_sales_orders",
                        to="inquiry.inquiry",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiry_sales_orders_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "inquiry_sales_order",
                "permissions": [
                    ("print_inquiry_salesorder", "Can print Inquiry Sales Order"),
                    (
                        "download_inquiry_salesorder_excel_copy",
                        "Can download Inquiry Sales Order Excel",
                    ),
                    (
                        "download_inquiry_salesorder_pdf_copy",
                        "Can download Inquiry Sales Order PDF",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InquirySalesOrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("length", models.IntegerField(blank=True, default=0, null=True)),
                ("pieces", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "net_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("out_source", models.BooleanField(default=False, null=True)),
                ("cutting", models.BooleanField(default=False, null=True)),
                ("machining", models.BooleanField(default=False, null=True)),
                ("deburring", models.BooleanField(default=False, null=True)),
                (
                    "cutting_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "machining_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "deburring_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("anodising", models.BooleanField(default=False, null=True)),
                ("powder_coating", models.BooleanField(default=False, null=True)),
                ("pvdf", models.BooleanField(default=False, null=True)),
                (
                    "anodising_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("anodising_description", models.CharField(max_length=250, null=True)),
                (
                    "powder_coating_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "powder_coating_description",
                    models.CharField(max_length=250, null=True),
                ),
                (
                    "pvdf_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("pvdf_description", models.CharField(max_length=250, null=True)),
                (
                    "laser_marking_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "laser_marking_description",
                    models.CharField(max_length=250, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "alloy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.alloy",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiry_salesorder_detail_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiry_salesorder_detail_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inquiry_salesorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiry_salesorder_details",
                        to="inquiry_salesorder.inquirysalesorder",
                    ),
                ),
                (
                    "surface_finish",
                    models.ManyToManyField(
                        blank=True,
                        related_name="inquiry_salesorder_surface_finish",
                        to="common.jobworktype",
                    ),
                ),
                (
                    "temper",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.temper",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiry_salesorder_detail_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "inquiry_salesorder_detail",
                "permissions": [
                    (
                        "print_inquiry_salesorder_detail",
                        "Can print Inquiry Sales Order Detail",
                    ),
                    (
                        "download_inquiry_salesorder_detail_excel_copy",
                        "Can download Inquiry Sales Order Detail Excel",
                    ),
                    (
                        "download_inquiry_salesorder_detail_pdf_copy",
                        "Can download Inquiry Sales Order Detail PDF",
                    ),
                ],
            },
        ),
    ]
