# Generated by Django 5.1.1 on 2025-10-31 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry_salesorder", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inquirysalesorder",
            name="mode_of_packing",
        ),
    ]
