# Generated by Django 5.1.1 on 2025-10-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_packingmode"),
        ("inquiry_salesorder", "0002_remove_inquirysalesorder_mode_of_packing"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquirysalesorder",
            name="packing_mode",
            field=models.ManyToManyField(
                blank=True, related_name="inquiry_sales_orders", to="common.packingmode"
            ),
        ),
    ]
