# Generated by Django 5.1.1 on 2025-11-04 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry_salesorder", "0003_inquirysalesorder_packing_mode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inquirysalesorderdetail",
            old_name="net_weight",
            new_name="quantity",
        ),
    ]
