# Generated by Django 5.1.1 on 2025-11-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inquiry_salesorder",
            "0004_rename_net_weight_inquirysalesorderdetail_quantity",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquirysalesorderdetail",
            name="anodising_description",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="inquirysalesorderdetail",
            name="powder_coating_description",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="inquirysalesorderdetail",
            name="pvdf_description",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
