# Generated by Django 5.1.1 on 2025-11-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inquiry_salesorder",
            "0005_alter_inquirysalesorderdetail_anodising_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquirysalesorderdetail",
            name="laser_marking_description",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
