# Generated by Django 5.1.1 on 2026-03-19 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0025_remove_customer_customer_cu_custome_d3a0b9_idx_and_more"),
        ("die", "0079_rename_no_of_regrinds_dietool_regrinds"),
        (
            "inquiry_salesorder",
            "0006_alter_inquirysalesorderdetail_laser_marking_description",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="inquirysalesorder",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inquiry_sales_orders",
                to="customer.customer",
            ),
        ),
        migrations.AddField(
            model_name="inquirysalesorderdetail",
            name="section_no",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inquiry_salesorder_section_no",
                to="die.die",
            ),
        ),
    ]
