# Generated by Django 5.1.1 on 2026-03-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry_salesorder", "0007_inquirysalesorder_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquirysalesorder",
            name="terms_and_condition",
            field=models.TextField(blank=True, null=True),
        ),
    ]
