# Generated by Django 5.1.1 on 2026-04-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry_salesorder", "0008_inquirysalesorder_terms_and_condition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inquirysalesorder",
            name="purchase_order_number",
        ),
        migrations.AddField(
            model_name="inquirysalesorder",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inquirysalesorder",
            name="nalco_type",
            field=models.CharField(
                choices=[("Fixed", "Fixed"), ("Variable", "Variable")],
                default="Variable",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inquirysalesorder",
            name="project_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="inquirysalesorder",
            name="purchase_order_no",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="inquirysalesorder",
            name="tolerance",
            field=models.CharField(
                choices=[
                    ("Zero(0)", "Zero(0)"),
                    ("+-3%", "+-3%"),
                    ("+-5%", "+-5%"),
                    ("+-7%", "+-7%"),
                    ("+-10%", "+-10%"),
                    ("+3%", "+3%"),
                    ("+5%", "+5%"),
                    ("+7%", "+7%"),
                    ("+10%", "+10%"),
                    ("-3%", "-3%"),
                    ("-5%", "-5%"),
                    ("-7%", "-7%"),
                    ("-10%", "-10%"),
                ],
                default="Zero(0)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inquirysalesorderdetail",
            name="conversion",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="inquirysalesorderdetail",
            name="modify_nalco_rate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inquirysalesorderdetail",
            name="nalco_rate",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="inquirysalesorderdetail",
            name="nalco_rate_change_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inquirysalesorderdetail",
            name="packing_charge",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
