# Generated by Django 5.1.1 on 2026-04-13 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0025_remove_customer_customer_cu_custome_d3a0b9_idx_and_more"),
        (
            "inquiry_salesorder",
            "0009_remove_inquirysalesorder_purchase_order_number_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="inquirysalesorder",
            old_name="customer",
            new_name="bill_to",
        ),
        migrations.AddField(
            model_name="inquirysalesorder",
            name="ship_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inquiry_sales_orders_ship_to",
                to="customer.customer",
            ),
        ),
    ]
