# Generated by Django 5.1.1 on 2026-04-13 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry", "0011_alter_inquirydetail_alloy_and_more"),
        (
            "inquiry_salesorder",
            "0010_rename_customer_inquirysalesorder_bill_to_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquirysalesorder",
            name="inquiry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inquiry_sales_orders",
                to="inquiry.inquiry",
            ),
        ),
    ]
