# Generated by Django 5.1.1 on 2026-04-13 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry_salesorder", "0011_alter_inquirysalesorder_inquiry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inquirysalesorder",
            name="approved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inquiry_sales_orders_approved_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
