# Generated by Django 5.1.1 on 2026-04-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry_salesorder", "0012_inquirysalesorder_approved_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquirysalesorderdetail",
            name="max_weight",
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="inquirysalesorderdetail",
            name="min_weight",
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="inquirysalesorderdetail",
            name="net_weight",
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
