# Generated by Django 5.1.1 on 2026-04-13 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry_salesorder", "0013_inquirysalesorderdetail_max_weight_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inquirysalesorderdetail",
            old_name="packing_charge",
            new_name="packing_cost",
        ),
        migrations.RemoveField(
            model_name="inquirysalesorderdetail",
            name="quantity",
        ),
    ]
