# Generated by Django 5.1.1 on 2026-04-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inquiry_salesorder",
            "0014_rename_packing_charge_inquirysalesorderdetail_packing_cost_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="inquirysalesorderdetail",
            name="price_per_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
