# Generated by Django 4.2.8 on 2026-04-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry_salesorder", "0015_inquirysalesorderdetail_price_per_kg"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquirysalesorderdetail",
            name="salesorder_type",
            field=models.CharField(
                choices=[("In_House", "In_House"), ("Job_Work", "Job_Work")],
                default="In_House",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inquirysalesorder",
            name="order_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
