# Generated by Django 5.1.1 on 2026-05-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry_salesorder", "0016_inquirysalesorderdetail_salesorder_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquirysalesorder",
            name="order_type",
            field=models.CharField(
                default="order",
                max_length=50,
                verbose_name=(("order", "Order"), ("trial", "Trial")),
            ),
        ),
    ]
