# Generated by Django 5.1.1 on 2026-06-16 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry_salesorder", "0017_inquirysalesorder_order_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inquirysalesorderdetail",
            name="length",
        ),
    ]
