# Generated by Django 5.1.1 on 2026-06-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry_salesorder", "0018_remove_inquirysalesorderdetail_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquirysalesorderdetail",
            name="length",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
