# Generated by Django 5.1.1 on 2026-06-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry_salesorder", "0020_alter_inquirysalesorder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquirysalesorder",
            name="approval_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inquirysalesorder",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
