# Generated by Django 5.1.1 on 2026-06-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry_salesorder", "0021_inquirysalesorder_approval_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquirysalesorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("SalesOrder", "SalesOrder"),
                    ("WorkOrder", "WorkOrder"),
                    ("Pending_Fixed_Rate_Approval", "Pending_Fixed_Rate_Approval"),
                ],
                default="Pending_Fixed_Rate_Approval",
                max_length=100,
            ),
        ),
    ]
