# Generated by Django 5.1.1 on 2026-07-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry_salesorder", "0022_alter_inquirysalesorder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquirysalesorderdetail",
            name="customer_reference_number",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
