# Generated by Django 5.1.1 on 2026-01-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="store",
            options={
                "ordering": ["store_code"],
                "permissions": [
                    ("download_store_pdf_copy", "Can download store PDF"),
                    ("download_store_excel_copy", "Can download store Excel"),
                ],
            },
        ),
    ]
