# Generated by Django 5.1.1 on 2026-02-10 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0039_storetype"),
        ("store", "0003_remove_store_approve_remove_store_approve_remarks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="store_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="store_store_type",
                to="common.storetype",
            ),
        ),
    ]
