# Generated by Django 5.1.1 on 2025-09-25 13:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BundleInwardFlat",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("order_no", models.CharField(max_length=100)),
                ("remarks", models.TextField(null=True)),
                ("bill_to_customer_name", models.CharField(max_length=255)),
                ("ship_to_customer_name", models.CharField(max_length=255)),
                ("die_number", models.CharField(max_length=100)),
                ("length", models.IntegerField()),
                ("alloy_name", models.CharField(max_length=100)),
                ("bundle_no", models.CharField(max_length=100)),
                ("shift", models.CharField(max_length=10)),
                ("pieces", models.IntegerField()),
                ("weight", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "average_weight",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                ("gross_weight", models.DecimalField(decimal_places=3, max_digits=10)),
                ("packing_date", models.DateTimeField()),
                ("dispatch_date", models.DateTimeField(null=True)),
                ("hardness", models.CharField(max_length=100)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("dimension1", models.CharField(max_length=100)),
                ("dimension2", models.CharField(max_length=100)),
                ("dimension3", models.CharField(max_length=100)),
                ("dimension4", models.CharField(max_length=100)),
                ("color_code", models.CharField(max_length=100)),
                ("temper_name", models.CharField(max_length=100)),
                ("temper_code", models.CharField(max_length=100)),
                ("packing_type", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=100)),
                (
                    "jobworks",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("deleted", models.IntegerField()),
                ("is_excess_stock", models.BooleanField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "bundle_inward_flat",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BundleInward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                (
                    "bundle_no",
                    models.CharField(db_index=True, max_length=100, null=True),
                ),
                (
                    "shift",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B")], default="A", max_length=10
                    ),
                ),
                ("pieces", models.IntegerField(default=0)),
                ("weight", models.DecimalField(decimal_places=3, max_digits=10)),
                ("gross_weight", models.DecimalField(decimal_places=3, max_digits=10)),
                ("packing_date", models.DateTimeField(auto_now=True, null=True)),
                ("dispatch_date", models.DateTimeField(null=True)),
                ("hardness", models.CharField(max_length=100)),
                ("remarks", models.TextField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Dispatched", "Dispatched"), ("Packed", "Packed")],
                        default="Packed",
                        max_length=100,
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("verified_date", models.DateTimeField(auto_now=True, null=True)),
                ("added_for_outword", models.BooleanField(default=False)),
                ("added_for_warehouse", models.BooleanField(default=False)),
                ("is_excess_stock", models.BooleanField(default=False)),
                ("is_warehouse", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "bundle_inward",
                "permissions": [
                    ("print_bundle_inward_copy", "Can print bundle inward"),
                    (
                        "download_bundle_inward_excel_copy",
                        "Can download bundle inward Excel",
                    ),
                    ("print_current_stock_copy", "Can print current stock"),
                    (
                        "download_current_stock_excel_copy",
                        "Can download current stock Excel",
                    ),
                    ("print_packing_report_copy", "Can print packing report"),
                    (
                        "download_packing_report_excel_copy",
                        "Can download packing report Excel",
                    ),
                    (
                        "print_packing_datewise_report_copy",
                        "Can print packing datewise report",
                    ),
                    (
                        "download_packing_datewise_report_excel_copy",
                        "Can download packing datewise report Excel",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExcessStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                ("length", models.IntegerField(default=0, null=True)),
                ("weight", models.DecimalField(decimal_places=3, max_digits=10)),
                ("gross_weight", models.DecimalField(decimal_places=3, max_digits=10)),
                ("pieces", models.IntegerField(default=0)),
                (
                    "shift",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B")], default="A", max_length=10
                    ),
                ),
                ("hardness_value", models.CharField(max_length=100)),
                ("remarks", models.TextField(null=True)),
            ],
            options={
                "db_table": "excess_stock",
                "permissions": [
                    ("print_excess_stock_copy", "Can print excess stock"),
                    (
                        "download_excess_stock_excel_copy",
                        "Can download excess stock Excel",
                    ),
                ],
            },
        ),
    ]
