# Generated by Django 5.1.1 on 2025-09-25 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bundle_inward", "0001_initial"),
        ("die", "0002_initial"),
        ("product", "0001_initial"),
        ("workorder", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bundleinward",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bundleinward",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bundleinward",
            name="verify_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bundle_verify_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bundleinward",
            name="workorder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bundle_inward_workorder",
                to="workorder.workorder",
            ),
        ),
        migrations.AddField(
            model_name="bundleinward",
            name="workorder_detail",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bundle_inward_workorder_detail",
                to="workorder.workorderdetail",
            ),
        ),
        migrations.AddField(
            model_name="excessstock",
            name="alloy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="excess_stock_alloy",
                to="product.alloy",
            ),
        ),
        migrations.AddField(
            model_name="excessstock",
            name="bundle_inward",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="excess_stock_bundle_inward",
                to="bundle_inward.bundleinward",
            ),
        ),
        migrations.AddField(
            model_name="excessstock",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="excessstock",
            name="die_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="excess_stock_die",
                to="die.die",
            ),
        ),
        migrations.AddField(
            model_name="excessstock",
            name="temper",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="excess_stock_temper",
                to="product.temper",
            ),
        ),
        migrations.AddField(
            model_name="excessstock",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="bundleinward",
            index=models.Index(
                fields=["bundle_no"], name="bundle_inwa_bundle__523614_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bundleinward",
            index=models.Index(
                fields=["workorder"], name="bundle_inwa_workord_23f0e8_idx"
            ),
        ),
    ]
