# Generated by Django 5.1.1 on 2025-11-07 09:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundle_inward", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bundleinward",
            name="packing_date",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
