# Generated by Django 5.1.1 on 2025-11-12 06:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundle_inward", "0003_alter_bundleinward_packing_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bundleinward",
            name="approve",
        ),
        migrations.RemoveField(
            model_name="bundleinward",
            name="approve_remarks",
        ),
        migrations.RemoveField(
            model_name="bundleinward",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="bundleinward",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="bundleinward",
            name="done_flag",
        ),
        migrations.RemoveField(
            model_name="bundleinward",
            name="f_id",
        ),
        migrations.RemoveField(
            model_name="bundleinward",
            name="reject",
        ),
        migrations.RemoveField(
            model_name="excessstock",
            name="approve",
        ),
        migrations.RemoveField(
            model_name="excessstock",
            name="approve_remarks",
        ),
        migrations.RemoveField(
            model_name="excessstock",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="excessstock",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="excessstock",
            name="done_flag",
        ),
        migrations.RemoveField(
            model_name="excessstock",
            name="f_id",
        ),
        migrations.RemoveField(
            model_name="excessstock",
            name="reject",
        ),
        migrations.AddField(
            model_name="bundleinward",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bundleinward",
            name="deleted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bundleinward_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="excessstock",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="excessstock",
            name="deleted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="excessstock_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bundleinward",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bundleinward",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bundleinward_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bundleinward",
            name="dispatch_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bundleinward",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bundleinward",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bundleinward",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bundleinward_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="excessstock",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="excessstock",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="excessstock_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="excessstock",
            name="length",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="excessstock",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="excessstock",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="excessstock",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="excessstock_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
