# Generated by Django 5.1.1 on 2025-11-12 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bundle_inward", "0004_remove_bundleinward_approve_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bundleinwardflat",
            options={},
        ),
    ]
