# Generated by Django 5.1.1 on 2025-11-12 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bundle_inward", "0005_alter_bundleinwardflat_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bundleinwardflat",
            options={"managed": False},
        ),
    ]
