# Generated by Django 5.1.1 on 2025-11-12 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bundle_inward", "0006_alter_bundleinwardflat_options"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
    CREATE OR REPLACE VIEW bundle_inward_flat AS
    SELECT bi.id,
    wo.order_no,
    bi.remarks,
    c.customer_name AS bill_to_customer_name,
    cu.customer_name AS ship_to_customer_name,
    dp.die_number,
    wod.length,
    al.alloy_code AS alloy_name,
    bi.bundle_no,
    bi.shift,
    bi.pieces,
    bi.weight,
    bi.weight / NULLIF(bi.pieces, 0)::numeric AS average_weight,
    bi.gross_weight,
    bi.packing_date,
    bi.dispatch_date,
    bi.hardness,
    (up.first_name::text || ' '::text) || up.last_name::text AS updated_by,
    (uc.first_name::text || ' '::text) || uc.last_name::text AS created_by,
    dp.dimension1,
    dp.dimension2,
    dp.dimension3,
    dp.dimension4,
    al.color_code,
    tm.name AS temper_name,
    tm.code AS temper_code,
    bi.status,
    array_agg(jw.name) AS jobworks,
    bi.deleted,
    bi.is_excess_stock,
    bi.created_at,
    bi.updated_at
   FROM bundle_inward bi
     JOIN workorder wo ON bi.workorder_id = wo.id
     JOIN workorder_detail wod ON bi.workorder_detail_id = wod.id
     JOIN customer_customer c ON wo.bill_to_id = c.id
     JOIN customer_customer cu ON wo.ship_to_id = cu.id
     JOIN die dp ON wod.die_profile_id = dp.id
     JOIN alloy al ON wod.alloy_id = al.id
     JOIN temper tm ON wod.temper_id = tm.id
     JOIN workorder_detail_jobworks wdj ON wod.id = wdj.workorderdetail_id
     JOIN jobwork_type jw ON jw.id = wdj.jobworktype_id
     LEFT JOIN "user" up ON bi.updated_by_id = up.id
     LEFT JOIN "user" uc ON bi.created_by_id = uc.id
    GROUP BY bi.id, wo.order_no, bi.remarks, c.customer_name, al.alloy_code,
    cu.customer_name, dp.die_number, wod.length, bi.bundle_no, 
    bi.shift, bi.pieces, bi.weight, bi.gross_weight, bi.packing_date, 
    bi.dispatch_date, bi.hardness, up.first_name, up.last_name, 
    uc.first_name, uc.last_name, dp.dimension1, dp.dimension2, 
    dp.dimension3, dp.dimension4, al.color_code, tm.name, tm.code, 
    bi.status, bi.deleted, bi.is_excess_stock, 
    bi.created_at, bi.updated_at;
            """,
            reverse_sql="DROP VIEW IF EXISTS bundle_inward_flat;",
        ),
    ]
