# Generated by Django 5.1.1 on 2026-01-13 05:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundle_inward", "0007_create_list_view"),
        ("die", "0045_merge_20260108_1600"),
        ("product", "0025_temper_section_thickness_over_and_more"),
        ("workorder", "0012_alter_workorderdetail_nalco_rate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="BundleInwardFlat",
        ),
        migrations.RenameIndex(
            model_name="bundleinward",
            new_name="bundle_no_idx",
            old_name="bundle_inwa_bundle__523614_idx",
        ),
        migrations.RenameIndex(
            model_name="bundleinward",
            new_name="workorder_idx",
            old_name="bundle_inwa_workord_23f0e8_idx",
        ),
        migrations.AlterField(
            model_name="bundleinward",
            name="added_for_outword",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="bundleinward",
            name="added_for_warehouse",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="bundleinward",
            name="bundle_no",
            field=models.CharField(
                db_index=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="bundleinward",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bundleinward",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bundleinward",
            name="dispatch_date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="bundleinward",
            name="hardness",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="bundleinward",
            name="is_excess_stock",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="bundleinward",
            name="is_warehouse",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="bundleinward",
            name="packing_date",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="bundleinward",
            name="shift",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B")],
                db_index=True,
                default="A",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="bundleinward",
            name="status",
            field=models.CharField(
                choices=[
                    ("Dispatched", "Dispatched"),
                    ("Packed", "Packed"),
                    ("Warehouse", "Warehouse"),
                    ("Excess-Stock", "Excess-Stock"),
                ],
                db_index=True,
                default="Packed",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="bundleinward",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="bundleinward",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bundleinward",
            name="verified",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="excessstock",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="excessstock",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="excessstock",
            name="hardness_value",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="excessstock",
            name="length",
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="excessstock",
            name="shift",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B")],
                db_index=True,
                default="A",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="excessstock",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="excessstock",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="bundleinward",
            index=models.Index(
                fields=["workorder_detail"], name="workorder_detail_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bundleinward",
            index=models.Index(fields=["status"], name="status_idx"),
        ),
        migrations.AddIndex(
            model_name="bundleinward",
            index=models.Index(fields=["verified"], name="verified_idx"),
        ),
        migrations.AddIndex(
            model_name="bundleinward",
            index=models.Index(fields=["shift"], name="shift_idx"),
        ),
        migrations.AddIndex(
            model_name="bundleinward",
            index=models.Index(fields=["packing_date"], name="packing_date_idx"),
        ),
        migrations.AddIndex(
            model_name="bundleinward",
            index=models.Index(fields=["dispatch_date"], name="dispatch_date_idx"),
        ),
        migrations.AddIndex(
            model_name="bundleinward",
            index=models.Index(fields=["hardness"], name="hardness_idx"),
        ),
        migrations.AddIndex(
            model_name="bundleinward",
            index=models.Index(fields=["verify_by"], name="verify_by_idx"),
        ),
        migrations.AddIndex(
            model_name="bundleinward",
            index=models.Index(
                fields=["added_for_warehouse"], name="added_for_warehouse_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bundleinward",
            index=models.Index(
                fields=["added_for_outword"], name="added_for_outword_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bundleinward",
            index=models.Index(fields=["is_excess_stock"], name="is_excess_stock_idx"),
        ),
        migrations.AddIndex(
            model_name="bundleinward",
            index=models.Index(fields=["is_warehouse"], name="is_warehouse_idx"),
        ),
        migrations.AddIndex(
            model_name="bundleinward",
            index=models.Index(
                fields=["status", "verified"], name="status_verified_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bundleinward",
            index=models.Index(
                fields=["workorder", "status"], name="workorder_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bundleinward",
            index=models.Index(
                fields=["deleted", "created_at"], name="deleted_created_at_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bundleinward",
            index=models.Index(
                fields=["packing_date", "shift"], name="packing_date_shift_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bundleinward",
            index=models.Index(
                fields=["verified", "verified_date"], name="verified_verified_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bundleinward",
            index=models.Index(
                fields=["is_warehouse", "is_excess_stock"], name="warehouse_excess_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bundleinward",
            index=models.Index(fields=["-created_at"], name="created_at_desc_idx"),
        ),
        migrations.AddIndex(
            model_name="excessstock",
            index=models.Index(
                fields=["bundle_inward"], name="bundle_inward_excess_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="excessstock",
            index=models.Index(fields=["die_profile"], name="die_profile_excess_idx"),
        ),
        migrations.AddIndex(
            model_name="excessstock",
            index=models.Index(fields=["alloy"], name="alloy_excess_idx"),
        ),
        migrations.AddIndex(
            model_name="excessstock",
            index=models.Index(fields=["temper"], name="temper_excess_idx"),
        ),
        migrations.AddIndex(
            model_name="excessstock",
            index=models.Index(fields=["shift"], name="shift_excess_idx"),
        ),
        migrations.AddIndex(
            model_name="excessstock",
            index=models.Index(
                fields=["hardness_value"], name="hardness_value_excess_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="excessstock",
            index=models.Index(fields=["length"], name="length_excess_idx"),
        ),
        migrations.AddIndex(
            model_name="excessstock",
            index=models.Index(
                fields=["die_profile", "alloy", "temper"], name="die_alloy_temper_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="excessstock",
            index=models.Index(
                fields=["bundle_inward", "shift"], name="bundle_shift_excess_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="excessstock",
            index=models.Index(
                fields=["deleted", "created_at"], name="deleted_created_at_excess_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="excessstock",
            index=models.Index(
                fields=["-created_at"], name="created_at_desc_excess_idx"
            ),
        ),
    ]
