# Generated by Django 5.1.1 on 2026-01-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundle_inward", "0008_delete_bundleinwardflat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bundleinward",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="excessstock",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
