# Generated by Django 5.1.1 on 2026-04-21 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bundle_inward", "0009_alter_bundleinward_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="bundleinward",
            name="bundle_no_idx",
        ),
        migrations.RemoveIndex(
            model_name="bundleinward",
            name="workorder_idx",
        ),
        migrations.RemoveIndex(
            model_name="bundleinward",
            name="workorder_detail_idx",
        ),
        migrations.RemoveIndex(
            model_name="bundleinward",
            name="status_idx",
        ),
        migrations.RemoveIndex(
            model_name="bundleinward",
            name="verified_idx",
        ),
        migrations.RemoveIndex(
            model_name="bundleinward",
            name="shift_idx",
        ),
        migrations.RemoveIndex(
            model_name="bundleinward",
            name="packing_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="bundleinward",
            name="hardness_idx",
        ),
        migrations.RemoveIndex(
            model_name="bundleinward",
            name="verify_by_idx",
        ),
        migrations.RemoveIndex(
            model_name="bundleinward",
            name="added_for_outword_idx",
        ),
        migrations.RemoveIndex(
            model_name="bundleinward",
            name="is_excess_stock_idx",
        ),
        migrations.RemoveIndex(
            model_name="bundleinward",
            name="is_warehouse_idx",
        ),
        migrations.RemoveIndex(
            model_name="bundleinward",
            name="status_verified_idx",
        ),
        migrations.RemoveIndex(
            model_name="bundleinward",
            name="deleted_created_at_idx",
        ),
        migrations.RemoveIndex(
            model_name="bundleinward",
            name="packing_date_shift_idx",
        ),
        migrations.RemoveIndex(
            model_name="bundleinward",
            name="verified_verified_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="bundleinward",
            name="created_at_desc_idx",
        ),
        migrations.RemoveField(
            model_name="bundleinward",
            name="shift",
        ),
    ]
