# Generated by Django 5.1.1 on 2026-02-04 07:11

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundle_verification", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockverification",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 9, 12, 653289, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stockverification",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 9, 14, 820619, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
