# Generated by Django 5.1.1 on 2026-02-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundle_verification", "0003_alter_stockverification_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockverification",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
