# Generated by Django 5.1.1 on 2025-09-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BundleOutward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                ("finalized_bundle_ids", models.TextField(blank=True, default="")),
                ("outward_bundle_ids", models.TextField(default="", null=True)),
                ("slip_no", models.CharField(max_length=100, null=True)),
                ("date_prepared", models.DateTimeField(auto_now=True, null=True)),
                (
                    "shift",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B")], default="A", max_length=10
                    ),
                ),
                ("transporter_name", models.CharField(max_length=100, null=True)),
                ("vehicle_no", models.CharField(max_length=100, null=True)),
                (
                    "dispatch_to",
                    models.CharField(
                        choices=[("Warehouse", "Warehouse"), ("Customer", "Customer")],
                        default="Warehouse",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("approved", models.BooleanField(default=False, null=True)),
                ("remarks", models.TextField(null=True)),
                ("dispatch_date", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "bundle_outward",
                "permissions": [
                    ("print_bundle_outward_copy", "Can print bundle outward"),
                    (
                        "download_bundle_outward_excel_copy",
                        "Can download bundle outward Excel",
                    ),
                    ("print_dispatch_report_copy", "Can print dispatch report"),
                    (
                        "download_dispatch_report_excel_copy",
                        "Can download dispatch report Excel",
                    ),
                ],
            },
        ),
    ]
