# Generated by Django 5.1.1 on 2025-11-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundle_inward", "0002_initial"),
        ("bundle_outward", "0003_remove_bundleoutward_finalized_bundle_ids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bundleoutward",
            name="finalized_bundles",
            field=models.ManyToManyField(
                blank=True,
                related_name="finalized_in_bundle_outwards",
                through="bundle_outward.BundleOutwardInward",
                to="bundle_inward.bundleinward",
            ),
        ),
        migrations.AddField(
            model_name="bundleoutward",
            name="outward_bundles",
            field=models.ManyToManyField(
                blank=True,
                related_name="outward_in_bundle_outwards",
                through="bundle_outward.BundleOutwardOutward",
                to="bundle_inward.bundleinward",
            ),
        ),
    ]
