# Generated by Django 5.2.5 on 2025-12-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bundle_outward", "0005_remove_bundleoutward_approve_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bundleoutward",
            name="transporter_name",
        ),
        migrations.RemoveField(
            model_name="bundleoutward",
            name="vehicle_no",
        ),
    ]
