# Generated by Django 5.2.5 on 2025-12-10 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundle_outward", "0006_remove_bundleoutward_transporter_name_and_more"),
        ("transporter", "0006_alter_transporter_opening_balance"),
        ("vehicle_master", "0003_alter_vehiclemaster_party_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="bundleoutward",
            name="transporter_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bundle_outword_transporter_name",
                to="transporter.transporter",
            ),
        ),
        migrations.AddField(
            model_name="bundleoutward",
            name="vehicle_no",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bundle_outword_vehicle_no",
                to="vehicle_master.vehiclemaster",
            ),
        ),
    ]
