# Generated by Django 5.2.5 on 2025-12-10 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundle_outward", "0007_bundleoutward_transporter_name_and_more"),
        ("transporter", "0006_alter_transporter_opening_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bundleoutward",
            name="transporter_name",
        ),
        migrations.AddField(
            model_name="bundleoutward",
            name="party_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bundle_outword_party_name",
                to="transporter.transporter",
            ),
        ),
    ]
