# Generated by Django 5.1.1 on 2026-01-19 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundle_inward", "0008_delete_bundleinwardflat_and_more"),
        ("bundle_outward", "0008_remove_bundleoutward_transporter_name_and_more"),
        ("customer", "0016_alter_accountgroup_created_by_and_more"),
        ("transporter", "0007_alter_transporter_created_by_and_more"),
        ("vehicle_master", "0004_alter_vehiclemaster_created_at_and_more"),
        ("workorder", "0012_alter_workorderdetail_nalco_rate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="bundleoutward",
            name="approved",
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="bundleoutward",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bundleoutward",
            name="date_prepared",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="bundleoutward",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bundleoutward",
            name="dispatch_date",
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="bundleoutward",
            name="dispatch_to",
            field=models.CharField(
                choices=[("Warehouse", "Warehouse"), ("Customer", "Customer")],
                db_index=True,
                default="Warehouse",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bundleoutward",
            name="shift",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B")],
                db_index=True,
                default="A",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="bundleoutward",
            name="slip_no",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="bundleoutward",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="bundleoutward",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="bundleoutward",
            index=models.Index(
                fields=["workorder", "approved"], name="idx_workorder_approved"
            ),
        ),
        migrations.AddIndex(
            model_name="bundleoutward",
            index=models.Index(
                fields=["dispatch_date", "shift"], name="idx_dispatch_date_shift"
            ),
        ),
        migrations.AddIndex(
            model_name="bundleoutward",
            index=models.Index(
                fields=["customer", "dispatch_to"], name="idx_customer_dispatch_to"
            ),
        ),
        migrations.AddIndex(
            model_name="bundleoutward",
            index=models.Index(fields=["slip_no"], name="idx_slip_no"),
        ),
        migrations.AddIndex(
            model_name="bundleoutward",
            index=models.Index(
                fields=["approved", "dispatch_date"], name="idx_approved_dispatch_date"
            ),
        ),
    ]
