# Generated by Django 5.1.1 on 2026-01-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundle_outward", "0009_alter_bundleoutward_approved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bundleoutward",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
