# Generated by Django 5.1.1 on 2026-02-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundle_outward", "0011_alter_bundleoutwardinward_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bundleoutwardinward",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bundleoutwardoutward",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
