# Generated by Django 5.1.1 on 2026-03-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bundle_outward", "0012_alter_bundleoutwardinward_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bundleoutward",
            name="party_name",
        ),
    ]
