# Generated by Django 5.1.1 on 2026-03-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundle_outward", "0013_remove_bundleoutward_party_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="bundleoutward",
            name="party_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
