# Generated by Django 5.1.1 on 2026-04-21 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bundle_outward", "0014_bundleoutward_party_name"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="bundleoutward",
            name="idx_workorder_approved",
        ),
        migrations.RemoveIndex(
            model_name="bundleoutward",
            name="idx_dispatch_date_shift",
        ),
        migrations.RemoveField(
            model_name="bundleoutward",
            name="shift",
        ),
    ]
