# Generated by Django 5.1.1 on 2025-09-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "permissions": [
                    (
                        "download_account_group_pdf_copy",
                        "Can download account group PDF",
                    ),
                    (
                        "download_account_group_excel_copy",
                        "Can download account group Excel",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BankingDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Bank Name"
                    ),
                ),
                (
                    "bank_account_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Bank Account Number",
                    ),
                ),
                (
                    "bank_ifsc_code",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        verbose_name="Bank IFSC Code",
                    ),
                ),
                (
                    "bank_branch_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Branch Address",
                    ),
                ),
                (
                    "beneficiary_swift_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Beneficiary Swift Code",
                    ),
                ),
                (
                    "bank_ad_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Bank AD Code",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BillingPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                ("person_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("phone_number", models.CharField(max_length=15)),
            ],
            options={
                "db_table": "customer_billingperson",
            },
        ),
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                (
                    "contact_person_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Contact Person Name",
                    ),
                ),
                (
                    "contact_person_designation",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Contact Person Designation",
                    ),
                ),
                (
                    "contact_person_mobile_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Contact Person Mobile Number",
                    ),
                ),
                (
                    "contact_person_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Contact Person Email",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                (
                    "gstin_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="GSTIN Number",
                    ),
                ),
                (
                    "gst_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="GST Type"
                    ),
                ),
                (
                    "pan_number",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="PAN Number"
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Customer Name"
                    ),
                ),
                (
                    "customer_number",
                    models.CharField(
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Customer Number",
                    ),
                ),
                ("person_name", models.CharField(max_length=250, null=True)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="Phone Number"),
                ),
                (
                    "delivery_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Delivery Days"
                    ),
                ),
                (
                    "udyam_no",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Udyam No / MSME",
                    ),
                ),
                (
                    "applicable_gst",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Applicable GST",
                    ),
                ),
                ("customer_logo", models.CharField(max_length=250, null=True)),
                (
                    "office_address_shop",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Office Address - Shop No, Building, Apartment",
                    ),
                ),
                (
                    "office_address_area",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Office Address - Area, Street",
                    ),
                ),
                (
                    "office_address_landmark",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Office Address - Landmark",
                    ),
                ),
                (
                    "office_address_pin_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Office Address - Pin Code",
                    ),
                ),
                (
                    "office_address_city",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Office Address - City",
                    ),
                ),
                (
                    "office_address_state",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Office Address - State",
                    ),
                ),
                (
                    "office_address_country",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Office Address - Country",
                    ),
                ),
                (
                    "factory_address_shop",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Factory Address - Shop No, Building, Apartment",
                    ),
                ),
                (
                    "factory_address_area",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Factory Address - Area, Street",
                    ),
                ),
                (
                    "factory_address_landmark",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Factory Address - Landmark",
                    ),
                ),
                (
                    "factory_address_pin_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Factory Address - Pin Code",
                    ),
                ),
                (
                    "factory_address_city",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Factory Address - City",
                    ),
                ),
                (
                    "factory_address_state",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Factory Address - State",
                    ),
                ),
                (
                    "factory_address_country",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Factory Address - Country",
                    ),
                ),
                (
                    "customer_section_no",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Customer Section No",
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        choices=[("INDIAN", "Indian"), ("OVERSEAS", "Overseas")],
                        default="INDIAN",
                        max_length=15,
                    ),
                ),
                (
                    "import_export_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "beneficiary_agent_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("trade_name", models.CharField(blank=True, max_length=100, null=True)),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                ("fax_number", models.CharField(blank=True, max_length=15, null=True)),
                ("website", models.CharField(blank=True, null=True)),
            ],
            options={
                "permissions": [
                    (
                        "print_customer_workorder_report_pdf_copy",
                        "Can print customer workorder report",
                    ),
                    ("download_customer_pdf_copy", "Can download customer PDF"),
                    ("download_customer_excel_copy", "Can download customer Excel"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomerCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "permissions": [
                    (
                        "download_customer_category_pdf_copy",
                        "Can download customer category PDF",
                    ),
                    (
                        "download_customer_category_excel_copy",
                        "Can download customer category Excel",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomerType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "permissions": [
                    (
                        "download_customer_type_pdf_copy",
                        "Can download customer type PDF",
                    ),
                    (
                        "download_customer_type_excel_copy",
                        "Can download customer type Excel",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShipingPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                ("person_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("phone_number", models.CharField(max_length=15)),
            ],
            options={
                "db_table": "customer_shipingperson",
            },
        ),
        migrations.CreateModel(
            name="SiteLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                ("gst_number", models.CharField(max_length=15)),
                ("company_legal_name", models.CharField(max_length=255, unique=True)),
                ("site_name", models.CharField(max_length=255)),
                ("billing_shop_no", models.CharField(max_length=255, null=True)),
                ("billing_area_street", models.CharField(max_length=255, null=True)),
                (
                    "billing_landmark",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("billing_pincode", models.CharField(max_length=20, null=True)),
                ("billing_city", models.CharField(max_length=255, null=True)),
                ("billing_state", models.CharField(max_length=255, null=True)),
                (
                    "shipping_shop_no",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shipping_area_street",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shipping_landmark",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shipping_pincode",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "shipping_city",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shipping_state",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "customer_sitelocation",
                "permissions": [
                    (
                        "download_site_location_pdf_copy",
                        "Can download site location PDF",
                    ),
                    (
                        "download_site_location_excel_copy",
                        "Can download site location Excel",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UnderGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "permissions": [
                    ("download_under_group_pdf_copy", "Can download under group PDF"),
                    (
                        "download_under_group_excel_copy",
                        "Can download under group Excel",
                    ),
                ],
            },
        ),
    ]
