# Generated by Django 5.1.1 on 2025-11-10 07:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_remove_undergroup_approve_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountgroup",
            name="approve",
        ),
        migrations.RemoveField(
            model_name="accountgroup",
            name="approve_remarks",
        ),
        migrations.RemoveField(
            model_name="accountgroup",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="accountgroup",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="accountgroup",
            name="done_flag",
        ),
        migrations.RemoveField(
            model_name="accountgroup",
            name="f_id",
        ),
        migrations.RemoveField(
            model_name="accountgroup",
            name="reject",
        ),
        migrations.AddField(
            model_name="accountgroup",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accountgroup",
            name="deleted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accountgroup_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="accountgroup",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="accountgroup",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accountgroup_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="accountgroup",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="accountgroup",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accountgroup_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
