# Generated by Django 5.1.1 on 2025-12-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0006_remove_bankingdetails_approve_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customertype",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
