# Generated by Django 5.1.1 on 2025-12-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0007_alter_customertype_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="account_group",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="under_group",
        ),
    ]
