# Generated by Django 5.1.1 on 2025-12-30 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0008_remove_customer_account_group_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="account",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="company_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CUSTOMER", "Customer"),
                    ("VENDOR", "Vendor"),
                    ("CUSTOMER_VENDOR", "Customer_Vendor"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="credit_limit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="customer_balance",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="due_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_company_visible_on_documents",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="licence_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Customer Number",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customer.customertype",
                verbose_name="Customer Type",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="sales_executive",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_executive",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="sales_executive_assistant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_executive_assistant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
