# Generated by Django 5.1.1 on 2025-12-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0009_customer_account_customer_company_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="company_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CUSTOMER", "Customer"),
                    ("VENDOR", "Vendor"),
                    ("CUSTOMER_VENDOR", "Customer_Vendor"),
                ],
                default="CUSTOMER",
                max_length=50,
                null=True,
            ),
        ),
    ]
