# Generated by Django 5.1.1 on 2026-01-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0010_alter_customer_company_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="account",
            new_name="amount",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="customer_logo",
        ),
        migrations.AlterField(
            model_name="customer",
            name="company_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("customer", "customer"),
                    ("vendor", "vendor"),
                    ("customer_vendor", "customer_vendor"),
                ],
                default="customer",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_balance",
            field=models.CharField(
                blank=True,
                choices=[("credit", "credit"), ("debit", "debit")],
                default="credit",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Customer Name",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="gstin_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                unique=True,
                verbose_name="GSTIN Number",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="licence_no",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="pan_number",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="PAN Number",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="udyam_no",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Udyam No / MSME",
            ),
        ),
    ]
