# Generated by Django 5.1.1 on 2026-01-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0011_rename_account_customer_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="is_company_visible_on_documents",
        ),
    ]
