# Generated by Django 5.1.1 on 2026-01-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0012_remove_customer_is_company_visible_on_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="is_company_visible_on_documents",
            field=models.BooleanField(default=False),
        ),
    ]
