# Generated by Django 5.1.1 on 2026-01-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0013_customer_is_company_visible_on_documents"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bankingdetails",
            unique_together={("bank_account_number",)},
        ),
    ]
