# Generated by Django 5.1.1 on 2026-01-06 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0014_alter_bankingdetails_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bankingdetails",
            index=models.Index(
                fields=["customer"], name="customer_ba_custome_fd1997_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bankingdetails",
            index=models.Index(
                fields=["deleted"], name="customer_ba_deleted_f52b72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bankingdetails",
            index=models.Index(
                fields=["customer", "deleted"], name="customer_ba_custome_df7b85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["customer_type"], name="customer_cu_custome_432dbb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["sales_executive"], name="customer_cu_sales_e_680124_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["sales_executive_assistant"],
                name="customer_cu_sales_e_57547a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["created_by"], name="customer_cu_created_76b721_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["updated_by"], name="customer_cu_updated_1691a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["deleted"], name="customer_cu_deleted_812bdf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["company_type"], name="customer_cu_company_13368b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["gstin_number"], name="customer_cu_gstin_n_ecdcd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["pan_number"], name="customer_cu_pan_num_67cf67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["customer_number"], name="customer_cu_custome_d3a0b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["deleted", "company_type"],
                name="customer_cu_deleted_35da00_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["deleted", "created_at"], name="customer_cu_deleted_1180aa_idx"
            ),
        ),
    ]
