# Generated by Django 5.1.1 on 2026-01-19 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0018_delete_accountgroup_customercategory_sitelocation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customertype",
            options={
                "ordering": ["id", "name"],
                "permissions": [
                    (
                        "download_customer_type_pdf_copy",
                        "Can download customer type PDF",
                    ),
                    (
                        "download_customer_type_excel_copy",
                        "Can download customer type Excel",
                    ),
                ],
            },
        ),
    ]
