# Generated by Django 5.1.1 on 2026-01-19 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0019_alter_customertype_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customertype",
            options={
                "ordering": ["-id"],
                "permissions": [
                    (
                        "download_customer_type_pdf_copy",
                        "Can download customer type PDF",
                    ),
                    (
                        "download_customer_type_excel_copy",
                        "Can download customer type Excel",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="customertype",
            index=models.Index(fields=["name"], name="customer_cu_name_0053d1_idx"),
        ),
        migrations.AddIndex(
            model_name="customertype",
            index=models.Index(
                fields=["created_at"], name="customer_cu_created_d6efb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customertype",
            index=models.Index(
                fields=["updated_at"], name="customer_cu_updated_7d6013_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customertype",
            index=models.Index(
                fields=["deleted"], name="customer_cu_deleted_509794_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customertype",
            index=models.Index(
                fields=["deleted", "created_at"], name="customer_cu_deleted_e5916f_idx"
            ),
        ),
    ]
