# Generated by Django 5.1.1 on 2026-01-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0020_alter_customertype_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankingdetails",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customertype",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
