# Generated by Django 5.1.1 on 2026-02-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0021_alter_bankingdetails_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankingdetails",
            name="bank_ifsc_code",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Bank IFSC Code"
            ),
        ),
    ]
