# Generated by Django 5.1.1 on 2026-02-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0022_alter_bankingdetails_bank_ifsc_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="applicable_gst",
            field=models.CharField(
                blank=True,
                choices=[("cgst", "cgst"), ("igst", "igst"), ("sgst", "sgst")],
                max_length=10,
                null=True,
                verbose_name="Applicable GST",
            ),
        ),
    ]
