# Generated by Django 5.1.1 on 2026-02-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0023_alter_customer_applicable_gst"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="applicable_gst",
            field=models.CharField(
                blank=True,
                choices=[("IGST", "IGST"), ("SGST_CGST", "SGST_CGST")],
                max_length=10,
                null=True,
                verbose_name="Applicable GST",
            ),
        ),
    ]
