# Generated by Django 5.1.1 on 2026-02-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0024_alter_customer_applicable_gst"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customer",
            name="customer_cu_custome_d3a0b9_idx",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="customer_number",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="customer_section_no",
        ),
    ]
