# Generated by Django 5.1.1 on 2025-09-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "item",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Alloy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=25)),
                ("color_code", models.CharField(max_length=50)),
                ("ingredient", models.TextField()),
                (
                    "application",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("remark", models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                "db_table": "alloy",
                "permissions": [
                    ("download_alloy_pdf_copy", "Can download alloy PDF"),
                    ("download_alloy_excel_copy", "Can download alloy Excel"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Temper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=25, unique=True)),
                ("code", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "temper",
                "permissions": [
                    ("download_temper_pdf_copy", "Can download temper PDF"),
                    ("download_temper_excel_copy", "Can download temper Excel"),
                ],
            },
        ),
    ]
