# Generated by Django 5.1.1 on 2025-11-10 05:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="temper",
            name="approve",
        ),
        migrations.RemoveField(
            model_name="temper",
            name="approve_remarks",
        ),
        migrations.RemoveField(
            model_name="temper",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="temper",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="temper",
            name="done_flag",
        ),
        migrations.RemoveField(
            model_name="temper",
            name="f_id",
        ),
        migrations.RemoveField(
            model_name="temper",
            name="reject",
        ),
        migrations.AddField(
            model_name="temper",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="temper",
            name="deleted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="temper_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="temper",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="temper",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="temper_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="temper",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="temper",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="temper_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
