# Generated by Django 5.2.5 on 2025-12-16 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_remove_alloy_approve_remove_alloy_approve_remarks_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alloy",
            name="application",
        ),
        migrations.RemoveField(
            model_name="alloy",
            name="color_code",
        ),
        migrations.RemoveField(
            model_name="alloy",
            name="ingredient",
        ),
    ]
