# Generated by Django 5.2.5 on 2025-12-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product",
            "0006_alloy_al_max_alloy_al_min_alloy_bi_max_alloy_bi_min_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="alloy",
            name="name",
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="std_no",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
