# Generated by Django 5.2.5 on 2025-12-18 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_alter_alloy_name_alter_alloy_std_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alloy",
            name="name",
        ),
        migrations.RemoveField(
            model_name="alloy",
            name="std_no",
        ),
    ]
