# Generated by Django 5.2.5 on 2025-12-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_remove_alloy_name_remove_alloy_std_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="alloy",
            name="alloy_code",
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="alloy",
            name="standard_name",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
