# Generated by Django 5.2.5 on 2025-12-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_alloy_alloy_code_alloy_standard_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alloy",
            name="alloy_code",
        ),
        migrations.RemoveField(
            model_name="alloy",
            name="standard_name",
        ),
    ]
