# Generated by Django 5.1.1 on 2025-12-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_alloy_alloy_code_alloy_standard_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alloy",
            name="alloy_code",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="standard_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
