# Generated by Django 5.1.1 on 2025-12-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_alter_alloy_alloy_code_alter_alloy_standard_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alloy",
            name="al_max",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="al_min",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="bi_max",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="bi_min",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="cr_max",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="cr_min",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="cu_max",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="cu_min",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="fe_max",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="fe_min",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="mg_max",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="mg_min",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="mn_max",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="mn_min",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="others_each_max",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="others_each_min",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="others_total_max",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="others_total_min",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="pb_max",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="pb_min",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="si_max",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="si_min",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="sn_max",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="sn_min",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="ti_max",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="ti_min",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="zn_max",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alloy",
            name="zn_min",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
