# Generated by Django 5.1.1 on 2025-12-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0013_alter_alloy_al_max_alter_alloy_al_min_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temper",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
