# Generated by Django 5.1.1 on 2025-12-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0014_alter_temper_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temper",
            name="name",
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
