# Generated by Django 5.1.1 on 2026-01-06 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0019_make_department_plant_nullable"),
        ("product", "0015_alter_temper_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="temper",
            name="area",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="temper",
            name="dimention_unit",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="temper",
            name="electrical_conductivity_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="temper",
            name="electrical_conductivity_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="temper",
            name="elongation_50mm_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="temper",
            name="elongation_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="temper",
            name="hardness",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="temper",
            name="section_thinkness_over",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="temper",
            name="section_thinkness_upto",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="temper",
            name="section_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.sectiontype",
            ),
        ),
        migrations.AddField(
            model_name="temper",
            name="temper_code_new",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="temper",
            name="temper_code_old",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="temper",
            name="tensile_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="temper",
            name="tensile_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="temper",
            name="yield_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="temper",
            name="yield_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="temper",
            name="yield_unit",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
