# Generated by Django 5.1.1 on 2026-01-06 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0016_temper_area_temper_dimention_unit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="temper",
            name="section_thinkness_over",
        ),
        migrations.RemoveField(
            model_name="temper",
            name="section_thinkness_upto",
        ),
    ]
