# Generated by Django 5.1.1 on 2026-01-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0017_remove_temper_section_thinkness_over_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="temper",
            name="section_thickness_over",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="temper",
            name="section_thickness_upto",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=7, null=True
            ),
        ),
    ]
