# Generated by Django 5.1.1 on 2026-01-08 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0021_merge_0016_remove_item_0020_temper_section_thickness"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="temper",
            name="section_thickness_over",
        ),
        migrations.RemoveField(
            model_name="temper",
            name="section_thickness_upto",
        ),
    ]
