# Generated by Django 5.1.1 on 2026-01-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0022_remove_temper_section_thickness_over_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="temper",
            name="section_thickness_over",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="temper",
            name="section_thickness_upto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
