# Generated by Django 5.1.1 on 2026-01-08 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0023_temper_section_thickness_over_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="temper",
            name="section_thickness_over",
        ),
        migrations.RemoveField(
            model_name="temper",
            name="section_thickness_upto",
        ),
    ]
