# Generated by Django 5.1.1 on 2026-01-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0024_remove_temper_section_thickness_over_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="temper",
            name="section_thickness_over",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="temper",
            name="section_thickness_upto",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
