# Generated by Django 5.1.1 on 2026-01-13 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0026_item"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["item_code"]},
        ),
        migrations.AlterModelTable(
            name="item",
            table="item",
        ),
    ]
