# Generated by Django 5.1.1 on 2026-01-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0028_item_deleted_at_item_deleted_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alloy",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
