# Generated by Django 5.1.1 on 2026-01-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0031_alter_alloy_al_max_alter_alloy_al_min_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="temper",
            name="code",
        ),
    ]
