# Generated by Django 5.1.1 on 2026-01-23 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0032_remove_temper_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="temper",
            name="dimention_unit",
        ),
        migrations.RemoveField(
            model_name="temper",
            name="yield_unit",
        ),
    ]
