# Generated by Django 5.1.1 on 2026-01-23 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0031_yieldunit"),
        ("product", "0033_remove_temper_dimention_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="temper",
            name="dimention_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.uom",
            ),
        ),
        migrations.AddField(
            model_name="temper",
            name="yield_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.yieldunit",
            ),
        ),
    ]
