# Generated by Django 5.1.1 on 2026-01-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0034_temper_dimention_unit_temper_yield_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="temper",
            name="electrical_conductivity_max",
        ),
        migrations.RemoveField(
            model_name="temper",
            name="electrical_conductivity_min",
        ),
        migrations.RemoveField(
            model_name="temper",
            name="elongation_50mm_min",
        ),
        migrations.RemoveField(
            model_name="temper",
            name="elongation_min",
        ),
        migrations.RemoveField(
            model_name="temper",
            name="hardness",
        ),
        migrations.RemoveField(
            model_name="temper",
            name="tensile_max",
        ),
        migrations.RemoveField(
            model_name="temper",
            name="tensile_min",
        ),
        migrations.RemoveField(
            model_name="temper",
            name="yield_max",
        ),
        migrations.RemoveField(
            model_name="temper",
            name="yield_min",
        ),
    ]
