# Generated by Django 5.1.1 on 2026-01-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0035_remove_temper_electrical_conductivity_max_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="temper",
            name="electrical_conductivity_max",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="temper",
            name="electrical_conductivity_min",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="temper",
            name="elongation_50mm_min",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="temper",
            name="elongation_min",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="temper",
            name="hardness",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="temper",
            name="tensile_max",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="temper",
            name="tensile_min",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="temper",
            name="yield_max",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="temper",
            name="yield_min",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
    ]
