# Generated by Django 5.1.1 on 2026-01-30 12:23

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0036_temper_electrical_conductivity_max_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, null=True)),
            ],
            options={
                "db_table": "item_type",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MaterialCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, null=True)),
            ],
            options={
                "db_table": "material_center",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ValuationMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, null=True)),
            ],
            options={
                "db_table": "valuation_method",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="item",
            name="base_unit",
            field=models.CharField(default="KG", max_length=10),
        ),
        migrations.AddField(
            model_name="item",
            name="batch_managed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="item",
            name="bom_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="grn_required",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="item",
            name="gst_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="hsn_code",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="lead_time_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="making_time_minutes",
            field=models.PositiveIntegerField(
                default=0, help_text="Extrusion or manufacturing time per job"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="maximum_stock",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="minimum_stock",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.000"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="net_weight",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.00"),
                help_text="Weight per piece or per batch in KG",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="purchase_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.000"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="reorder_qty",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.000"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="sale_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="item_type_fk",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="item",
                to="product.itemtype",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="material_center",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="item",
                to="product.materialcenter",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="valuation_method",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="item",
                to="product.valuationmethod",
            ),
        ),
    ]
