# Generated by Django 5.1.1 on 2026-01-30 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0037_itemtype_materialcenter_valuationmethod_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="item_type_fk",
        ),
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="item",
                to="product.itemtype",
            ),
        ),
    ]
