# Generated by Django 5.1.1 on 2026-02-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0038_remove_item_item_type_fk_alter_item_item_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                db_index=True,
                default="Active",
                max_length=20,
            ),
        ),
    ]
