# Generated by Django 5.1.1 on 2026-02-03 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0039_item_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="default_uom",
            new_name="uom",
        ),
    ]
