# Generated by Django 5.1.1 on 2026-02-03 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0036_remove_itemcategory_item_catego_is_acti_3edb83_idx_and_more"),
        ("product", "0040_rename_default_uom_item_uom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="uom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uom",
                to="common.uom",
            ),
        ),
    ]
