# Generated by Django 5.1.1 on 2026-02-04 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0042_alter_item_created_at_alter_item_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["-created_at"]},
        ),
    ]
