# Generated by Django 5.1.1 on 2026-02-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0043_alter_item_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temper",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
