# Generated by Django 5.1.1 on 2026-02-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0044_alter_temper_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="temper",
            name="heat_treatment",
            field=models.BooleanField(default=False),
        ),
    ]
