# Generated by Django 5.1.1 on 2026-02-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0045_temper_heat_treatment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temper",
            name="area",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
