# Generated by Django 5.1.1 on 2026-02-11 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0046_alter_temper_area"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="approve",
        ),
        migrations.RemoveField(
            model_name="item",
            name="approve_remarks",
        ),
        migrations.RemoveField(
            model_name="item",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="item",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="item",
            name="done_flag",
        ),
        migrations.RemoveField(
            model_name="item",
            name="f_id",
        ),
        migrations.RemoveField(
            model_name="item",
            name="reject",
        ),
        migrations.AlterField(
            model_name="item",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Item_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Item_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
