# Generated by Django 5.1.1 on 2026-02-11 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0047_remove_item_approve_remove_item_approve_remarks_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="approve",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="approve_remarks",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="approved_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="approved_by",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="done_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="f_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="reject",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="item",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
