# Generated by Django 5.1.1 on 2026-02-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0048_item_approve_item_approve_remarks_item_approved_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="conversion_factor",
        ),
        migrations.RemoveField(
            model_name="item",
            name="secondary_uom",
        ),
    ]
