# Generated by Django 5.1.1 on 2026-02-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0049_remove_item_conversion_factor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temper",
            name="name",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
