# Generated by Django 5.2.4 on 2026-02-13 05:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0041_alter_department_updated_at_nullable"),
        ("product", "0050_alter_temper_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="temper",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False)),
                fields=("name", "temper_code_new", "section_type"),
                name="unique_active_temper_name_code_section",
            ),
        ),
    ]
