# Generated by Django 5.1.1 on 2026-02-24 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0045_rename_grn_status_idx_grn_status_5ca68c_idx_and_more"),
        (
            "product",
            "0054_remove_temper_unique_alloy_section_tempercode_not_null_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="temper",
            name="unique_active_temper_name_code_section",
        ),
        migrations.AddConstraint(
            model_name="temper",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False)),
                fields=(
                    "name",
                    "temper_code_new",
                    "section_type",
                    "alloy",
                    "dimention_unit",
                    "yield_unit",
                ),
                name="unique_active_temper_6_fields",
            ),
        ),
    ]
