# Generated by Django 5.1.1 on 2026-04-15 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "product",
            "0055_remove_temper_unique_active_temper_name_code_section_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="temper",
            old_name="name",
            new_name="description",
        ),
    ]
