# Generated by Django 5.1.1 on 2026-04-17 04:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0047_packingmode_code_packingmode_price_per_kg"),
        ("product", "0056_rename_name_temper_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("year", models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="temper",
            name="unique_active_temper_6_fields",
        ),
        migrations.AddConstraint(
            model_name="temper",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False)),
                fields=(
                    "description",
                    "temper_code_new",
                    "section_type",
                    "alloy",
                    "dimention_unit",
                    "yield_unit",
                ),
                name="unique_active_temper_6_fields",
            ),
        ),
    ]
