# Generated by Django 5.1.1 on 2026-04-17 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0057_standardmaster_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alloy",
            name="standard_name",
        ),
    ]
