# Generated by Django 5.1.1 on 2026-04-17 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0058_remove_alloy_standard_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="alloy",
            name="standard_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.standardmaster",
            ),
        ),
    ]
