# Generated by Django 5.1.1 on 2026-04-17 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0060_temper_standard_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alloy",
            old_name="standard_name",
            new_name="standard",
        ),
        migrations.RenameField(
            model_name="temper",
            old_name="standard_name",
            new_name="standard",
        ),
    ]
