# Generated by Django 5.1.1 on 2026-08-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0061_rename_standard_name_alloy_standard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temper',
            name='hardness',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
