# Generated by Django 5.1.1 on 2026-05-05 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dietool_production", "0003_maintenancetype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diemaintenancelog",
            name="maintenance_type",
        ),
    ]
