# Generated by Django 5.1.1 on 2026-05-05 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dietool_production", "0004_remove_diemaintenancelog_maintenance_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="diemaintenancelog",
            name="maintenance_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_log",
                to="dietool_production.maintenancetype",
            ),
        ),
    ]
