# Generated by Django 5.1.1 on 2026-05-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dietool_production", "0005_diemaintenancelog_maintenance_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="diemaintenancelog",
            name="hardness_after",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="diemaintenancelog",
            name="hardness_before",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
