# Generated by Django 5.1.1 on 2026-05-11 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dietool_production", "0007_correctionhistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="diemaintenancelog",
            name="inspection_done_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenance_inspector",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="diemaintenancelog",
            name="inspection_result",
            field=models.CharField(
                choices=[
                    ("pass", "Pass"),
                    ("fail", "Fail"),
                    ("rework", "Rework Required"),
                    ("deviation", "Accepted with Deviation"),
                    ("hold", "Hold"),
                    ("rejected", "Rejected"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="diemaintenancelog",
            name="inspection_type",
            field=models.CharField(
                choices=[
                    ("visual", "Visual Inspection"),
                    ("dimensional", "Dimensional Inspection"),
                    ("hardness", "Hardness Test"),
                    ("surface", "Surface Finish Check"),
                    ("crack", "Crack Detection"),
                    ("trial", "Trial Run Inspection"),
                    ("final", "Final QC Inspection"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
