# Generated by Django 5.1.1 on 2026-05-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dietool_production", "0008_diemaintenancelog_inspection_done_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diemaintenancelog",
            name="life_added_mt",
        ),
    ]
