# Generated by Django 5.1.1 on 2026-05-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dietool_production", "0009_remove_diemaintenancelog_life_added_mt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="correctionhistory",
            name="correction",
        ),
        migrations.RemoveField(
            model_name="correctionhistory",
            name="issue",
        ),
    ]
