# Generated by Django 5.1.1 on 2026-05-11 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dietool_production", "0010_remove_correctionhistory_correction_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="correctionhistory",
            name="correction_done_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="correction_done_by_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="correctionhistory",
            name="correction_request_no",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="correctionhistory",
            name="die_life_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="correctionhistory",
            name="problem_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="correctionhistory",
            name="reason_for_correction",
            field=models.TextField(blank=True, null=True),
        ),
    ]
