# Generated by Django 5.1.1 on 2026-05-12 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dietool_production", "0011_correctionhistory_correction_done_by_and_more"),
        ("product", "0061_rename_standard_name_alloy_standard_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dietriallog",
            name="alloy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dietriallog_alloy",
                to="product.alloy",
            ),
        ),
        migrations.AddField(
            model_name="dietriallog",
            name="approved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dietriallog_approver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dietriallog",
            name="suggestion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dietriallog",
            name="temper",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dietriallog_temper",
                to="product.temper",
            ),
        ),
        migrations.AddField(
            model_name="dietriallog",
            name="total_kg_extrude",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="dietriallog",
            name="trial_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dietriallog",
            name="trial_no",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="dietriallog",
            name="trial_type",
            field=models.CharField(
                choices=[
                    ("new", "New Die Trial"),
                    ("correction", "Correction Trial"),
                    ("repeat", "Repeat Trial"),
                    ("development", "Development Trial"),
                    ("approval", "Customer Approval Trial"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
