# Generated by Django 5.1.1 on 2026-05-12 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dietool_production",
            "0012_dietriallog_alloy_dietriallog_approved_by_and_more",
        ),
        ("shift", "0002_remove_shiftmaster_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietriallog",
            name="billet_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dietriallog",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_shift",
                to="shift.shiftmaster",
            ),
        ),
        migrations.AddField(
            model_name="dietriallog",
            name="shift_end_snapshot",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dietriallog",
            name="shift_name_snapshot",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="dietriallog",
            name="shift_start_snapshot",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dietriallog",
            name="result",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("not_approved", "Not Approved"),
                    ("deviation", "Approved with Deviation"),
                    ("rework", "Rework Required"),
                    ("hold", "Hold"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
