# Generated by Django 5.1.1 on 2026-05-12 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "dietool_production",
            "0013_dietriallog_billet_size_dietriallog_shift_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="dietriallog",
            old_name="total_kg_extrude",
            new_name="total_extrude_kg",
        ),
    ]
