# Generated by Django 5.1.1 on 2026-05-15 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0112_alter_dietool_unique_together"),
        (
            "dietool_production",
            "0014_rename_total_kg_extrude_dietriallog_total_extrude_kg",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DieFailureLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("failure_date", models.DateField(blank=True, null=True)),
                (
                    "failure_type",
                    models.CharField(
                        choices=[
                            ("breakdown", "Breakdown"),
                            ("crack", "Crack"),
                            ("wear", "Wear"),
                            ("scrap", "Scrap"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("production", "Production"),
                            ("maintenance", "Maintenance"),
                            ("trial", "Trial"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "broken_part",
                    models.CharField(
                        choices=[
                            ("die_plate", "Die Plate"),
                            ("mandrel", "Mandrel"),
                            ("backer", "Backer"),
                            ("bolster", "Bolster"),
                            ("feeder", "Feeder"),
                            ("die_ring", "Die Ring"),
                            ("pocket", "Pocket"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("root_cause", models.TextField(blank=True, null=True)),
                ("action_taken", models.TextField(blank=True, null=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("downtime_hours", models.TimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "die_tool",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failure_log_dietool",
                        to="die.dietool",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "die_failure_log",
                "permissions": [
                    (
                        "download_die_failure_log_excel_copy",
                        "Can download Die Failure Log Excel",
                    ),
                    (
                        "download_die_failure_log_pdf_copy",
                        "Can download Die Failure Log PDF",
                    ),
                ],
            },
        ),
    ]
