# Generated by Django 5.1.1 on 2026-05-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "dietool_production",
            "0016_diefailurelog_shift_diefailurelog_shift_end_snapshot_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diefailurelog",
            name="broken_part",
        ),
    ]
