# Generated by Django 5.1.1 on 2026-05-15 08:50

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dietool_production", "0017_remove_diefailurelog_broken_part"),
    ]

    operations = [
        migrations.AddField(
            model_name="diefailurelog",
            name="broken_part",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("die_plate", "Die Plate"),
                    ("mandrel", "Mandrel"),
                    ("backer", "Backer"),
                    ("bolster", "Bolster"),
                    ("feeder", "Feeder"),
                    ("die_ring", "Die Ring"),
                    ("pocket", "Pocket"),
                ],
                max_length=55,
                null=True,
            ),
        ),
    ]
