# Generated by Django 5.1.1 on 2026-05-18 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dietool_production", "0018_diefailurelog_broken_part"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="correctionhistory",
            options={
                "permissions": [
                    (
                        "download_die_correction_history_excel_copy",
                        "Can download Die Correction History Excel",
                    ),
                    (
                        "download_die_correction_history_pdf_copy",
                        "Can download Die Correction History PDF",
                    ),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="diemaintenancelog",
            options={
                "permissions": [
                    (
                        "download_die_tool_maintenance_excel_copy",
                        "Can download Die Tool maintenance Excel",
                    ),
                    (
                        "download_die_tool_maintenance_pdf_copy",
                        "Can download Die Tool maintenance PDF",
                    ),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="dietriallog",
            options={
                "permissions": [
                    (
                        "download_die_trial_log_excel_copy",
                        "Can download Die Trial log Excel",
                    ),
                    (
                        "download_die_trial_log_pdf_copy",
                        "Can download Die Trial log PDF",
                    ),
                ]
            },
        ),
    ]
