# Generated by Django 5.1.1 on 2026-06-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dietool_production", "0021_correctioninspectiontype_reasonforcorrection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="correctionhistory",
            name="reason_for_correction",
        ),
    ]
