# Generated by Django 5.1.1 on 2026-06-25 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dietool_production", "0022_remove_correctionhistory_reason_for_correction"),
    ]

    operations = [
        migrations.AddField(
            model_name="correctionhistory",
            name="inspection_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="correctionhistory_inspectiontype",
                to="dietool_production.correctioninspectiontype",
            ),
        ),
        migrations.AddField(
            model_name="correctionhistory",
            name="reason_for_correction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="correctionhistory_reason",
                to="dietool_production.reasonforcorrection",
            ),
        ),
    ]
