# Generated by Django 5.1.1 on 2026-06-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dietool_production", "0025_activitymaster"),
    ]

    operations = [
        migrations.AddField(
            model_name="correctionhistory",
            name="activity",
            field=models.ManyToManyField(
                blank=True,
                related_name="correctionhistory_activity",
                to="dietool_production.activitymaster",
            ),
        ),
    ]
