# Generated by Django 5.1.1 on 2026-06-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dietool_production", "0028_alter_dietriallog_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="diefailurelog",
            name="failure_no",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="diefailurelog",
            name="severity",
            field=models.CharField(
                choices=[
                    ("minor", "Minor"),
                    ("major", "Major"),
                    ("critical", "Critical"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="diefailurelog",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
