# Generated by Django 5.1.1 on 2026-07-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dietool_production", "0030_analysismethod_diefailurelog_analysis_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="diemaintenancelog",
            name="die_life_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
