# Generated by Django 5.1.1 on 2026-07-02 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dietool_production", "0032_reasonformaintenance_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="diemaintenancelog",
            name="after_maintenance_done_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="after_maintenance_done_by_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
