# Generated by Django 5.1.1 on 2026-08-18 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietool_production', '0033_diemaintenancelog_after_maintenance_done_by'),
        ('production', '0026_production_completion_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietriallog',
            name='production',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dietriallog_production', to='production.production'),
        ),
    ]
