# Generated by Django 5.1.1 on 2026-08-25 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('die', '0123_dietool_status_alter_dietool_location'),
        ('dietool_production', '0034_dietriallog_production'),
        ('melting_furnace', '0007_alter_recoverystandard_furnace_type'),
        ('shift', '0002_remove_shiftmaster_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DieNitridingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('shift_name_snapshot', models.CharField(blank=True, max_length=50, null=True)),
                ('shift_start_snapshot', models.TimeField(blank=True, null=True)),
                ('shift_end_snapshot', models.TimeField(blank=True, null=True)),
                ('batch_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('nitriding_start_time', models.DateTimeField(blank=True, null=True)),
                ('holding_time', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('blower_start_time', models.DateTimeField(blank=True, null=True)),
                ('nitriding_stop_time', models.DateTimeField(blank=True, null=True)),
                ('total_die_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('nitriding_start_gas_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('nitriding_stop_gas_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('actual_used_ammonia_gas', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('furnace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='die_nitriding_batches', to='melting_furnace.furnace')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nitriding_batches_operator', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_shift', to='shift.shiftmaster')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nitriding_batch',
                'ordering': ['-id'],
                'permissions': [('download_nitriding_batch_excel_copy', 'Can download Nitriding Batch Excel'), ('download_nitriding_batch_pdf_copy', 'Can download Nitriding Batch PDF')],
            },
        ),
        migrations.CreateModel(
            name='DieNitridingBatchDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('die_plate', models.BooleanField(default=False)),
                ('die_mandrel', models.BooleanField(default=False)),
                ('die_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='dietool_production.dienitridingbatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('die_tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nitriding_batch_details', to='die.dietool')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'die_nitriding_batch_detail',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('batch',), name='unique_nitriding_batch')],
            },
        ),
    ]
