# Generated by Django 5.1.1 on 2026-08-26 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('die', '0123_dietool_status_alter_dietool_location'),
        ('dietool_production', '0035_dienitridingbatch_dienitridingbatchdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='dienitridingbatchdetail',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='die_nitriding_batch_details', to='die.die'),
        ),
        migrations.AlterModelTable(
            name='dienitridingbatch',
            table='die_nitriding_batch',
        ),
    ]
