# Generated by Django 5.1.1 on 2026-08-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietool_production', '0036_dienitridingbatchdetail_section_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE dietool_production_dienitridingbatch
                ALTER COLUMN holding_time DROP DEFAULT;

                ALTER TABLE dietool_production_dienitridingbatch
                ALTER COLUMN holding_time TYPE timestamp with time zone
                USING NULL;
            """,
            reverse_sql="""
                ALTER TABLE dietool_production_dienitridingbatch
                ALTER COLUMN holding_time TYPE numeric
                USING NULL;
            """,
        ),
        migrations.AlterField(
            model_name='dienitridingbatch',
            name='holding_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
