# Generated by Django 5.1.1 on 2026-08-26 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietool_production', '0037_alter_dienitridingbatch_holding_time'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dienitridingbatchdetail',
            name='unique_nitriding_batch',
        ),
    ]
