# Generated by Django 5.1.1 on 2025-12-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shift", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shiftmaster",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="shiftmaster",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="shiftmaster",
            name="deleted_by",
        ),
    ]
