# Generated by Django 5.1.1 on 2025-10-30 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transporter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "party_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, null=True
                    ),
                ),
                (
                    "party_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "balance_type",
                    models.CharField(
                        choices=[("credit", "Credit"), ("debit", "Debit")],
                        default="credit",
                        max_length=10,
                    ),
                ),
                ("is_cash_ammount", models.BooleanField(default=False)),
                ("address", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "city",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, null=True
                    ),
                ),
                ("pincode", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "mobile_no_sms",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "mobile_no",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("phone_no", models.CharField(blank=True, max_length=50, null=True)),
                ("email_id", models.EmailField(blank=True, max_length=50, null=True)),
                (
                    "send_sms_type",
                    models.CharField(
                        choices=[
                            ("sms", "Sms"),
                            ("email", "Email"),
                            ("whatsapp", "Whatsapp"),
                        ],
                        default="sms",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transporter_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transporter_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transporter_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "transporter",
            },
        ),
    ]
