# Generated by Django 5.1.1 on 2025-10-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transporter", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transporter",
            old_name="is_cash_ammount",
            new_name="is_cash_amount",
        ),
    ]
