# Generated by Django 5.1.1 on 2025-10-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transporter", "0002_rename_is_cash_ammount_transporter_is_cash_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transporter",
            name="mobile_no",
            field=models.CharField(
                blank=True, db_index=True, max_length=20, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="transporter",
            name="party_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="transporter",
            name="party_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="transporter",
            name="send_sms_type",
            field=models.CharField(
                choices=[("sms", "Sms"), ("email", "Email"), ("whatsapp", "Whatsapp")],
                default="sms",
                max_length=20,
                unique=True,
            ),
        ),
    ]
