# Generated by Django 5.1.1 on 2025-11-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transporter", "0003_alter_transporter_mobile_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transporter",
            name="send_sms_type",
            field=models.CharField(
                choices=[("sms", "Sms"), ("email", "Email"), ("whatsapp", "Whatsapp")],
                default="sms",
                max_length=20,
            ),
        ),
    ]
