# Generated by Django 5.1.1 on 2025-11-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transporter", "0004_alter_transporter_send_sms_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transporter",
            name="is_active",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="inactive",
                max_length=20,
            ),
        ),
    ]
