# Generated by Django 5.1.1 on 2025-11-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transporter", "0005_alter_transporter_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transporter",
            name="opening_balance",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=20, null=True
            ),
        ),
    ]
