# Generated by Django 4.2.8 on 2026-01-07 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transporter", "0006_alter_transporter_opening_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transporter",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transporter",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="transporter",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transporter",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="transporter",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="transporter",
            index=models.Index(
                fields=["deleted", "is_active"], name="transporter_deleted_b33c9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transporter",
            index=models.Index(
                fields=["deleted", "-id"], name="transporter_deleted_b8c265_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transporter",
            index=models.Index(
                fields=["deleted", "created_at"], name="transporter_deleted_ea791c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transporter",
            index=models.Index(
                fields=["deleted", "updated_at"], name="transporter_deleted_57a6b9_idx"
            ),
        ),
    ]
