# Generated by Django 5.1.1 on 2026-01-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transporter", "0007_alter_transporter_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transporter",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
