# Generated by Django 5.1.1 on 2026-03-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transporter", "0008_alter_transporter_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transporter",
            name="opening_balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
