# Generated by Django 5.1.1 on 2026-03-10 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transporter", "0009_alter_transporter_opening_balance"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transporter",
            options={
                "permissions": [
                    ("download_transpoter_excel_copy", "Can download transpoter Excel"),
                    ("download_transpoter_pdf_copy", "Can download transpoter PDF"),
                ]
            },
        ),
    ]
