# Generated by Django 5.1.1 on 2026-03-10 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transporter", "0010_alter_transporter_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transporter",
            options={
                "permissions": [
                    (
                        "download_transporter_excel_copy",
                        "Can download transporter Excel",
                    ),
                    ("download_transporter_pdf_copy", "Can download transporter PDF"),
                ]
            },
        ),
    ]
