# Generated by Django 5.1.1 on 2025-10-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialyearmodel",
            name="current",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="financialyearmodel",
            name="default",
            field=models.BooleanField(default=False),
        ),
    ]
