# Generated by Django 5.1.1 on 2025-10-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_financialyearmodel_current_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackingMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "packing_mode",
            },
        ),
    ]
