# Generated by Django 5.1.1 on 2025-12-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_packingmode_created_at_packingmode_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packingmode",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
