# Generated by Django 5.1.1 on 2025-12-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_plant"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="plant",
            new_name="plant_plant_c_4ddeb9_idx",
            old_name="plant_plant_code_idx",
        ),
        migrations.RenameIndex(
            model_name="plant",
            new_name="plant_status_e4c1ec_idx",
            old_name="plant_status_idx",
        ),
        migrations.RenameIndex(
            model_name="plant",
            new_name="plant_city_b5a495_idx",
            old_name="plant_city_idx",
        ),
        migrations.RenameIndex(
            model_name="plant",
            new_name="plant_deleted_fab9ee_idx",
            old_name="plant_deleted_status_idx",
        ),
    ]
