# Generated by Django 5.1.1 on 2025-12-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0010_default_plant_capabilities"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="plantcapability",
            new_name="plant_capab_code_07adf3_idx",
            old_name="plant_capability_code_idx",
        ),
        migrations.RenameIndex(
            model_name="plantcapability",
            new_name="plant_capab_status_51cc53_idx",
            old_name="plant_capability_status_idx",
        ),
        migrations.RenameIndex(
            model_name="plantcapability",
            new_name="plant_capab_is_dele_d042cc_idx",
            old_name="plant_capability_deleted_status_idx",
        ),
        migrations.RenameIndex(
            model_name="planttype",
            new_name="plant_type_code_1f01ed_idx",
            old_name="plant_type_code_idx",
        ),
        migrations.RenameIndex(
            model_name="planttype",
            new_name="plant_type_status_985461_idx",
            old_name="plant_type_status_idx",
        ),
        migrations.RenameIndex(
            model_name="planttype",
            new_name="plant_type_is_dele_964834_idx",
            old_name="plant_type_deleted_status_idx",
        ),
        migrations.RenameIndex(
            model_name="planttypecapability",
            new_name="plant_type__plant_t_312941_idx",
            old_name="plant_type_capability_type_cap_idx",
        ),
        migrations.RenameIndex(
            model_name="planttypecapability",
            new_name="plant_type__status_1517a6_idx",
            old_name="plant_type_capability_status_idx",
        ),
        migrations.RenameIndex(
            model_name="planttypecapability",
            new_name="plant_type__is_dele_3c9781_idx",
            old_name="plant_type_capability_deleted_status_idx",
        ),
    ]
