# Generated by Django 5.1.1 on 2025-12-31 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_alter_packingmode_name"),
        (
            "common",
            "0011_rename_plant_capability_code_idx_plant_capab_code_07adf3_idx_and_more",
        ),
    ]

    operations = []
