# Generated by Django 5.1.1 on 2026-01-02 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0012_merge_20251231_1655"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="plantcapability",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plantcapability_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="plantcapability",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plantcapability_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="planttype",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="planttype_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="planttype",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="planttype_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="plantcapability",
            index=models.Index(
                fields=["created_by"], name="plant_capab_created_e60361_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plantcapability",
            index=models.Index(
                fields=["updated_by"], name="plant_capab_updated_77c7da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plantcapability",
            index=models.Index(
                fields=["created_at"], name="plant_capab_created_8658d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planttype",
            index=models.Index(
                fields=["created_by"], name="plant_type_created_2b2b8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planttype",
            index=models.Index(
                fields=["updated_by"], name="plant_type_updated_418c1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planttype",
            index=models.Index(
                fields=["created_at"], name="plant_type_created_f4da83_idx"
            ),
        ),
    ]
