# Generated by Django 5.1.1 on 2026-01-02 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0013_plantcapability_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="planttypecapability",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="planttypecapability",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plant_type_capability_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="planttypecapability",
            index=models.Index(
                fields=["created_by"], name="plant_type__created_add56d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planttypecapability",
            index=models.Index(
                fields=["updated_by"], name="plant_type__updated_b9a7fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planttypecapability",
            index=models.Index(
                fields=["created_at"], name="plant_type__created_3ecc62_idx"
            ),
        ),
    ]
