# Generated by Django 5.1.1 on 2026-01-02 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0014_planttypecapability_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="plant",
            index=models.Index(fields=["created_by"], name="plant_created_dea005_idx"),
        ),
        migrations.AddIndex(
            model_name="plant",
            index=models.Index(fields=["updated_by"], name="plant_updated_c0b7c0_idx"),
        ),
        migrations.AddIndex(
            model_name="plant",
            index=models.Index(fields=["created_at"], name="plant_created_ea748b_idx"),
        ),
    ]
