# Generated by Django 5.1.1 on 2026-01-05 09:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0016_change_plant_head_to_foreignkey"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Section type name (e.g., Production, Quality, Maintenance)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Section Type",
                "verbose_name_plural": "Section Types",
                "db_table": "section_type",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveIndex(
            model_name="plant",
            name="plant_plant_head_idx",
        ),
        migrations.AddField(
            model_name="sectiontype",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sectiontype_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sectiontype",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sectiontype_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="sectiontype",
            index=models.Index(fields=["name"], name="section_typ_name_1998a1_idx"),
        ),
        migrations.AddIndex(
            model_name="sectiontype",
            index=models.Index(
                fields=["is_active"], name="section_typ_is_acti_e9e64f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sectiontype",
            index=models.Index(
                fields=["is_archived", "is_active"],
                name="section_typ_is_arch_3c08d0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sectiontype",
            index=models.Index(
                fields=["created_by"], name="section_typ_created_af367f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sectiontype",
            index=models.Index(
                fields=["updated_by"], name="section_typ_updated_80c67a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sectiontype",
            index=models.Index(
                fields=["created_at"], name="section_typ_created_34abba_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sectiontype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("name",),
                name="unique_active_section_type_name",
            ),
        ),
    ]
