# Generated by Django 5.1.1 on 2026-01-05 10:41

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0017_sectiontype_remove_plant_plant_plant_head_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "department_code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique department code",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("department_name", models.CharField(db_index=True, max_length=255)),
                (
                    "department_type",
                    models.CharField(
                        choices=[
                            ("PRODUCTION", "Production"),
                            ("STORE", "Store"),
                            ("QA", "Quality Assurance"),
                            ("PURCHASE", "Purchase"),
                            ("MAINTENANCE", "Maintenance"),
                            ("FINANCE", "Finance"),
                            ("ADMIN", "Administration"),
                        ],
                        db_index=True,
                        help_text="Type of department",
                        max_length=20,
                    ),
                ),
                (
                    "cost_center_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        db_index=True,
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="department_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent department for hierarchical structure",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_departments",
                        to="common.department",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        help_text="Plant this department belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departments",
                        to="common.plant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="department_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "department",
                "ordering": ["department_code"],
                "indexes": [
                    models.Index(
                        fields=["department_code"], name="department_departm_3ebb1f_idx"
                    ),
                    models.Index(
                        fields=["department_name"], name="department_departm_6f0352_idx"
                    ),
                    models.Index(
                        fields=["department_type"], name="department_departm_622d91_idx"
                    ),
                    models.Index(
                        fields=["status"], name="department_status_daa645_idx"
                    ),
                    models.Index(
                        fields=["is_archived", "status"],
                        name="department_is_arch_6e62d8_idx",
                    ),
                    models.Index(
                        fields=["plant"], name="department_plant_i_6bfb93_idx"
                    ),
                    models.Index(
                        fields=["parent_department"],
                        name="department_parent__437586_idx",
                    ),
                    models.Index(
                        fields=["cost_center_code"],
                        name="department_cost_ce_31a78e_idx",
                    ),
                    models.Index(
                        fields=["created_by"], name="department_created_a22af5_idx"
                    ),
                    models.Index(
                        fields=["updated_by"], name="department_updated_81e737_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="department_created_919db1_idx"
                    ),
                    models.Index(
                        fields=["plant", "is_archived", "status"],
                        name="department_plant_i_0d596a_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_archived", False)),
                        fields=("department_code",),
                        name="unique_active_department_code",
                    )
                ],
            },
        ),
    ]
