# Generated by Django 5.1.1 on 2026-01-07 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0020_itemcategory"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="itemcategory",
            new_name="item_catego_categor_94f56e_idx",
            old_name="item_categor_categor_idx",
        ),
        migrations.RenameIndex(
            model_name="itemcategory",
            new_name="item_catego_categor_baf6fb_idx",
            old_name="item_categor_categor_name_idx",
        ),
        migrations.RenameIndex(
            model_name="itemcategory",
            new_name="item_catego_allowed_5a530f_idx",
            old_name="item_categor_allowed_idx",
        ),
        migrations.RenameIndex(
            model_name="itemcategory",
            new_name="item_catego_is_acti_3edb83_idx",
            old_name="item_categor_is_acti_idx",
        ),
        migrations.RenameIndex(
            model_name="itemcategory",
            new_name="item_catego_is_arch_32c414_idx",
            old_name="item_categor_is_arch_idx",
        ),
        migrations.RenameIndex(
            model_name="itemcategory",
            new_name="item_catego_created_e0304c_idx",
            old_name="item_categor_created_idx",
        ),
        migrations.RenameIndex(
            model_name="itemcategory",
            new_name="item_catego_updated_309089_idx",
            old_name="item_categor_updated_idx",
        ),
        migrations.RenameIndex(
            model_name="itemcategory",
            new_name="item_catego_created_ed1a0e_idx",
            old_name="item_categor_created_at_idx",
        ),
        migrations.RenameIndex(
            model_name="itemcategory",
            new_name="item_catego_allowed_425e7c_idx",
            old_name="item_categor_allowed_type_idx",
        ),
    ]
