# Generated by Django 5.1.1 on 2026-01-12 04:53

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0022_alter_packingmode_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UOM",
            fields=[
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "uom_code",
                    models.CharField(
                        help_text="Examples: KG, MT, PCS", max_length=10, unique=True
                    ),
                ),
                ("uom_name", models.CharField(max_length=50)),
                (
                    "uom_type",
                    models.CharField(
                        choices=[
                            ("WEIGHT", "Weight"),
                            ("LENGTH", "Length"),
                            ("COUNT", "Count"),
                        ],
                        max_length=10,
                    ),
                ),
                ("decimal_allowed", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "uom",
                "ordering": ["uom_code"],
            },
        ),
    ]
