# Generated by Django 5.1.1 on 2026-01-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0024_uom_deleted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="uom",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
