# Generated by Django 5.1.1 on 2026-01-19 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0026_planttype_deleted_planttype_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plantcapability",
            options={
                "ordering": ["code"],
                "permissions": [
                    ("download_plant_type_pdf_copy", "Can download plant type PDF"),
                    ("download_plant_type_excel_copy", "Can download plant type Excel"),
                ],
                "verbose_name": "Plant Capability",
                "verbose_name_plural": "Plant Capabilities",
            },
        ),
    ]
