# Generated by Django 5.1.1 on 2026-01-19 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0027_alter_plantcapability_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["department_code"],
                "permissions": [
                    ("download_department_pdf_copy", "Can download department PDF"),
                    ("download_department_excel_copy", "Can download department Excel"),
                ],
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
    ]
