# Generated by Django 5.1.1 on 2026-01-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0028_alter_department_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemcategory",
            options={
                "ordering": ["category_code"],
                "permissions": [
                    (
                        "download_item_category_pdf_copy",
                        "Can download item category PDF",
                    ),
                    (
                        "download_item_category_excel_copy",
                        "Can download item category Excel",
                    ),
                ],
                "verbose_name": "Item Category",
                "verbose_name_plural": "Item Categories",
            },
        ),
    ]
