# Generated by Django 5.1.1 on 2026-01-19 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0029_alter_itemcategory_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="packingmode",
            options={
                "permissions": [
                    ("download_packing_mode_pdf_copy", "Can download packing_mode PDF"),
                    (
                        "download_packing_mode_excel_copy",
                        "Can download packing_mode Excel",
                    ),
                ]
            },
        ),
    ]
