# Generated by Django 5.1.1 on 2026-01-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0031_yieldunit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packingmode",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="yieldunit",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
