# Generated by Django 5.1.1 on 2026-01-23 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0032_alter_packingmode_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="yieldunit",
            options={},
        ),
    ]
