# Generated by Django 5.1.1 on 2026-01-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0034_remove_plant_plant_created_dea005_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcategory",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                db_index=True,
                default="Active",
                max_length=20,
            ),
        ),
    ]
