# Generated by Django 5.1.1 on 2026-01-28 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0035_itemcategory_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="itemcategory",
            name="item_catego_is_acti_3edb83_idx",
        ),
        migrations.RemoveIndex(
            model_name="itemcategory",
            name="item_catego_is_arch_32c414_idx",
        ),
        migrations.RemoveIndex(
            model_name="itemcategory",
            name="item_catego_allowed_425e7c_idx",
        ),
        migrations.RemoveField(
            model_name="itemcategory",
            name="is_active",
        ),
        migrations.AddIndex(
            model_name="itemcategory",
            index=models.Index(
                fields=["is_archived"], name="item_catego_is_arch_81e8c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemcategory",
            index=models.Index(
                fields=["allowed_item_type", "is_archived"],
                name="item_catego_allowed_94bbcc_idx",
            ),
        ),
    ]
