# Generated by Django 5.1.1 on 2026-02-04 07:11

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0036_remove_itemcategory_item_catego_is_acti_3edb83_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 9, 16, 952160, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="country",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 9, 19, 451915, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="currency",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 9, 21, 469626, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="currency",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 9, 23, 524316, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="financialyearmodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 9, 26, 56383, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="financialyearmodel",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 9, 28, 2989, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gsttype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 9, 29, 894796, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gsttype",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 9, 31, 799823, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="packingtype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 9, 34, 381529, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="packingtype",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 9, 37, 512224, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="uom",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 9, 39, 322121, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="uom",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 10, 38, 142351, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
