# Generated by Django 5.1.1 on 2026-02-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0039_storetype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="currency",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="financialyearmodel",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gsttype",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="packingtype",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uom",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
