# Generated by Django 5.2.4 on 2026-02-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0040_alter_country_updated_at_alter_currency_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
