# Generated by Django 5.2.4

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0041_alter_department_updated_at_nullable"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PackingType",
        ),
    ]
