# Generated by Django 5.2.4

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0042_delete_packingtype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50)),
                ("name", models.CharField(max_length=255)),
                (
                    "process_stage",
                    models.CharField(
                        choices=[
                            ("GRN", "GRN"),
                            ("PRODUCTION", "Production"),
                            ("DISPATCH", "Dispatch"),
                            ("STOCK", "Stock"),
                            ("RETURN", "Return"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("requires_sampling", models.BooleanField(default=False)),
                ("requires_lab_test", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspection_types",
                        to="common.plant",
                        db_index=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspectiontype_created",
                        to=settings.AUTH_USER_MODEL,
                        db_index=True,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspectiontype_updated",
                        to=settings.AUTH_USER_MODEL,
                        db_index=True,
                    ),
                ),
            ],
            options={
                "db_table": "inspection_type",
                "ordering": ["code"],
                "verbose_name": "Inspection Type",
                "verbose_name_plural": "Inspection Types",
                "indexes": [
                    models.Index(fields=["code"], name="inspection_t_code_8a1f2b_idx"),
                    models.Index(
                        fields=["plant_id"], name="inspection_t_plant_i_9c3e4d_idx"
                    ),
                    models.Index(
                        fields=["process_stage"],
                        name="inspection_t_process__7b2a1e_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="inspection_t_is_acti_5d8f3c_idx"
                    ),
                    models.Index(
                        fields=["is_archived", "is_active"],
                        name="inspection_t_is_arch_4e9b2a_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_archived", False)),
                        fields=("code",),
                        name="unique_active_inspection_type_code",
                    ),
                ],
            },
        ),
    ]
