# Generated by Django 5.2.4

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0043_inspection_type_master"),
        ("product", "0026_item"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GRN",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("grn_no", models.CharField(db_index=True, max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("POSTED", "Posted")],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("grn_date", models.DateField(db_index=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "plant",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grns",
                        to="common.plant",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grn_created",
                        to=settings.AUTH_USER_MODEL,
                        db_index=True,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grn_updated",
                        to=settings.AUTH_USER_MODEL,
                        db_index=True,
                    ),
                ),
            ],
            options={
                "db_table": "grn",
                "ordering": ["-grn_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GRNItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "received_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        max_digits=14,
                    ),
                ),
                (
                    "qa_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("PARTIAL", "Partial"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("is_posted", models.BooleanField(db_index=True, default=False)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "grn",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="common.grn",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grn_items",
                        to="product.item",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grn_items",
                        to="common.uom",
                    ),
                ),
            ],
            options={
                "db_table": "grn_item",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="QualityInspection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("inspection_date", models.DateField(auto_now_add=True, db_index=True)),
                (
                    "inspection_status",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Accepted"),
                            ("PARTIAL", "Partial"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "received_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        max_digits=14,
                    ),
                ),
                (
                    "accepted_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        max_digits=14,
                    ),
                ),
                (
                    "rejected_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        max_digits=14,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "grn_item",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_inspections",
                        to="common.grnitem",
                    ),
                ),
                (
                    "inspection_type",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_inspections",
                        to="common.inspectiontype",
                    ),
                ),
                (
                    "inspected_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_inspections_performed",
                        to=settings.AUTH_USER_MODEL,
                        db_index=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_inspection_created",
                        to=settings.AUTH_USER_MODEL,
                        db_index=True,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_inspection_updated",
                        to=settings.AUTH_USER_MODEL,
                        db_index=True,
                    ),
                ),
            ],
            options={
                "db_table": "quality_inspection",
                "ordering": ["-inspection_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="grn",
            index=models.Index(fields=["status"], name="grn_status_idx"),
        ),
        migrations.AddIndex(
            model_name="grn",
            index=models.Index(fields=["plant"], name="grn_plant_idx"),
        ),
        migrations.AddIndex(
            model_name="grnitem",
            index=models.Index(fields=["grn", "qa_status"], name="grn_item_grn_qa_idx"),
        ),
        migrations.AddIndex(
            model_name="grnitem",
            index=models.Index(fields=["qa_status"], name="grn_item_qa_idx"),
        ),
        migrations.AddIndex(
            model_name="qualityinspection",
            index=models.Index(fields=["grn_item_id"], name="quality_ins_grn_item_idx"),
        ),
        migrations.AddIndex(
            model_name="qualityinspection",
            index=models.Index(
                fields=["inspection_status"], name="quality_ins_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qualityinspection",
            index=models.Index(
                fields=["inspection_type_id"], name="quality_ins_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qualityinspection",
            index=models.Index(fields=["inspection_date"], name="quality_ins_date_idx"),
        ),
        migrations.AddIndex(
            model_name="qualityinspection",
            index=models.Index(
                fields=["is_archived", "is_active"],
                name="quality_ins_arch_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="qualityinspection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("grn_item",),
                name="unique_qa_per_grn_item",
            ),
        ),
    ]
