# Generated by Django 5.1.1 on 2026-02-23 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0044_quality_inspection_grn"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="grn",
            new_name="grn_status_5ca68c_idx",
            old_name="grn_status_idx",
        ),
        migrations.RenameIndex(
            model_name="grn",
            new_name="grn_plant_i_358cea_idx",
            old_name="grn_plant_idx",
        ),
        migrations.RenameIndex(
            model_name="grnitem",
            new_name="grn_item_grn_id_6590d4_idx",
            old_name="grn_item_grn_qa_idx",
        ),
        migrations.RenameIndex(
            model_name="grnitem",
            new_name="grn_item_qa_stat_aa07b7_idx",
            old_name="grn_item_qa_idx",
        ),
        migrations.RenameIndex(
            model_name="inspectiontype",
            new_name="inspection__code_05abe6_idx",
            old_name="inspection_t_code_8a1f2b_idx",
        ),
        migrations.RenameIndex(
            model_name="inspectiontype",
            new_name="inspection__plant_i_2fa38b_idx",
            old_name="inspection_t_plant_i_9c3e4d_idx",
        ),
        migrations.RenameIndex(
            model_name="inspectiontype",
            new_name="inspection__process_cbb721_idx",
            old_name="inspection_t_process__7b2a1e_idx",
        ),
        migrations.RenameIndex(
            model_name="inspectiontype",
            new_name="inspection__is_acti_f91d79_idx",
            old_name="inspection_t_is_acti_5d8f3c_idx",
        ),
        migrations.RenameIndex(
            model_name="inspectiontype",
            new_name="inspection__is_arch_8b1bc5_idx",
            old_name="inspection_t_is_arch_4e9b2a_idx",
        ),
        migrations.RenameIndex(
            model_name="qualityinspection",
            new_name="quality_ins_grn_ite_a917fe_idx",
            old_name="quality_ins_grn_item_idx",
        ),
        migrations.RenameIndex(
            model_name="qualityinspection",
            new_name="quality_ins_inspect_e50262_idx",
            old_name="quality_ins_status_idx",
        ),
        migrations.RenameIndex(
            model_name="qualityinspection",
            new_name="quality_ins_inspect_5c55ac_idx",
            old_name="quality_ins_type_idx",
        ),
        migrations.RenameIndex(
            model_name="qualityinspection",
            new_name="quality_ins_inspect_78bdde_idx",
            old_name="quality_ins_date_idx",
        ),
        migrations.RenameIndex(
            model_name="qualityinspection",
            new_name="quality_ins_is_arch_b8ea9b_idx",
            old_name="quality_ins_arch_idx",
        ),
    ]
