# Generated by Django 5.1.1 on 2026-03-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0046_grn_gate_entry_invoice_no_grnitem_batch_heat"),
    ]

    operations = [
        migrations.AddField(
            model_name="packingmode",
            name="code",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="packingmode",
            name="price_per_kg",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
