# Generated by Django 5.1.1 on 2026-06-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0047_packingmode_code_packingmode_price_per_kg"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectiontype",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
