# Generated by Django 5.1.1 on 2026-06-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0049_alter_uom_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uom",
            name="uom_code",
        ),
    ]
