# Generated by Django 5.1.1 on 2026-07-30 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0050_remove_uom_uom_code"),
        ("gate_entry", "0007_remove_gateentry_gate_entry_is_conv_b128cf_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grnitem",
            name="grn",
        ),
        migrations.RemoveField(
            model_name="grnitem",
            name="item",
        ),
        migrations.RemoveField(
            model_name="grnitem",
            name="uom",
        ),
        migrations.RemoveField(
            model_name="qualityinspection",
            name="grn_item",
        ),
        migrations.RemoveField(
            model_name="inspectiontype",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="inspectiontype",
            name="plant",
        ),
        migrations.RemoveField(
            model_name="inspectiontype",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="qualityinspection",
            name="inspection_type",
        ),
        migrations.RemoveField(
            model_name="qualityinspection",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="qualityinspection",
            name="inspected_by",
        ),
        migrations.RemoveField(
            model_name="qualityinspection",
            name="updated_by",
        ),
        migrations.DeleteModel(
            name="GRN",
        ),
        migrations.DeleteModel(
            name="GRNItem",
        ),
        migrations.DeleteModel(
            name="InspectionType",
        ),
        migrations.DeleteModel(
            name="QualityInspection",
        ),
    ]
