# Generated by Django 5.1.1 on 2026-06-03 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FurnaceMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "furnace_code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "furnace_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "furnace_type",
                    models.CharField(
                        choices=[
                            ("CRUCIBLE", "Crucible"),
                            ("CRUCIBLE_FURNACE", "Crucible Furnace"),
                            ("ELECTRIC", "Electric"),
                            ("ELECTRIC_ARC_FURNACE", "Electric Arc Furnace"),
                            ("GAS", "Gas"),
                            ("GAS_FURNACE", "Gas Furnace"),
                            ("HOLDING", "Holding"),
                            ("INDUCTION", "Induction"),
                            ("INDUCTION_FURNACE", "Induction Furnace"),
                            ("OIL_FURNACE", "Oil Furnace"),
                            ("REVERBERATORY", "Reverberatory"),
                            ("REVERBERATORY_FURNACE", "Reverberatory Furnace"),
                            ("ROTARY", "Rotary"),
                            ("TILTING", "Tilting"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "capacity_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Capacity (KG)",
                    ),
                ),
                (
                    "min_temp_celsius",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Min Temp (°C)",
                    ),
                ),
                (
                    "max_temp_celsius",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Max Temp (°C)",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("COAL", "Coal"),
                            ("DIESEL", "Diesel"),
                            ("ELECTRICITY", "Electricity"),
                            ("HEAVY_FUEL_OIL", "Heavy Fuel Oil"),
                            ("LPG", "LPG"),
                            ("NATURAL_GAS", "Natural Gas"),
                            ("PROPANE", "Propane"),
                        ],
                        max_length=50,
                    ),
                ),
                ("remarks", models.TextField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    (
                        "download_furnace_Master_excel_copy",
                        "Can download furnace master Excel",
                    ),
                    (
                        "download_furnace_Master_pdf_copy",
                        "Can download furnace master PDF",
                    ),
                ],
            },
        ),
    ]
