# Generated by Django 5.1.1 on 2026-07-28 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("furnace_master", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="furnacemaster",
            old_name="furnace_code",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="furnacemaster",
            old_name="furnace_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="furnacemaster",
            old_name="furnace_type",
            new_name="type",
        ),
    ]
