# Generated by Django 5.1.1 on 2026-07-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furnace_master", "0002_rename_furnace_code_furnacemaster_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="furnacemaster",
            name="max_temp_celsius",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Max Temp (°C)",
            ),
        ),
        migrations.AlterField(
            model_name="furnacemaster",
            name="min_temp_celsius",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Min Temp (°C)",
            ),
        ),
    ]
