# Generated by Django 5.1.1 on 2026-02-13 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("die", "0052_alter_conversionrate_conversion"),
        ("shift", "0002_remove_shiftmaster_deleted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "shift_name_snapshot",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("shift_start_snapshot", models.TimeField(blank=True, null=True)),
                ("shift_end_snapshot", models.TimeField(blank=True, null=True)),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Draft", "Draft"), ("Submitted", "Submitted")],
                        default="Draft",
                        max_length=10,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "press",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shiftlog_press",
                        to="die.diepress",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_shift",
                        to="shift.shiftmaster",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shiftlog_supervisor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShiftIdleLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("MAINT", "Maintenance"),
                            ("OPERATION", "Operation"),
                            ("SHUTDOWN", "Shutdown"),
                        ],
                        max_length=20,
                    ),
                ),
                ("from_time", models.TimeField()),
                ("to_time", models.TimeField()),
                ("minutes", models.PositiveIntegerField()),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "shift_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idle_logs",
                        to="shift_logs.shiftlog",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShiftUsedLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alloy", models.CharField(blank=True, max_length=100, null=True)),
                ("log_qty", models.FloatField()),
                (
                    "shift_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_logs",
                        to="shift_logs.shiftlog",
                    ),
                ),
            ],
        ),
    ]
