# Generated by Django 5.1.1 on 2026-02-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shift_logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftidlelog",
            name="type",
            field=models.CharField(
                choices=[
                    ("Maintenance", "Maintenance"),
                    ("Operation", "Operation"),
                    ("Shutdown", "Shutdown"),
                ],
                max_length=20,
            ),
        ),
    ]
