# Generated by Django 5.1.1 on 2026-08-03 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shift_logs", "0002_alter_shiftidlelog_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shiftusedlog",
            name="shift_log",
        ),
        migrations.DeleteModel(
            name="ShiftIdleLog",
        ),
        migrations.DeleteModel(
            name="ShiftUsedLog",
        ),
    ]
