"""
Django settings for alux_erp project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import timedelta
from os import path
from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

allowed_host_str = config("ALLOWED_HOSTS", default="")
ALLOWED_HOSTS = ["*"]


cors_allowed_origins_str = config("CORS_ALLOWED_ORIGINS", default="")
CORS_ALLOWED_ORIGINS = [
    origin.strip() for origin in cors_allowed_origins_str.split(",")
]
CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in cors_allowed_origins_str.split(",")
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "django_extensions",
    "django_filters",
    "user",
    "common",
    "msg_logger",
    "die",
    "party",
    "product",
    "production",
    "quotation",
    "workorder",
    "core",
    "bloster",
    "vendor",
    "customer",
    "nalco",
    "die_quotation",
    "proforma",
    "bundle_inward",
    "bundle_outward",
    "planning",
    "aging",
    "ageing_cycle",
    "warehouse",
    "bundle_verification",
    "inquiry",
    "inquiry_quotation",
    "inquiry_salesorder",
    "transporter",
    "vehicle_type",
    "vehicle_master",
    "material",
    "bulk_import",
    "first_weight_entry",
    "second_weight_entry",
    "manual_weight_entry",
    "die_requisition",
    "shift",
    "settings",
    "imports",
    "store",
    "melting_furnace",
    "shift_logs",
    "gate_pass",
    "gate_entry",
    "scrap_sale",
    "scrap_entry",
    "scrap_transfer",
    "scrap_generation_remelt",
    "online_inspection",
    "dimension_inspection",
    "mechanical_test",
    "test_certificate",
    "dietool_production",
    "material_indent",
    "material_request",
    "silk",
    "purchase_order",
    "import_export",
    "simple_history",
    "axes",
    "receipt_notes",
    "furnace_master",
    "quality_inspection",
    "return_to_vendor",
    "recovery_standard_master",
    "furnace_charge_plan",
    "create_dross_entry",
    "die_proforma"
]

BLACKLIST_APP_NAME = "rest_framework_simplejwt.token_blacklist"

MIDDLEWARE = [
    "silk.middleware.SilkyMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "axes.middleware.AxesMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.gzip.GZipMiddleware",
    "utils.api_performance_middleware.APIPerformanceMiddleware",  # API performance monitoring
]

ROOT_URLCONF = "alux_erp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "alux_erp.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

MEDIA_ROOT = path.join(BASE_DIR, "media/")
MEDIA_URL = "/media/"

# Base URL for generating full absolute URLs (e.g., for API responses)
# Example: https://devservices.aluxerp.com
BASE_URL = config("APP_URL", default="http://localhost:8000")

STATIC_DIR = path.join(BASE_DIR, "static")

STATIC_URL = "staticfiles/"
STATICFILES_DIRS = [STATIC_DIR]
STATIC_ROOT = path.join(BASE_DIR, "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly"
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
}

AUTH_USER_MODEL = "user.User"

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=360),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=5),
    "ALGORITHM": "HS256",
    "BLACKLIST_AFTER_ROTATION": True,
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
}

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {"format": "%(levelname)s %(message)s"},
        "verbose": {
            "format": "[%(asctime)s] %(levelname)s [%(filename)s:%(lineno)s] %(message)s",
            "datefmt": "%Y/%b/%d %H:%M:%S",
        },
    },
    "handlers": {
        "file": {
            "level": "DEBUG",  # Capture DEBUG logs as well
            "class": "logging.handlers.RotatingFileHandler",
            "filename": config("LOG_FILE_LOCATION"),
            "maxBytes": 1024 * 1024 * 200,  # 200 mb
            "backupCount": 10,
            "formatter": "verbose",
            "encoding": "utf8",
        },
        # 'db': {
        #     'level': 'INFO',
        #     'class': 'logging.handlers.DBLoggerHandler',
        #     'model': 'msg_logger.LogActivity',  # or your custom model
        # },
    },
    "loggers": {
        "file_logger": {  # Use a more specific logger name
            "handlers": ["file"],
            "level": "DEBUG",  # Capture DEBUG logs as well
            "propagate": True,  # Allow log records to propagate to parent handlers
        },
        # 'db_logger': {
        #     'handlers': ['db'],
        #     'level': 'CRITICAL',
        #     'propagate': False
        # },
    },
}

# Cache Configuration
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
        "OPTIONS": {
            "MAX_ENTRIES": 1000,
        },
        "TIMEOUT": 300,
    }
}

AXES_ENABLED = True
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_PARAMETERS = ["username", "ip_address"]

CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", default="redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 3600          
CELERY_TASK_SOFT_TIME_LIMIT = 3300     
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  
CELERY_TASK_ACKS_LATE = True           
CELERY_WORKER_POOL = "solo"            
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

