# Generated by Django 5.1.1 on 2026-03-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dimension_inspection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dimensioninspection",
            name="head_end_scrap_mm",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="dimensioninspection",
            name="tail_end_scrap_mm",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
