# Generated by Django 5.1.1 on 2026-03-11 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0079_rename_no_of_regrinds_dietool_regrinds"),
        ("dimension_inspection", "0002_dimensioninspection_head_end_scrap_mm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dimensioninspection",
            name="container_temp",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="dimensioninspection",
            name="cut_length",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dimensioninspection",
            name="die_no",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="die_no_dimension_inspection",
                to="die.dietool",
            ),
        ),
        migrations.AddField(
            model_name="dimensioninspection",
            name="quenching_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AIR", "AIR"),
                    ("WATER_SPRAY", "WATER SPRAY"),
                    ("MIST", "MIST"),
                    ("WATER_DIP", "WATER_DIP"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
