# Generated by Django 5.1.1 on 2026-03-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dimension_inspection", "0003_dimensioninspection_container_temp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dimensioninspection",
            name="total_scrap_mm",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
