# Generated by Django 5.1.1 on 2026-03-11 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dimension_inspection", "0004_dimensioninspection_total_scrap_mm"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dimensioninspection",
            old_name="backend_scrap",
            new_name="back_end_scrap",
        ),
        migrations.RenameField(
            model_name="dimensioninspection",
            old_name="frontend_scrap",
            new_name="front_end_scrap",
        ),
        migrations.RenameField(
            model_name="dimensioninspection",
            old_name="head_end_scrap_mm",
            new_name="head_end_scrap",
        ),
        migrations.RenameField(
            model_name="dimensioninspection",
            old_name="tail_end_scrap_mm",
            new_name="tail_end_scrap",
        ),
        migrations.RenameField(
            model_name="dimensioninspection",
            old_name="total_scrap_mm",
            new_name="total_scrap",
        ),
    ]
