# Generated by Django 5.1.1 on 2026-03-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dimension_inspection",
            "0005_rename_backend_scrap_dimensioninspection_back_end_scrap_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dimensioninspection",
            name="billet_length",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
