# Generated by Django 5.1.1 on 2026-03-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dimension_inspection", "0006_dimensioninspection_billet_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dimensioninspection",
            name="billet_cast_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
