# Generated by Django 5.1.1 on 2026-03-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dimension_inspection", "0007_alter_dimensioninspection_billet_cast_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="dimensioninspection",
            name="billet_temp",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="dimensioninspection",
            name="cooling_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="dimensioninspection",
            name="die_temp",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="dimensioninspection",
            name="die_unloading_other",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="dimensioninspection",
            name="die_unloading_reason",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dimensioninspection",
            name="extruded_billet",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dimensioninspection",
            name="extrusion_speed",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="dimensioninspection",
            name="planned_billet",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dimensioninspection",
            name="pullar_force_kgs",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="dimensioninspection",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dimensioninspection",
            name="sample_chacked",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dimensioninspection",
            name="section_exit_temp",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
