# Generated by Django 5.1.1 on 2026-03-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dimension_inspection", "0008_dimensioninspection_billet_temp_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dimensioninspection",
            old_name="sample_chacked",
            new_name="sample_checked",
        ),
    ]
