# Generated by Django 5.1.1 on 2026-03-12 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "dimension_inspection",
            "0010_alter_dimensioninspection_back_end_scrap_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dimensioninspection",
            options={
                "permissions": [
                    (
                        "download_dimension_inspection_excel_copy",
                        "Can download dimension inspection Excel",
                    ),
                    (
                        "download_dimension_inspection_pdf_copy",
                        "Can download dimension inspection PDF",
                    ),
                ]
            },
        ),
    ]
