# Generated by Django 5.1.1 on 2025-09-25 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workorder", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                ("finalized_bundle_ids", models.CharField(blank=True, default="")),
                ("vehicle_no", models.CharField(max_length=100, null=True)),
                ("transporter_name", models.CharField(max_length=100, null=True)),
                (
                    "shift",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B")], default="A", max_length=10
                    ),
                ),
                ("remarks", models.TextField(null=True)),
                ("dispatched_to_customer_date", models.DateField(null=True)),
                ("outward_bundle_ids", models.CharField(default="", null=True)),
                ("approved", models.BooleanField(default=False, null=True)),
                ("dispatched", models.BooleanField(default=False)),
                ("added_for_outword", models.BooleanField(default=False)),
                ("slip_no", models.CharField(max_length=100, null=True)),
                ("dispatched_date", models.DateTimeField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_workorder",
                        to="workorder.workorder",
                    ),
                ),
            ],
            options={
                "db_table": "warehouse",
                "permissions": [
                    (
                        "print_warehouse_bundle_outward_copy",
                        "Can print warehouse bundle outward",
                    ),
                    (
                        "download_warehouse_bundle_outward_excel_copy",
                        "Can download warehouse bundle outward Excel",
                    ),
                    (
                        "print_warehouse_current_stock_copy",
                        "Can print warehouse current stock",
                    ),
                    (
                        "download_warehouse_current_stock_excel_copy",
                        "Can download warehouse current stock Excel",
                    ),
                ],
            },
        ),
    ]
