# Generated by Django 5.1.1 on 2025-11-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundle_inward", "0002_initial"),
        ("warehouse", "0002_remove_warehouse_finalized_bundle_ids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="finalized_bundles",
            field=models.ManyToManyField(
                blank=True,
                related_name="finalized_in_warehouses",
                through="warehouse.WarehouseBundleInward",
                to="bundle_inward.bundleinward",
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="outward_bundles",
            field=models.ManyToManyField(
                blank=True,
                related_name="outward_in_warehouses",
                through="warehouse.WarehouseBundleOutward",
                to="bundle_inward.bundleinward",
            ),
        ),
    ]
