# Generated by Django 5.1.1 on 2025-11-14 09:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0003_warehouse_finalized_bundles_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehouse",
            name="approve",
        ),
        migrations.RemoveField(
            model_name="warehouse",
            name="approve_remarks",
        ),
        migrations.RemoveField(
            model_name="warehouse",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="warehouse",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="warehouse",
            name="done_flag",
        ),
        migrations.RemoveField(
            model_name="warehouse",
            name="f_id",
        ),
        migrations.RemoveField(
            model_name="warehouse",
            name="reject",
        ),
        migrations.AddField(
            model_name="warehouse",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="deleted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="warehouse_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="warehouse_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="dispatched_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="dispatched_to_customer_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="slip_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="transporter_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="warehouse_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="vehicle_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
