# Generated by Django 5.2.5 on 2025-12-12 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0004_remove_warehouse_approve_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehouse",
            name="transporter_name",
        ),
        migrations.RemoveField(
            model_name="warehouse",
            name="vehicle_no",
        ),
    ]
