# Generated by Django 5.2.5 on 2025-12-12 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transporter", "0006_alter_transporter_opening_balance"),
        ("vehicle_master", "0003_alter_vehiclemaster_party_name"),
        ("warehouse", "0005_remove_warehouse_transporter_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="party_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="warehouse_party_name",
                to="transporter.transporter",
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="vehicle_no",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="warehouse_vehicle_no",
                to="vehicle_master.vehiclemaster",
            ),
        ),
    ]
