# Generated by Django 5.1.1 on 2026-03-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0008_alter_warehousebundleinward_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehouse",
            name="party_name",
        ),
    ]
