# Generated by Django 5.1.1 on 2026-03-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0009_remove_warehouse_party_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="party_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
