# Generated by Django 5.1.1 on 2026-04-24 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0010_warehouse_party_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehouse",
            name="shift",
        ),
    ]
