# Generated by Django 5.1.1 on 2026-02-27 07:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gate_pass", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="gatepass",
            new_name="gate_pass_gate_pa_ae2e5f_idx",
            old_name="gate_pass_no_idx",
        ),
        migrations.RenameIndex(
            model_name="gatepass",
            new_name="gate_pass_status_1d0cee_idx",
            old_name="gate_pass_status_idx",
        ),
        migrations.RenameIndex(
            model_name="gatepass",
            new_name="gate_pass_date_ec753e_idx",
            old_name="gate_pass_date_idx",
        ),
        migrations.RenameIndex(
            model_name="gatepass",
            new_name="gate_pass_po_id_c8a4f1_idx",
            old_name="gate_pass_po_idx",
        ),
        migrations.RenameIndex(
            model_name="gatepass",
            new_name="gate_pass_party_n_9b095c_idx",
            old_name="gate_pass_party_idx",
        ),
        migrations.RenameIndex(
            model_name="gatepass",
            new_name="gate_pass_vehicle_945199_idx",
            old_name="gate_pass_vehicle_idx",
        ),
        migrations.AlterField(
            model_name="gatepass",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="gatepassitem",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
