# Generated by Django 5.1.1 on 2026-03-03 04:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gate_pass", "0003_gatepassitem_created_at_and_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="gatepass",
            new_name="gate_pass_deleted_dbf1c8_idx",
            old_name="gate_pass_deleted_is_archived_idx",
        ),
        migrations.AlterField(
            model_name="gatepassitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="gatepass",
            index=models.Index(fields=["type"], name="gate_pass_type_28fe8c_idx"),
        ),
    ]
