# Generated by Django 5.1.1 on 2025-09-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=150)),
                (
                    "sundry_group",
                    models.CharField(
                        choices=[
                            ("sundry_creditors", "sundry_creditors"),
                            ("sundry_debtors", "sundry_debtors"),
                        ],
                        default="sundry_debtors",
                        max_length=20,
                    ),
                ),
                ("account_group", models.CharField(max_length=25)),
                ("customer_category", models.CharField(max_length=25)),
                ("customer_subcategory", models.CharField(max_length=25)),
                ("customer_type", models.CharField(max_length=25)),
                ("office_address", models.TextField(null=True)),
                ("registered_address", models.TextField(null=True)),
                ("shipping_address", models.TextField(null=True)),
                ("applicable_gst", models.CharField(max_length=25, null=True)),
                ("party_section_no", models.CharField(max_length=50)),
                ("bank_name", models.CharField(max_length=25, null=True)),
                ("bank_branch_name", models.CharField(max_length=25, null=True)),
                ("bank_branch_address", models.TextField(null=True)),
                ("bank_account_number", models.CharField(max_length=25, null=True)),
                ("bank_ifsc_code", models.CharField(max_length=15, null=True)),
                ("gst_no", models.CharField(max_length=25, null=True)),
                ("gst_type", models.CharField(max_length=25, null=True)),
                ("pan_number", models.CharField(max_length=15, null=True)),
                ("udhyam_no", models.CharField(max_length=25, null=True)),
                ("sgst_number", models.CharField(max_length=25, null=True)),
                ("cgst_number", models.CharField(max_length=25, null=True)),
                ("unique_id", models.CharField(max_length=64, null=True)),
            ],
            options={
                "db_table": "party",
            },
        ),
    ]
