# Generated by Django 5.1.1 on 2025-09-25 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Production",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                ("production_no", models.CharField(max_length=100)),
                (
                    "shift",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B")], default="A", max_length=10
                    ),
                ),
                ("cavity", models.CharField(max_length=100, null=True)),
                ("time_in", models.TimeField(blank=True, null=True)),
                ("time_out", models.TimeField(blank=True, null=True)),
                ("total_cycle", models.TimeField(blank=True, null=True)),
                (
                    "billet_size",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("billet_nos", models.IntegerField(default=0, null=True)),
                (
                    "billet_weight",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                ("cut_length", models.CharField(blank=True, max_length=100, null=True)),
                ("pieces", models.IntegerField(default=0, null=True)),
                (
                    "weight_per_piece",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "recovery",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                ("scrap", models.IntegerField(default=0, null=True)),
                (
                    "speed",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "kg_per_hour",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                ("ext_pressure", models.FloatField(default=0.0, null=True)),
                ("basket_no", models.CharField(blank=True, max_length=100, null=True)),
                ("cast_no", models.CharField(max_length=100, null=True)),
                ("target", models.CharField(max_length=100, null=True)),
                ("bloster_no", models.CharField(max_length=100, null=True)),
                ("remarks", models.TextField(null=True)),
                ("production_supervisor", models.CharField(max_length=100, null=True)),
                ("power_cut_at", models.TimeField(blank=True, null=True)),
                ("power_resumed_at", models.TimeField(blank=True, null=True)),
                ("power_cut_duration", models.TimeField(blank=True, null=True)),
                (
                    "alloy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_alloy",
                        to="product.alloy",
                    ),
                ),
            ],
            options={
                "db_table": "production",
            },
        ),
    ]
