# Generated by Django 5.1.1 on 2025-09-25 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0002_initial"),
        ("die", "0003_initial"),
        ("planning", "0002_initial"),
        ("product", "0002_initial"),
        ("production", "0001_initial"),
        ("workorder", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="production",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="production",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_of_customer",
                to="customer.customer",
            ),
        ),
        migrations.AddField(
            model_name="production",
            name="die_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_die",
                to="die.die",
            ),
        ),
        migrations.AddField(
            model_name="production",
            name="grade",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_temper",
                to="product.temper",
            ),
        ),
        migrations.AddField(
            model_name="production",
            name="iwo_no",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_workorder",
                to="workorder.workorder",
            ),
        ),
        migrations.AddField(
            model_name="production",
            name="planning",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_planning",
                to="planning.planning",
            ),
        ),
        migrations.AddField(
            model_name="production",
            name="press",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_die_press",
                to="die.diepress",
            ),
        ),
        migrations.AddField(
            model_name="production",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
