# Generated by Django 5.1.1 on 2026-01-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0004_alter_production_bloster_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="production",
            name="cavity",
            field=models.IntegerField(default=0),
        ),
    ]
