# Generated by Django 5.1.1 on 2026-01-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0005_alter_production_cavity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="production",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
