# Generated by Django 5.1.1 on 2026-02-13 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0006_alter_production_updated_at"),
        ("shift", "0002_remove_shiftmaster_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="production",
            name="shift_end_snapshot",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="production",
            name="shift_name_snapshot",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="production",
            name="shift_start_snapshot",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="production",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shiftsnapshot_shift",
                to="shift.shiftmaster",
            ),
        ),
    ]
