# Generated by Django 5.1.1 on 2026-02-16 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0007_production_shift_end_snapshot_and_more"),
        ("shift", "0002_remove_shiftmaster_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="production",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_shift",
                to="shift.shiftmaster",
            ),
        ),
    ]
