# Generated by Django 5.1.1 on 2026-03-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0008_alter_production_shift"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="production",
            name="power_cut_at",
        ),
        migrations.RemoveField(
            model_name="production",
            name="power_cut_duration",
        ),
        migrations.RemoveField(
            model_name="production",
            name="power_resumed_at",
        ),
        migrations.AddField(
            model_name="production",
            name="billet_temp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Billet temperature in °C",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="production",
            name="die_station_no",
            field=models.PositiveIntegerField(
                blank=True, help_text="Die station number", null=True
            ),
        ),
        migrations.AddField(
            model_name="production",
            name="die_temp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Die temperature in °C",
                max_digits=6,
                null=True,
            ),
        ),
    ]
