# Generated by Django 5.1.1 on 2026-03-02 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0009_remove_production_power_cut_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="production",
            old_name="grade",
            new_name="temper",
        ),
    ]
