# Generated by Django 5.1.1 on 2026-03-02 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0010_rename_grade_production_temper"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="production",
            name="target",
        ),
    ]
