# Generated by Django 5.1.1 on 2026-03-02 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0011_remove_production_target"),
    ]

    operations = [
        migrations.RenameField(
            model_name="production",
            old_name="iwo_no",
            new_name="workorder",
        ),
    ]
