# Generated by Django 5.1.1 on 2026-03-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloster", "0008_alter_blostermaster_size"),
        ("production", "0012_rename_iwo_no_production_workorder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="production",
            name="bloster_no",
        ),
        migrations.AddField(
            model_name="production",
            name="bloster_no",
            field=models.ManyToManyField(
                blank=True,
                related_name="production_bloster",
                to="bloster.blostermaster",
            ),
        ),
    ]
