# Generated by Django 5.1.1 on 2026-08-03 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0123_dietool_status_alter_dietool_location"),
        ("production", "0013_remove_production_bloster_no_production_bloster_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="production",
            name="die_tool",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_die_tool",
                to="die.dietool",
            ),
        ),
        migrations.AddField(
            model_name="production",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="production",
            name="quenching_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="production",
            name="production_supervisor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
