# Generated by Django 5.1.1 on 2026-08-03 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0014_production_die_tool_production_length_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="production",
            name="basket_no",
        ),
        migrations.RemoveField(
            model_name="production",
            name="billet_nos",
        ),
        migrations.RemoveField(
            model_name="production",
            name="billet_size",
        ),
        migrations.RemoveField(
            model_name="production",
            name="billet_weight",
        ),
        migrations.RemoveField(
            model_name="production",
            name="bloster_no",
        ),
        migrations.CreateModel(
            name="BilletMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billet_size",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "billet_weight",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                ("billet_nos", models.IntegerField(default=0, null=True)),
                ("cast_no", models.CharField(max_length=100, null=True)),
                (
                    "production",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billet_production",
                        to="production.production",
                    ),
                ),
            ],
            options={
                "db_table": "billet_master",
            },
        ),
    ]
