# Generated by Django 5.1.1 on 2026-08-03 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0015_remove_production_basket_no_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftIdleLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Maintenance", "Maintenance"),
                            ("Operation", "Operation"),
                            ("Shutdown", "Shutdown"),
                        ],
                        max_length=20,
                    ),
                ),
                ("from_time", models.TimeField()),
                ("to_time", models.TimeField()),
                ("minutes", models.PositiveIntegerField()),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "production",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idle_logs",
                        to="production.production",
                    ),
                ),
            ],
            options={
                "db_table": "shift_idle_log",
            },
        ),
        migrations.CreateModel(
            name="ShiftUsedLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alloy", models.CharField(blank=True, max_length=100, null=True)),
                ("log_qty", models.FloatField()),
                (
                    "production",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_logs",
                        to="production.production",
                    ),
                ),
            ],
            options={
                "db_table": "shift_used_log",
            },
        ),
    ]
