# Generated by Django 5.1.1 on 2026-08-03 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0016_shiftidlelog_shiftusedlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="production",
            name="actual_pieces",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="production",
            name="die_tool_return_status",
            field=models.CharField(
                choices=[
                    ("RETURN_TO_DIE_TOOL_ROOM", "RETURN_TO_DIE_TOOL_ROOM"),
                    ("KEEP_AT_PRESS", "KEEP_AT_PRESS"),
                ],
                default="RETURN_TO_DIE_TOOL_ROOM",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="production",
            name="input_kg_per_hour",
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="production",
            name="operators",
            field=models.ManyToManyField(
                blank=True,
                related_name="production_operators",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="production",
            name="output_kg_per_hour",
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="production",
            name="planning_recovery",
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="production",
            name="production_process_recovery",
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="production",
            name="running_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="production",
            name="total_output_weight",
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="production",
            name="weight_per_meter",
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
