# Generated by Django 5.1.1 on 2026-08-03 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0017_production_actual_pieces_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billetmaster",
            name="billet_nos",
        ),
    ]
