# Generated by Django 5.1.1 on 2026-08-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0018_remove_billetmaster_billet_nos"),
    ]

    operations = [
        migrations.AddField(
            model_name="billetmaster",
            name="extrude_billet",
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
