# Generated by Django 5.1.1 on 2026-08-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0019_billetmaster_extrude_billet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="production",
            name="kg_per_hour",
        ),
        migrations.RemoveField(
            model_name="production",
            name="length",
        ),
        migrations.RemoveField(
            model_name="production",
            name="production_supervisor",
        ),
    ]
