# Generated by Django 5.1.1 on 2026-08-03 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0020_remove_production_kg_per_hour_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="production",
            name="cast_no",
        ),
        migrations.RemoveField(
            model_name="production",
            name="recovery",
        ),
        migrations.RemoveField(
            model_name="production",
            name="weight",
        ),
    ]
