# Generated by Django 5.1.1 on 2026-08-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "production",
            "0021_remove_production_cast_no_remove_production_recovery_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="production",
            name="scrap",
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
