# Generated by Django 5.1.1 on 2026-08-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0022_alter_production_scrap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='planning_recovery',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='production_process_recovery',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
