# Generated by Django 5.1.1 on 2026-08-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0023_alter_production_planning_recovery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='speed',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
