# Generated by Django 5.1.1 on 2026-08-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0024_alter_production_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='speed',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
