# Generated by Django 5.1.1 on 2026-08-14 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0025_alter_production_speed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='completion_status',
            field=models.CharField(blank=True, choices=[('ORDER_COMPLETE', 'Order Complete'), ('ORDER_COMPLETE_WITH_DEVIATION', 'Order Complete With Deviation'), ('PROGRAM_BREAK', 'Program Break'), ('DIE_FAIL', 'Die Fail'), ('HAND_OVER', 'Hand Over (Next Shift)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='deviation_type',
            field=models.CharField(blank=True, choices=[('SECTION_CUT', 'Section Cut'), ('ROUGHNESS', 'Roughness'), ('JOINT', 'Joint'), ('DIMENSION', 'Dimension'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('ROUGHNESS', 'Roughness'), ('SECTION_CUT', 'Section Cut'), ('JOINT_PROBLEM', 'Joint Problem'), ('DIE_CRACK', 'Die Crack'), ('DIMENSION', 'Dimension'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='production_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='program_break_reason',
            field=models.CharField(blank=True, choices=[('DIE_TOOL_MAINTENANCE', 'Die Tool Maintenance'), ('SHUTDOWN', 'Shutdown'), ('ALLOY_CHANGE', 'Alloy Change'), ('POWER_FAILURE', 'Power Failure'), ('BILLET_FINISH', 'Billet Finish'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='supervisors',
            field=models.ManyToManyField(blank=True, related_name='production_supervisors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='production',
            name='die_tool_return_status',
            field=models.CharField(choices=[('RETURN_TO_DIE_TOOL_ROOM', 'Return to Die Tool Room'), ('KEEP_AT_PRESS', 'Keep at Press')], default='RETURN_TO_DIE_TOOL_ROOM', max_length=30),
        ),
    ]
