# Generated by Django 5.1.1 on 2026-03-08

import uuid
from decimal import Decimal

from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0046_grn_gate_entry_invoice_no_grnitem_batch_heat"),
        (
            "product",
            "0055_remove_temper_unique_active_temper_name_code_section_and_more",
        ),
        ("store", "0004_alter_store_store_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapGenerationRemelt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "remelt_no",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("remelt_date", models.DateField(db_index=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "total_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("COMPLETED", "Completed"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET_NULL,
                        related_name="scrap_generation_remelts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination_store",
                    models.ForeignKey(
                        on_delete=models.PROTECT,
                        related_name="scrap_generation_remelts_in",
                        to="store.store",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=models.PROTECT,
                        related_name="scrap_generation_remelts",
                        to="common.plant",
                    ),
                ),
                (
                    "source_store",
                    models.ForeignKey(
                        on_delete=models.PROTECT,
                        related_name="scrap_generation_remelts_out",
                        to="store.store",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET_NULL,
                        related_name="scrap_generation_remelts_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Scrap Generation Remelt",
                "verbose_name_plural": "Scrap Generation Remelts",
                "db_table": "scrap_generation_remelt",
                "ordering": ["-remelt_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScrapGenerationRemeltItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("batch_heat", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "qty",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=18,
                        validators=[MinValueValidator(Decimal("0.0001"))],
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=models.PROTECT,
                        related_name="scrap_generation_remelt_items",
                        to="product.item",
                    ),
                ),
                (
                    "scrap_generation_remelt",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="items",
                        to="scrap_generation_remelt.scrapgenerationremelt",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=models.PROTECT,
                        related_name="scrap_generation_remelt_items",
                        to="common.uom",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scrap Generation Remelt Item",
                "verbose_name_plural": "Scrap Generation Remelt Items",
                "db_table": "scrap_generation_remelt_item",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="scrapgenerationremelt",
            index=models.Index(
                fields=["remelt_no"], name="scrap_gener_remelt__f4f4cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapgenerationremelt",
            index=models.Index(fields=["status"], name="scrap_gener_status_23d070_idx"),
        ),
        migrations.AddIndex(
            model_name="scrapgenerationremelt",
            index=models.Index(
                fields=["remelt_date"], name="scrap_gener_remelt__cb05a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapgenerationremelt",
            index=models.Index(
                fields=["plant_id"], name="scrap_gener_plant_i_b2ec21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapgenerationremelt",
            index=models.Index(
                fields=["source_store_id"], name="scrap_gener_source__d2c5c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapgenerationremelt",
            index=models.Index(
                fields=["destination_store_id"], name="scrap_gener_destina_d7a1c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapgenerationremelt",
            index=models.Index(
                fields=["is_archived"], name="scrap_gener_is_arch_661f06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapgenerationremelt",
            index=models.Index(
                fields=["status", "is_archived"], name="scrap_gener_status_4281ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapgenerationremeltitem",
            index=models.Index(
                fields=["scrap_generation_remelt_id"],
                name="scrap_gener_scrap_g_57a4b4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scrapgenerationremeltitem",
            index=models.Index(
                fields=["item_id"], name="scrap_gener_item_id_7bd93a_idx"
            ),
        ),
    ]
