# Generated by Django 5.1.1 on 2026-03-08 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scrap_generation_remelt", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="scrapgenerationremelt",
            new_name="scrap_gener_remelt__aaed6f_idx",
            old_name="scrap_gener_remelt__f4f4cb_idx",
        ),
        migrations.RenameIndex(
            model_name="scrapgenerationremelt",
            new_name="scrap_gener_status_7236c7_idx",
            old_name="scrap_gener_status_23d070_idx",
        ),
        migrations.RenameIndex(
            model_name="scrapgenerationremelt",
            new_name="scrap_gener_remelt__5c8676_idx",
            old_name="scrap_gener_remelt__cb05a2_idx",
        ),
        migrations.RenameIndex(
            model_name="scrapgenerationremelt",
            new_name="scrap_gener_plant_i_e37210_idx",
            old_name="scrap_gener_plant_i_b2ec21_idx",
        ),
        migrations.RenameIndex(
            model_name="scrapgenerationremelt",
            new_name="scrap_gener_source__6acb66_idx",
            old_name="scrap_gener_source__d2c5c4_idx",
        ),
        migrations.RenameIndex(
            model_name="scrapgenerationremelt",
            new_name="scrap_gener_destina_b3aee7_idx",
            old_name="scrap_gener_destina_d7a1c8_idx",
        ),
        migrations.RenameIndex(
            model_name="scrapgenerationremelt",
            new_name="scrap_gener_is_arch_6ef721_idx",
            old_name="scrap_gener_is_arch_661f06_idx",
        ),
        migrations.RenameIndex(
            model_name="scrapgenerationremelt",
            new_name="scrap_gener_status_c12744_idx",
            old_name="scrap_gener_status_4281ad_idx",
        ),
        migrations.RenameIndex(
            model_name="scrapgenerationremeltitem",
            new_name="scrap_gener_scrap_g_e3dfd3_idx",
            old_name="scrap_gener_scrap_g_57a4b4_idx",
        ),
        migrations.RenameIndex(
            model_name="scrapgenerationremeltitem",
            new_name="scrap_gener_item_id_ee431f_idx",
            old_name="scrap_gener_item_id_7bd93a_idx",
        ),
    ]
