# Generated by Django 5.1.1

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("module_name", models.CharField(db_index=True, max_length=100)),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=10)),
                ("total_rows", models.IntegerField(default=0)),
                ("success_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partial Success"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "error_summary",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_logs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "import_log",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportErrorRow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("row_number", models.IntegerField(db_index=True)),
                (
                    "error_type",
                    models.CharField(
                        choices=[
                            ("validation", "Validation Error"),
                            ("reference", "Reference Error"),
                            ("business_rule", "Business Rule Violation"),
                            ("duplicate", "Duplicate Entry"),
                            ("database", "Database Error"),
                            ("unknown", "Unknown Error"),
                        ],
                        default="validation",
                        max_length=20,
                    ),
                ),
                ("field_name", models.CharField(blank=True, max_length=100, null=True)),
                ("error_message", models.TextField()),
                ("raw_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "import_log",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="error_rows",
                        to="imports.importlog",
                    ),
                ),
            ],
            options={
                "db_table": "import_error_row",
                "ordering": ["row_number"],
            },
        ),
        migrations.AddIndex(
            model_name="importlog",
            index=models.Index(
                fields=["module_name", "status"], name="import_log_module__idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importlog",
            index=models.Index(fields=["started_at"], name="import_log_started_idx"),
        ),
        migrations.AddIndex(
            model_name="importerrorrow",
            index=models.Index(
                fields=["import_log", "row_number"], name="import_error_import__idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importerrorrow",
            index=models.Index(fields=["error_type"], name="import_error_error__idx"),
        ),
    ]
