# Generated by Django 5.1.1 on 2025-12-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="importerrorrow",
            new_name="import_erro_import__ef3202_idx",
            old_name="import_error_import__idx",
        ),
        migrations.RenameIndex(
            model_name="importerrorrow",
            new_name="import_erro_error_t_14b3c9_idx",
            old_name="import_error_error__idx",
        ),
        migrations.RenameIndex(
            model_name="importlog",
            new_name="import_log_module__8d26d4_idx",
            old_name="import_log_module__idx",
        ),
        migrations.RenameIndex(
            model_name="importlog",
            new_name="import_log_started_59f4a3_idx",
            old_name="import_log_started_idx",
        ),
    ]
