# Generated by Django 5.1.1 on 2026-03-13 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechanical_test", "0001_initial"),
        ("production", "0012_rename_iwo_no_production_workorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="mechanicaltestdetail",
            name="production_no",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mechanical_test_detail_production_no",
                to="production.production",
            ),
        ),
    ]
