# Generated by Django 5.1.1 on 2026-03-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechanical_test", "0002_mechanicaltestdetail_production_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="mechanicaltest",
            name="furnace_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mechanicaltest",
            name="heat_treatment_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
