# Generated by Django 5.1.1 on 2026-03-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechanical_test", "0003_mechanicaltest_furnace_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mechanicaltest",
            name="source_type",
            field=models.CharField(
                blank=True,
                choices=[("PRODUCTION", "PRODUCTION"), ("AGEING", "AGEING")],
                max_length=20,
                null=True,
            ),
        ),
    ]
