# Generated by Django 5.1.1 on 2026-03-13 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechanical_test", "0004_alter_mechanicaltest_source_type"),
        ("shift", "0002_remove_shiftmaster_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mechanicaltest",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_shift",
                to="shift.shiftmaster",
            ),
        ),
        migrations.AddField(
            model_name="mechanicaltest",
            name="shift_end_snapshot",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mechanicaltest",
            name="shift_name_snapshot",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="mechanicaltest",
            name="shift_start_snapshot",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
