# Generated by Django 5.1.1 on 2026-03-13 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mechanical_test", "0005_mechanicaltest_shift_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mechanicaltest",
            options={
                "permissions": [
                    (
                        "print_mechanical_test_excel_copy",
                        "Can print mechanical test Excel",
                    ),
                    ("print_mechanical_test_pdf_copy", "Can print mechanical test PDF"),
                ]
            },
        ),
    ]
