# Generated by Django 5.1.1 on 2026-03-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechanical_test", "0006_alter_mechanicaltest_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mechanicaltest",
            name="qc_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
