# Generated by Django 5.1.1 on 2026-08-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ageing_cycle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agingcycle',
            name='zone1_temp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agingcycle',
            name='zone2_temp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agingcycle',
            name='zone3_temp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agingcycle',
            name='zone4_temp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
