# Generated by Django 5.1.1 on 2026-03-03 04:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gate_entry", "0005_gateentry_is_converted_grn_reference"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="gateentry",
            new_name="gate_entry_gate_en_035b9f_idx",
            old_name="gate_entry_gate_en_7a1b2c_idx",
        ),
        migrations.RenameIndex(
            model_name="gateentry",
            new_name="gate_entry_date_0cecb2_idx",
            old_name="gate_entry_date_8b2c3d_idx",
        ),
        migrations.RenameIndex(
            model_name="gateentry",
            new_name="gate_entry_status_21ffbb_idx",
            old_name="gate_entry_status_9c3d4e_idx",
        ),
        migrations.RenameIndex(
            model_name="gateentry",
            new_name="gate_entry_is_conv_b128cf_idx",
            old_name="gate_entry_is_conv_67e8fa_idx",
        ),
        migrations.RenameIndex(
            model_name="gateentry",
            new_name="gate_entry_vendor__043b59_idx",
            old_name="gate_entry_vendor__0d4e5f_idx",
        ),
        migrations.RenameIndex(
            model_name="gateentry",
            new_name="gate_entry_transpo_8d6119_idx",
            old_name="gate_entry_transpo_1e5f6a_idx",
        ),
        migrations.RenameIndex(
            model_name="gateentry",
            new_name="gate_entry_vehicle_396367_idx",
            old_name="gate_entry_vehicle_2f6a7b_idx",
        ),
        migrations.RenameIndex(
            model_name="gateentry",
            new_name="gate_entry_deleted_a22798_idx",
            old_name="gate_entry_deleted_3a7b8c_idx",
        ),
        migrations.RenameIndex(
            model_name="gateentry",
            new_name="gate_entry_deleted_6a4fb5_idx",
            old_name="gate_entry_deleted_is_arch_idx",
        ),
        migrations.AlterField(
            model_name="gateentryitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="gateentryitem",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
