# Generated by Django 5.1.1 on 2026-07-30 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "gate_entry",
            "0006_rename_gate_entry_gate_en_7a1b2c_idx_gate_entry_gate_en_035b9f_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="gateentry",
            name="gate_entry_is_conv_b128cf_idx",
        ),
        migrations.RemoveField(
            model_name="gateentry",
            name="grn_reference",
        ),
        migrations.RemoveField(
            model_name="gateentry",
            name="is_converted",
        ),
    ]
