# Generated by Django 5.1.1 on 2025-09-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Planning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                ("planning_no", models.CharField(max_length=100, null=True)),
                ("planning_date", models.DateField(auto_now=True)),
                ("plan_pcs", models.IntegerField(default=0, null=True)),
                ("plan_qty", models.FloatField(default=0.0, null=True)),
                ("aging", models.CharField(max_length=50, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "billet_size",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "total_billet",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "cavity",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "last_wt_mtr",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "cut_length",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "billet_wt_kg",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "butt_wt_kg",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "ext_lenth",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                ("no_of_pcs", models.IntegerField(default=0, null=True)),
                (
                    "process_recovery",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
            ],
            options={
                "db_table": "planning",
                "permissions": [
                    ("download_planning_pdf_copy", "Can download planning PDF"),
                    ("download_planning_excel_copy", "Can download planning Excel"),
                    (
                        "download_planning_priority_pdf_copy",
                        "Can download planning priority PDF",
                    ),
                    (
                        "download_planning_priority_excel_copy",
                        "Can download planning priority Excel",
                    ),
                ],
            },
        ),
    ]
