# Generated by Django 5.1.1 on 2025-09-25 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("die", "0003_initial"),
        ("planning", "0001_initial"),
        ("workorder", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="planning",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="planning",
            name="die_tool",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planning_die_tool",
                to="die.dietool",
            ),
        ),
        migrations.AddField(
            model_name="planning",
            name="profile_no",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planning_profile_no",
                to="die.die",
            ),
        ),
        migrations.AddField(
            model_name="planning",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="planning",
            name="workorder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planning_workorder",
                to="workorder.workorder",
            ),
        ),
        migrations.AddField(
            model_name="planning",
            name="workorder_detail",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planning_workorder_detail",
                to="workorder.workorderdetail",
            ),
        ),
    ]
