# Generated by Django 5.1.1 on 2026-01-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0004_planning_quenching_type_alter_planning_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planning",
            name="flow_rate",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="planning",
            name="water_pressure",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
