# Generated by Django 5.1.1 on 2026-01-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0005_planning_flow_rate_planning_water_pressure"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planning",
            name="billet_size",
        ),
        migrations.RemoveField(
            model_name="planning",
            name="billet_wt_kg",
        ),
        migrations.RemoveField(
            model_name="planning",
            name="butt_wt_kg",
        ),
        migrations.RemoveField(
            model_name="planning",
            name="cavity",
        ),
        migrations.RemoveField(
            model_name="planning",
            name="cut_length",
        ),
        migrations.RemoveField(
            model_name="planning",
            name="ext_lenth",
        ),
        migrations.RemoveField(
            model_name="planning",
            name="last_wt_mtr",
        ),
        migrations.RemoveField(
            model_name="planning",
            name="no_of_pcs",
        ),
        migrations.RemoveField(
            model_name="planning",
            name="process_recovery",
        ),
        migrations.RemoveField(
            model_name="planning",
            name="total_billet",
        ),
    ]
