# Generated by Django 5.1.1 on 2026-01-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0007_planning_actwt_planning_bltsize_planning_bltwt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planning",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
