# Generated by Django 5.1.1 on 2026-01-29 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0049_alter_diecategory_created_by_and_more"),
        ("planning", "0008_alter_planning_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planning",
            name="die_tool",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planning_die_tool",
                to="die.dietool",
            ),
        ),
    ]
