# Generated by Django 5.1.1 on 2026-01-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0009_alter_planning_die_tool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planning",
            name="pcsPerBlt",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
