# Generated by Django 5.1.1 on 2026-01-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0010_alter_planning_pcsperblt"),
    ]

    operations = [
        migrations.AddField(
            model_name="planning",
            name="cancel_status",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="planning",
            name="hold_status",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="planning",
            name="scheduled_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="planning",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Submitted", "Submitted"),
                    ("Approved", "Approved"),
                    ("Scheduled", "Scheduled"),
                    ("In-Progress", "In-Progress"),
                    ("Partially-Closed", "Partially-Closed"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                    ("On-Hold", "On-Hold"),
                ],
                default="Draft",
                max_length=30,
            ),
        ),
    ]
