# Generated by Django 5.1.1 on 2026-02-03 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die_requisition", "0008_remove_dierequisition_planning"),
        ("planning", "0011_planning_cancel_status_planning_hold_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planning",
            name="die_tool",
        ),
        migrations.AddField(
            model_name="planning",
            name="die_requisition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planning_die_requisition",
                to="die_requisition.dierequisition",
            ),
        ),
    ]
