# Generated by Django 5.1.1 on 2026-02-03 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die_requisition", "0008_remove_dierequisition_planning"),
        ("planning", "0012_remove_planning_die_tool_planning_die_requisition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planning",
            name="die_requisition",
        ),
        migrations.AddField(
            model_name="planning",
            name="die_requisition_detail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planning_die_requisition_detail",
                to="die_requisition.dierequisitiondetail",
            ),
        ),
    ]
