# Generated by Django 5.1.1 on 2026-02-03 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die_requisition", "0008_remove_dierequisition_planning"),
        ("planning", "0013_remove_planning_die_requisition_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planning",
            name="die_requisition_detail",
        ),
        migrations.AddField(
            model_name="planning",
            name="die_requisition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planning_die_requisition",
                to="die_requisition.dierequisition",
            ),
        ),
    ]
