# Generated by Django 5.1.1 on 2026-02-13 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0052_alter_conversionrate_conversion"),
        ("die_requisition", "0010_alter_dierequisition_options"),
        ("planning", "0016_planning_approved_at_planning_approved_by_and_more"),
        ("workorder", "0013_alter_workorder_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="planning",
            name="approval_remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="planning",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="planning",
            name="scheduled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="planning_scheduled_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="planning",
            name="scheduling_remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="planning",
            index=models.Index(fields=["planning_no"], name="idx_planning_no"),
        ),
        migrations.AddIndex(
            model_name="planning",
            index=models.Index(fields=["status"], name="idx_planning_status"),
        ),
        migrations.AddIndex(
            model_name="planning",
            index=models.Index(fields=["planning_date"], name="idx_planning_date"),
        ),
        migrations.AddIndex(
            model_name="planning",
            index=models.Index(
                fields=["scheduled_date"], name="idx_planning_scheduled_date"
            ),
        ),
        migrations.AddIndex(
            model_name="planning",
            index=models.Index(fields=["aging"], name="idx_planning_aging"),
        ),
        migrations.AddIndex(
            model_name="planning",
            index=models.Index(
                fields=["workorder", "status"], name="idx_workorder_status"
            ),
        ),
        migrations.AddIndex(
            model_name="planning",
            index=models.Index(
                fields=["profile_no", "status"], name="idx_profile_status"
            ),
        ),
        migrations.AddIndex(
            model_name="planning",
            index=models.Index(
                fields=["die_requisition", "status"], name="idx_die_req_status"
            ),
        ),
    ]
