# Generated by Django 5.1.1 on 2026-03-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0017_planning_approval_remarks_planning_scheduled_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planning",
            name="butt_weight_kg",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
