# Generated by Django 5.1.1 on 2026-06-04 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0018_planning_butt_weight_kg"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="planning",
            name="idx_planning_aging",
        ),
        migrations.RemoveField(
            model_name="planning",
            name="aging",
        ),
    ]
