# Generated by Django 5.1.1 on 2026-06-04 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ageing_cycle", "0001_initial"),
        ("planning", "0019_remove_planning_idx_planning_aging_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planning",
            name="ageing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="planning_ageing_cycle",
                to="ageing_cycle.agingcycle",
            ),
        ),
    ]
