# Generated by Django 5.1.1 on 2026-07-20 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0020_planning_ageing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planning",
            name="actWt",
        ),
        migrations.RemoveField(
            model_name="planning",
            name="bltSize",
        ),
        migrations.RemoveField(
            model_name="planning",
            name="bltWt",
        ),
        migrations.RemoveField(
            model_name="planning",
            name="buttWt",
        ),
        migrations.RemoveField(
            model_name="planning",
            name="extLen",
        ),
        migrations.RemoveField(
            model_name="planning",
            name="netOut",
        ),
        migrations.RemoveField(
            model_name="planning",
            name="pcsPerBlt",
        ),
        migrations.RemoveField(
            model_name="planning",
            name="recovery",
        ),
        migrations.RemoveField(
            model_name="planning",
            name="starOne",
        ),
        migrations.RemoveField(
            model_name="planning",
            name="starTwo",
        ),
        migrations.RemoveField(
            model_name="planning",
            name="totalBillets",
        ),
        migrations.RemoveField(
            model_name="planning",
            name="totalKgs",
        ),
        migrations.RemoveField(
            model_name="planning",
            name="totalWastage",
        ),
    ]
