# Generated by Django 5.1.1 on 2025-11-10 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("material", "0002_alter_material_updated_at"),
        ("transporter", "0006_alter_transporter_opening_balance"),
        ("vehicle_type", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecondWeightEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight_for",
                    models.CharField(
                        choices=[
                            ("gross_weight", "Gross_weight"),
                            ("tare_weight", "Tare_weight"),
                        ],
                        default="gross_weight",
                        max_length=50,
                    ),
                ),
                (
                    "cash_party_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "weight_automatic",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=50,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=50, null=True
                    ),
                ),
                (
                    "gross_weight",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=50, null=True
                    ),
                ),
                (
                    "tare_weight",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=50, null=True
                    ),
                ),
                (
                    "net_weight",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=50, null=True
                    ),
                ),
                ("date_time_first", models.DateTimeField()),
                ("date_time_second", models.DateTimeField()),
                (
                    "mound",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=50, null=True
                    ),
                ),
                ("serial_no", models.CharField(blank=True, max_length=100, null=True)),
                ("total_copy", models.IntegerField(default=1)),
                ("vehicle_no", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "party_mobile_no",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="second_weight_entry_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="second_weight_entry_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="second_weight_entry_material",
                        to="material.material",
                    ),
                ),
                (
                    "party_name",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"deleted": False, "is_active": "active"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transporter.transporter",
                    ),
                ),
                (
                    "purchaser",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={
                            "groups__name": "Purchaser",
                            "is_active": True,
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="second_weight_purchaser_weight_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"groups__name": "seller", "is_active": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="second_weigt_seller_weight_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="second_weight_entry_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="second_weight_entry_vehicletype",
                        to="vehicle_type.vehicletype",
                    ),
                ),
            ],
            options={
                "db_table": "second_weight_entry",
            },
        ),
    ]
