# Generated by Django 5.1.1 on 2025-11-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("second_weight_entry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="secondweightentry",
            name="capture_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="second_weight_photos/"
            ),
        ),
    ]
