# Generated by Django 5.2.5 on 2025-12-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("second_weight_entry", "0003_alter_secondweightentry_weight_for"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secondweightentry",
            name="capture_photo",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
