# Generated by Django 5.2.5 on 2025-12-09 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("second_weight_entry", "0004_alter_secondweightentry_capture_photo"),
        ("vehicle_master", "0003_alter_vehiclemaster_party_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secondweightentry",
            name="vehicle_no",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="second_weight_entry_vehicle_no",
                to="vehicle_master.vehiclemaster",
            ),
        ),
    ]
