# Generated by Django 5.1.1 on 2026-03-12 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("second_weight_entry", "0005_alter_secondweightentry_vehicle_no"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="secondweightentry",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"groups__name": "Seller", "is_active": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="second_weigt_seller_weight_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
