# Generated by Django 5.1.1 on 2026-03-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("second_weight_entry", "0006_alter_secondweightentry_seller"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="secondweightentry",
            options={
                "permissions": [
                    (
                        "download_second_weight_entry_excel_copy",
                        "Can download second weight entry Excel",
                    ),
                    (
                        "download_second_weight_entry_pdf_copy",
                        "Can download second weight entry PDF",
                    ),
                ]
            },
        ),
    ]
