# Generated by Django 5.1.1 on 2026-03-23 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_weight_entry", "0009_alter_firstweightentry_options"),
        ("second_weight_entry", "0007_alter_secondweightentry_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="secondweightentry",
            name="first_weight_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="second_weight_entry_first_weight_entry",
                to="first_weight_entry.firstweightentry",
            ),
        ),
    ]
