# Generated by Django 5.1.1 on 2026-03-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("second_weight_entry", "0009_alter_secondweightentry_first_weight_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secondweightentry",
            name="date_time_second",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
