# Generated by Django 5.1.1 on 2026-03-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("second_weight_entry", "0010_alter_secondweightentry_date_time_second"),
    ]

    operations = [
        migrations.AddField(
            model_name="secondweightentry",
            name="is_same_weight_allowed",
            field=models.BooleanField(default=False),
        ),
    ]
