# Generated by Django 5.1.1 on 2026-03-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("second_weight_entry", "0011_secondweightentry_is_same_weight_allowed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="secondweightentry",
            name="weight",
        ),
    ]
