# Generated by Django 5.1.1 on 2026-03-24 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("second_weight_entry", "0012_remove_secondweightentry_weight"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="secondweightentry",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="second_weigt_seller_weight_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="secondweightentry",
            name="weight_for",
            field=models.CharField(
                choices=[
                    ("gross weight", "Gross weight"),
                    ("tare weight", "Tare weight"),
                ],
                default="gross weight",
                max_length=50,
            ),
        ),
    ]
