# Generated by Django 5.1.1 on 2026-03-25 07:49

import django.db.models.deletion
from django.db import migrations, models


def migrate_material_to_uuid(apps, schema_editor):
    """
    Drop the old bigint material_id column and create a new UUID-based one.
    Since we can't map old IDs to UUIDs, all values are set to NULL.
    """
    with schema_editor.connection.cursor() as cursor:
        # Find and drop all foreign key constraints referencing this column
        cursor.execute(
            """
            SELECT constraint_name 
            FROM information_schema.table_constraints 
            WHERE table_name='second_weight_entry' 
            AND constraint_type='FOREIGN KEY'
            AND constraint_name LIKE '%material%'
        """
        )
        constraints = cursor.fetchall()
        for constraint in constraints:
            cursor.execute(
                f"""
                ALTER TABLE second_weight_entry 
                DROP CONSTRAINT {constraint[0]}
            """
            )

        # Drop the old column
        cursor.execute(
            """
            ALTER TABLE second_weight_entry 
            DROP COLUMN IF EXISTS material_id
        """
        )

        # Create the new UUID column
        cursor.execute(
            """
            ALTER TABLE second_weight_entry 
            ADD COLUMN material_id uuid NULL
        """
        )


def reverse_migrate(apps, schema_editor):
    """Reverse: drop UUID column"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            ALTER TABLE second_weight_entry 
            DROP COLUMN IF EXISTS material_id
        """
        )
        cursor.execute(
            """
            ALTER TABLE second_weight_entry 
            ADD COLUMN material_id bigint NULL
        """
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "product",
            "0055_remove_temper_unique_active_temper_name_code_section_and_more",
        ),
        ("second_weight_entry", "0013_alter_secondweightentry_seller_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_material_to_uuid, reverse_migrate),
        migrations.AlterField(
            model_name="secondweightentry",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="second_weight_entry_material",
                to="product.item",
            ),
        ),
    ]
