# Generated by Django 5.1.1 on 2026-03-25 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("second_weight_entry", "0014_alter_secondweightentry_material"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="secondweightentry",
            name="capture_photo",
        ),
    ]
