# Generated by Django 5.1.1 on 2026-03-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("second_weight_entry", "0015_remove_secondweightentry_capture_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="secondweightentry",
            name="capture_photo_second_1",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="secondweightentry",
            name="capture_photo_second_2",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
