# Generated by Django 5.1.1 on 2026-03-06 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0046_grn_gate_entry_invoice_no_grnitem_batch_heat"),
        ("customer", "0025_remove_customer_customer_cu_custome_d3a0b9_idx_and_more"),
        ("scrap_sale", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="scrapitem",
            index=models.Index(
                fields=["item_code"], name="scrap_item_item_co_bcffc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapitem",
            index=models.Index(
                fields=["is_archived"], name="scrap_item_is_arch_c635b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapsale",
            index=models.Index(
                fields=["sale_no"], name="scrap_sale_sale_no_c72914_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapsale",
            index=models.Index(fields=["status"], name="scrap_sale_status_7c307a_idx"),
        ),
        migrations.AddIndex(
            model_name="scrapsale",
            index=models.Index(
                fields=["sale_date"], name="scrap_sale_sale_da_489113_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapsale",
            index=models.Index(
                fields=["customer_id"], name="scrap_sale_custome_eb3467_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapsale",
            index=models.Index(
                fields=["is_archived"], name="scrap_sale_is_arch_7ff2ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapsale",
            index=models.Index(
                fields=["status", "is_archived"], name="scrap_sale_status_c545bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapsaleitem",
            index=models.Index(
                fields=["scrap_sale_id"], name="scrap_sale__scrap_s_e3d76a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapsaleitem",
            index=models.Index(
                fields=["scrap_item_id"], name="scrap_sale__scrap_i_bc6906_idx"
            ),
        ),
    ]
