# Generated by Django 5.1.1 on 2025-09-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("ARCHIVE", "Archive"),
                            ("RESTORE", "Restore"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("PRINT", "Print"),
                            ("DOWNLOAD", "Download"),
                            ("CONVERT", "Convert"),
                            ("SHIFT BUNDLE", "Shift Bundle"),
                            ("VERIFY", "Verify"),
                            ("FINALIZE BUNDLE", "Finalize Bundle"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "module_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ip_address", models.CharField(blank=True, max_length=50, null=True)),
                ("discription", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, null=True)),
                ("payload", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "log_activity",
                "ordering": ["-timestamp"],
            },
        ),
    ]
