# Generated by Django 4.2.8 on 2026-03-19 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_alter_companysettings_updated_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taxcompliancesettings",
            old_name="default_tax_rate",
            new_name="igst",
        ),
    ]
