# Generated by Django 5.1.1 on 2026-03-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0003_rename_default_tax_rate_taxcompliancesettings_igst"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxcompliancesettings",
            name="cgst",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="taxcompliancesettings",
            name="sgst",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
