# Generated by Django 5.1.1 on 2026-04-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0004_taxcompliancesettings_cgst_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialsettings",
            name="payment_terms",
            field=models.CharField(
                choices=[("7", "7"), ("15", "15"), ("30", "30")],
                default="30",
                max_length=20,
            ),
        ),
    ]
