# Generated by Django 5.1.1 on 2026-06-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0006_productionsettings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companysettings",
            old_name="address",
            new_name="factory_address",
        ),
        migrations.AddField(
            model_name="companysettings",
            name="office_address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
