# Generated by Django 5.1.1 on 2026-06-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0007_rename_address_companysettings_factory_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysettings",
            name="color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
