# Generated by Django 5.1.1 on 2026-06-15 06:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0008_companysettings_color"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productionsettings",
            name="nalco_approved_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="nalco_approved_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
