# Generated by Django 5.1.1 on 2026-07-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0009_productionsettings_nalco_approved_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysettings",
            name="landline",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
