# Generated by Django 5.1.1 on 2026-06-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material_indent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialindent",
            name="indent_no",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
