# Generated by Django 5.1.1 on 2026-06-19 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material_indent", "0002_materialindent_indent_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialindentdetail",
            name="material_indent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="material_indent",
                to="material_indent.materialindent",
            ),
        ),
    ]
