# Generated by Django 5.1.1 on 2026-07-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material_indent", "0003_alter_materialindentdetail_material_indent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialindentdetail",
            name="available_qty",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=0.0,
                max_digits=10,
                max_length=10,
                null=True,
            ),
        ),
    ]
