# Generated by Django 5.1.1 on 2025-09-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DieQuotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                (
                    "minimum_order_qty",
                    models.CharField(
                        choices=[
                            ("<300", "<300"),
                            ("300 - 500", "300 - 500"),
                            (">500", ">500"),
                        ],
                        default="<300",
                        max_length=250,
                    ),
                ),
                (
                    "die_right",
                    models.CharField(
                        choices=[("Hepl", "Hepl"), ("Customer", "Customer")],
                        default="Hepl",
                        max_length=250,
                    ),
                ),
                ("sample_delivery", models.CharField(max_length=250, null=True)),
                ("terms_and_condition", models.TextField(null=True)),
                ("quotation_date", models.DateTimeField(auto_now=True)),
                ("die_quotation_no", models.CharField(max_length=100, null=True)),
                (
                    "inquiry_base_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "db_table": "die_quotation",
                "permissions": [
                    ("print_die_quotation_pdf_copy", "Can print die quotation"),
                    (
                        "download_die_quotation_excel_copy",
                        "Can download die quotation Excel",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DieQuotationDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                ("customer_reference_no", models.CharField(max_length=250, null=True)),
                ("press_capacity", models.CharField(max_length=250, null=True)),
                ("quantity", models.CharField(max_length=250, null=True)),
                ("unit_of_measurement", models.CharField(max_length=25, null=True)),
                (
                    "profile_devlopment_cost",
                    models.FloatField(max_length=250, null=True),
                ),
                (
                    "inquiry_number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
            ],
            options={
                "db_table": "die_quotation_details",
            },
        ),
    ]
