# Generated by Django 5.1.1 on 2025-11-12 05:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die_quotation", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diequotation",
            name="approve",
        ),
        migrations.RemoveField(
            model_name="diequotation",
            name="approve_remarks",
        ),
        migrations.RemoveField(
            model_name="diequotation",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="diequotation",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="diequotation",
            name="done_flag",
        ),
        migrations.RemoveField(
            model_name="diequotation",
            name="f_id",
        ),
        migrations.RemoveField(
            model_name="diequotation",
            name="reject",
        ),
        migrations.RemoveField(
            model_name="diequotationdetails",
            name="approve",
        ),
        migrations.RemoveField(
            model_name="diequotationdetails",
            name="approve_remarks",
        ),
        migrations.RemoveField(
            model_name="diequotationdetails",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="diequotationdetails",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="diequotationdetails",
            name="done_flag",
        ),
        migrations.RemoveField(
            model_name="diequotationdetails",
            name="f_id",
        ),
        migrations.RemoveField(
            model_name="diequotationdetails",
            name="reject",
        ),
        migrations.AddField(
            model_name="diequotation",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diequotation",
            name="deleted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diequotation_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="diequotationdetails",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diequotationdetails",
            name="deleted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diequotationdetail_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="diequotation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="diequotation",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diequotation_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="diequotation",
            name="die_quotation_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="diequotation",
            name="sample_delivery",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="diequotation",
            name="terms_and_condition",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="diequotation",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="diequotation",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diequotation_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="diequotationdetails",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="diequotationdetails",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diequotationdetail_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="diequotationdetails",
            name="customer_reference_no",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="diequotationdetails",
            name="press_capacity",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="diequotationdetails",
            name="profile_devlopment_cost",
            field=models.FloatField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="diequotationdetails",
            name="quantity",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="diequotationdetails",
            name="unit_of_measurement",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="diequotationdetails",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="diequotationdetails",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diequotationdetail_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
