# Generated by Django 5.1.1 on 2026-01-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die_quotation", "0003_remove_diequotation_approve_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diequotation",
            name="die_right",
            field=models.CharField(
                choices=[("Own", "Own"), ("Customer", "Customer")],
                default="Own",
                max_length=250,
            ),
        ),
    ]
