# Generated by Django 5.1.1 on 2026-01-06 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0010_alter_customer_company_type"),
        ("die", "0043_alter_diesubcategory_name"),
        ("die_quotation", "0004_alter_diequotation_die_right"),
        ("product", "0015_alter_temper_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="diequotation",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="diequotation",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="diequotation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="diequotationdetails",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="diequotationdetails",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="diequotationdetails",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="diequotation",
            index=models.Index(
                fields=["-id", "deleted"], name="die_quotati_id_5cb55f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diequotation",
            index=models.Index(
                fields=["customer", "deleted"], name="die_quotati_custome_8157bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diequotation",
            index=models.Index(
                fields=["die_quotation_no"], name="die_quotati_die_quo_15d76f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diequotation",
            index=models.Index(
                fields=["quotation_date", "deleted"],
                name="die_quotati_quotati_f29112_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="diequotationdetails",
            index=models.Index(
                fields=["die_quotation", "deleted"],
                name="die_quotati_die_quo_41032d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="diequotationdetails",
            index=models.Index(
                fields=["inquiry_number"], name="die_quotati_inquiry_459207_idx"
            ),
        ),
    ]
