# Generated by Django 5.1.1 on 2026-06-19 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die_quotation", "0005_alter_diequotation_deleted_and_more"),
        ("product", "0061_rename_standard_name_alloy_standard_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diequotationdetails",
            name="conversion",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="diequotationdetails",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diequotationdetails",
            name="price_per_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="diequotationdetails",
            name="temper",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="die_quotation_details_temper",
                to="product.temper",
            ),
        ),
    ]
