# Generated by Django 5.1.1 on 2026-06-22 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0025_remove_customer_customer_cu_custome_d3a0b9_idx_and_more"),
        ("product", "0061_rename_standard_name_alloy_standard_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DieProforma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "workorder_no",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "freight_charges",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "advance_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "transport_charges",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "insurance_charges",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "other_charges",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("proforma_date", models.DateField(auto_now=True, db_index=True)),
                ("terms_and_condition", models.TextField(blank=True, null=True)),
                (
                    "delivery_schedule",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "weight_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "proforma_no",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="die_proforma_customer",
                        to="customer.customer",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "die_proforma",
                "permissions": [
                    ("print_die_proforma_copy", "Can print die proforma copy"),
                    ("download_proforma_pdf_copy", "Can download proforma Pdf copy"),
                    (
                        "download_proforma_excel_copy",
                        "Can download proforma Excel copy",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DieProformaDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "customer_reference_no",
                    models.CharField(
                        blank=True, db_index=True, max_length=250, null=True
                    ),
                ),
                ("pieces", models.IntegerField(db_index=True, default=0, null=True)),
                (
                    "net_weight",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "nalco_rate",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "packed_weight",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "dispatch_qty",
                    models.FloatField(db_index=True, default=0.0, null=True),
                ),
                (
                    "alloy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="die_proforma_detail_alloy",
                        to="product.alloy",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "die_proforma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="die_proforma_details_proforma",
                        to="die_proforma.dieproforma",
                    ),
                ),
                (
                    "temper",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="die_proforma_detail_temper",
                        to="product.temper",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "die_proforma_detail",
            },
        ),
    ]
