# Generated by Django 5.1.1 on 2026-06-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die_proforma", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dieproformadetails",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dieproformadetails",
            name="hsn",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="dieproformadetails",
            name="quantity",
            field=models.DecimalField(
                db_index=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="dieproformadetails",
            name="rate",
            field=models.DecimalField(
                db_index=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
