# Generated by Django 5.1.1 on 2026-06-22 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die_proforma", "0002_dieproformadetails_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dieproformadetails",
            name="quantity",
        ),
    ]
