# Generated by Django 5.1.1 on 2026-06-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die_proforma", "0003_remove_dieproformadetails_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="dieproformadetails",
            name="quantity",
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
