# Generated by Django 5.1.1 on 2026-06-22 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die_proforma", "0004_dieproformadetails_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dieproforma",
            name="delivery_schedule",
        ),
        migrations.RemoveField(
            model_name="dieproforma",
            name="weight_range",
        ),
        migrations.RemoveField(
            model_name="dieproforma",
            name="workorder_no",
        ),
        migrations.RemoveField(
            model_name="dieproformadetails",
            name="alloy",
        ),
        migrations.RemoveField(
            model_name="dieproformadetails",
            name="customer_reference_no",
        ),
        migrations.RemoveField(
            model_name="dieproformadetails",
            name="dispatch_qty",
        ),
        migrations.RemoveField(
            model_name="dieproformadetails",
            name="nalco_rate",
        ),
        migrations.RemoveField(
            model_name="dieproformadetails",
            name="net_weight",
        ),
        migrations.RemoveField(
            model_name="dieproformadetails",
            name="packed_weight",
        ),
        migrations.RemoveField(
            model_name="dieproformadetails",
            name="temper",
        ),
    ]
