# Generated by Django 5.1.1 on 2026-06-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die_proforma", "0005_remove_dieproforma_delivery_schedule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dieproforma",
            name="purchase_order_no",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
