# Generated by Django 5.1.1 on 2026-06-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die_proforma", "0006_dieproforma_purchase_order_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="dieproforma",
            name="purchase_order_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
