# Generated by Django 5.1.1 on 2025-09-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgingCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alloy", models.CharField(max_length=100, null=True)),
                ("temper", models.CharField(max_length=100, null=True)),
                ("cycle", models.CharField(max_length=100)),
                ("temp", models.CharField(max_length=50)),
                ("time", models.CharField(max_length=50)),
                ("webster", models.CharField(max_length=50)),
                ("bhn", models.CharField(max_length=50)),
                ("remark", models.TextField()),
            ],
            options={
                "db_table": "aging_cycle",
            },
        ),
    ]
