# Generated by Django 5.1.1 on 2026-03-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aging", "0002_ageingbatch_ageingbatchdetail_ageingtemperaturelog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ageingbatchdetail",
            old_name="cut_length",
            new_name="cut_length_mm",
        ),
        migrations.RenameField(
            model_name="ageingbatchdetail",
            old_name="production",
            new_name="production_no",
        ),
        migrations.RenameField(
            model_name="ageingbatchdetail",
            old_name="die",
            new_name="section_no",
        ),
        migrations.AddField(
            model_name="ageingbatchdetail",
            name="cast_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ageingbatchdetail",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
    ]
