# Generated by Django 5.1.1 on 2026-03-13 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aging", "0003_rename_cut_length_ageingbatchdetail_cut_length_mm_and_more"),
        ("die", "0079_rename_no_of_regrinds_dietool_regrinds"),
    ]

    operations = [
        migrations.AddField(
            model_name="ageingbatchdetail",
            name="die_no",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ageing_batch_die_tool",
                to="die.dietool",
            ),
        ),
    ]
