# Generated by Django 5.1.1 on 2026-06-03 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aging", "0004_ageingbatchdetail_die_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agingcycle",
            name="alloy",
        ),
        migrations.RemoveField(
            model_name="agingcycle",
            name="bhn",
        ),
        migrations.RemoveField(
            model_name="agingcycle",
            name="cycle",
        ),
        migrations.RemoveField(
            model_name="agingcycle",
            name="remark",
        ),
        migrations.RemoveField(
            model_name="agingcycle",
            name="temp",
        ),
        migrations.RemoveField(
            model_name="agingcycle",
            name="temper",
        ),
        migrations.RemoveField(
            model_name="agingcycle",
            name="time",
        ),
        migrations.RemoveField(
            model_name="agingcycle",
            name="webster",
        ),
    ]
