# Generated by Django 5.1.1 on 2026-06-03 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aging", "0005_remove_agingcycle_alloy_remove_agingcycle_bhn_and_more"),
        ("product", "0061_rename_standard_name_alloy_standard_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agingcycle",
            name="alloy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.alloy",
            ),
        ),
        migrations.AddField(
            model_name="agingcycle",
            name="cooling_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Air_Cooling", "Air_Cooling"),
                    ("Fan_Cooling", "Fan_Cooling"),
                    ("Natural_Cooling", "Natural_Cooling"),
                    ("Water_Quench", "Water_Quench"),
                    ("Water_Spray_Cooling", "Water_Spray_Cooling"),
                    ("Forced_Air_Cooling", "Forced_Air_Cooling"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agingcycle",
            name="cycle_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="agingcycle",
            name="cycle_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="agingcycle",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agingcycle",
            name="soaking_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agingcycle",
            name="temper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.temper",
            ),
        ),
        migrations.AddField(
            model_name="agingcycle",
            name="zone1_temp",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="agingcycle",
            name="zone2_temp",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="agingcycle",
            name="zone3_temp",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="agingcycle",
            name="zone4_temp",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
