# Generated by Django 5.1.1 on 2026-06-04 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aging", "0007_agingcycle_created_at_agingcycle_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agingcycle",
            name="soaking_time",
        ),
    ]
