# Generated by Django 5.1.1 on 2026-06-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aging", "0008_remove_agingcycle_soaking_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="agingcycle",
            name="soaking_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
