# Generated by Django 5.1.1 on 2026-06-04 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aging", "0009_agingcycle_soaking_time"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AgingCycle",
        ),
    ]
