# Generated by Django 5.1.1 on 2025-11-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
