# Generated by Django 5.1.1 on 2026-01-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "material",
            "0003_alter_material_created_at_alter_material_created_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
