# Generated by Django 5.1.1 on 2026-03-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("material", "0004_alter_material_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="material",
            options={
                "permissions": [
                    ("download_material_excel_copy", "Can download material Excel"),
                    ("download_material_pdf_copy", "Can download material PDF"),
                ]
            },
        ),
    ]
