# Generated by Django 5.1.1 on 2026-08-04 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0025_remove_customer_customer_cu_custome_d3a0b9_idx_and_more"),
        ("purchase_order", "0006_purchaseorderdetail_item"),
        ("quality_inspection", "0001_initial"),
        ("receipt_notes", "0013_alter_goodsreceiptnotedetail_grn"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualityinspection",
            name="grn",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quality_inspection_grn",
                to="receipt_notes.goodsreceiptnote",
            ),
        ),
        migrations.AddField(
            model_name="qualityinspection",
            name="inspection_no",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="qualityinspection",
            name="purchase_order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quality_inspection_purchase_order",
                to="purchase_order.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="qualityinspection",
            name="vendor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quality_inspection_vendor",
                to="customer.customer",
            ),
        ),
    ]
