# Generated by Django 5.1.1 on 2026-08-04 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quality_inspection", "0002_qualityinspection_grn_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qualityinspection",
            name="accepted_qty",
        ),
        migrations.RemoveField(
            model_name="qualityinspection",
            name="received_qty",
        ),
        migrations.RemoveField(
            model_name="qualityinspection",
            name="rejected_qty",
        ),
    ]
