# Generated by Django 5.1.1 on 2025-09-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlosterMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                ("bloster_no", models.CharField(max_length=100)),
                ("bloster_image", models.CharField(max_length=250, null=True)),
                ("autocard", models.CharField(max_length=250, null=True)),
                ("pdf", models.CharField(max_length=250, null=True)),
            ],
            options={
                "permissions": [
                    ("download_bolster_pdf_copy", "Can download bolster PDF"),
                    ("download_bolster_excel_copy", "Can download bolster Excel"),
                ],
            },
        ),
    ]
