# Generated by Django 5.1.1 on 2026-01-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloster", "0005_alter_blostermaster_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blostermaster",
            name="updated_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
