# Generated by Django 5.1.1 on 2026-03-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloster", "0006_alter_blostermaster_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="blostermaster",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blostermaster",
            name="size",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="blostermaster",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Solid", "Solid"),
                    ("Pocket", "Pocket"),
                    ("Multi_Hole", "Multi_Hole"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="blostermaster",
            name="bloster_image",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
