# Generated by Django 5.1.1 on 2026-03-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloster", "0007_blostermaster_description_blostermaster_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blostermaster",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
