# Generated by Django 5.1.1 on 2026-04-07 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloster", "0010_blostertype"),
    ]

    operations = [
        migrations.AddField(
            model_name="blostermaster",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bloster.blostertype",
            ),
        ),
    ]
