# Generated by Django 5.1.1 on 2026-04-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloster", "0011_blostermaster_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="blostermaster",
            name="diameter_mm",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blostermaster",
            name="thickness_mm",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
