# Generated by Django 5.1.1 on 2026-03-03 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("online_inspection", "0002_alter_onlineinspection_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="onlineinspection",
            options={
                "permissions": [
                    (
                        "print_online_inspection_pdf_copy",
                        "Can print online inspection PDF",
                    ),
                    (
                        "print_online_inspection_excel_copy",
                        "Can print online inspection Excel",
                    ),
                    (
                        "print_online_inspection_report_pdf_copy",
                        "Can print online inspection report PDF",
                    ),
                ]
            },
        ),
    ]
