# Generated by Django 5.1.1 on 2025-11-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manual_weight_entry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manualweightentry",
            name="weight_for",
            field=models.CharField(
                choices=[
                    ("gross weight", "Gross weight"),
                    ("tare weight", "Tare weight"),
                ],
                default="gross_weight",
                max_length=50,
            ),
        ),
    ]
