# Generated by Django 5.1.1 on 2026-03-16 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manual_weight_entry", "0003_alter_manualweightentry_seller"),
        ("vehicle_master", "0007_alter_vehiclemaster_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manualweightentry",
            options={
                "permissions": [
                    (
                        "download_manual_weight_entry_excel_copy",
                        "Can download manual weight entry Excel",
                    ),
                    (
                        "download_manual_weight_entry_pdf_copy",
                        "Can download manual weight entry PDF",
                    ),
                ]
            },
        ),
        migrations.AlterField(
            model_name="manualweightentry",
            name="capture_photo",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="manualweightentry",
            name="vehicle_no",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manual_weight_entry_vehicle_no",
                to="vehicle_master.vehiclemaster",
            ),
        ),
    ]
