# Generated by Django 5.1.1 on 2026-03-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manual_weight_entry", "0005_alter_manualweightentry_material_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manualweightentry",
            name="capture_photo",
        ),
    ]
