# Generated by Django 5.1.1 on 2026-03-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manual_weight_entry", "0006_remove_manualweightentry_capture_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manualweightentry",
            name="weight",
        ),
        migrations.RemoveField(
            model_name="manualweightentry",
            name="weight_automatic",
        ),
        migrations.RemoveField(
            model_name="manualweightentry",
            name="weight_for",
        ),
        migrations.AddField(
            model_name="manualweightentry",
            name="capture_photo_manual_1",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="manualweightentry",
            name="capture_photo_manual_2",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
