# Generated by Django 5.1.1 on 2026-06-10 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create_dross_entry", "0001_initial"),
        ("furnace_master", "0001_initial"),
        ("shift", "0002_remove_shiftmaster_deleted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="drossdetail",
            name="dross_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WHITE_DROSS", "White Dross"),
                    ("BLACK_DROSS", "Black Dross"),
                    ("SKIMMING_DROSS", "Skimming Dross"),
                    ("FURNACE_DROSS", "Furnace Dross"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="DrossEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "shift_name_snapshot",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("shift_start_snapshot", models.TimeField(blank=True, null=True)),
                ("shift_end_snapshot", models.TimeField(blank=True, null=True)),
                (
                    "dross_entry_no",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("heat_no", models.CharField(blank=True, max_length=50, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "furnace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="furnace_master.furnacemaster",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_shift",
                        to="shift.shiftmaster",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    (
                        "download_dross_entry_excel_copy",
                        "Can download dross entry Excel",
                    ),
                    ("download_dross_entry_pdf_copy", "Can download dross entry PDF"),
                ],
            },
        ),
        migrations.DeleteModel(
            name="HeaderInformation",
        ),
    ]
