# Generated by Django 5.1.1 on 2026-06-23 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create_dross_entry", "0002_alter_drossdetail_dross_type_drossentry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="drossdetail",
            name="dross_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dross_details",
                to="create_dross_entry.drossentry",
            ),
        ),
    ]
