# Generated by Django 5.2.5 on 2025-12-08 11:04

from django.db import migrations


def clear_party_name_data(apps, schema_editor):
    """
    Clear existing party_name data to allow conversion from CharField to ForeignKey
    """
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "UPDATE vehicle_master SET party_name = NULL WHERE party_name IS NOT NULL;"
        )
    else:
        VehicleMaster = apps.get_model("vehicle_master", "VehicleMaster")
        VehicleMaster.objects.all().update(party_name=None)


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle_master", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(clear_party_name_data, migrations.RunPython.noop),
    ]
