# Generated by Django 5.2.5 on 2025-12-08 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transporter", "0006_alter_transporter_opening_balance"),
        ("vehicle_master", "0002_clear_party_name_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclemaster",
            name="party_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicle_master_party_name",
                to="transporter.transporter",
            ),
        ),
    ]
