# Generated by Django 5.1.1 on 2026-03-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle_master", "0005_alter_vehiclemaster_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclemaster",
            name="vehicle_no",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
