# Generated by Django 5.1.1 on 2026-03-11 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle_master", "0006_alter_vehiclemaster_vehicle_no"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehiclemaster",
            options={
                "permissions": [
                    (
                        "download_vehicle_master_excel_copy",
                        "Can download vehicle master Excel",
                    ),
                    (
                        "download_vehicle_master_pdf_copy",
                        "Can download vehicle master PDF",
                    ),
                ]
            },
        ),
    ]
