# Generated by Django 5.1.1 on 2026-03-23 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle_master", "0008_vehiclemaster_vehicle_type"),
        ("vehicle_type", "0004_alter_vehicletype_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclemaster",
            name="vehicle_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicle_master_vehicle_type",
                to="vehicle_type.vehicletype",
            ),
        ),
    ]
