# Generated by Django 5.1.1 on 2026-05-07 03:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transporter", "0011_alter_transporter_options"),
        ("vehicle_master", "0009_alter_vehiclemaster_vehicle_type"),
        ("vehicle_type", "0004_alter_vehicletype_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclemaster",
            name="vehicle_no",
            field=models.CharField(
                blank=True, db_index=True, max_length=30, null=True, unique=True
            ),
        ),
        migrations.AddIndex(
            model_name="vehiclemaster",
            index=models.Index(
                fields=["deleted", "-id"], name="vehicle_mas_deleted_2633de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehiclemaster",
            index=models.Index(
                fields=["deleted", "party_name"], name="vehicle_mas_deleted_ab63d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehiclemaster",
            index=models.Index(
                fields=["deleted", "vehicle_type"],
                name="vehicle_mas_deleted_b80caf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vehiclemaster",
            index=models.Index(
                fields=["vehicle_no"], name="vehicle_mas_vehicle_93d5e2_idx"
            ),
        ),
    ]
