# Generated by Django 5.1.1 on 2025-12-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bulk_import", "0002_importjob_importrecord"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="importrecord",
            new_name="bulk_import_import__d37387_idx",
            old_name="bulk_import_import__bc02da_idx",
        ),
        migrations.RenameIndex(
            model_name="importrecord",
            new_name="bulk_import_import__e74795_idx",
            old_name="bulk_import_import__1d4b6c_idx",
        ),
        migrations.AlterModelTable(
            name="importrecord",
            table=None,
        ),
    ]
