# Generated by Django 5.1.1 on 2026-02-04 07:11

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bulk_import",
            "0003_rename_bulk_import_import__bc02da_idx_bulk_import_import__d37387_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="importerrorrow",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 8, 11, 896565, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="importerrorrow",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 8, 17, 973413, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="importjob",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 8, 49, 606629, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="importjob",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 8, 53, 486379, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="importlog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 8, 55, 605532, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="importlog",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 8, 57, 334260, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="importrecord",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 8, 59, 96597, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="importrecord",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 9, 1, 32468, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
