# Generated by Django 5.1.1 on 2026-02-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bulk_import", "0004_alter_importerrorrow_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importerrorrow",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="importlog",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="importrecord",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
