# Generated by Django 5.1.1 on 2026-01-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle_type", "0002_alter_vehicletype_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicletype",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
