# Generated by Django 5.1.1 on 2026-03-10 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle_type", "0003_alter_vehicletype_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicletype",
            options={
                "permissions": [
                    (
                        "download_vehicle_type_excel_copy",
                        "Can download vehicle type Excel",
                    ),
                    ("download_vehicle_type_pdf_copy", "Can download vehicle type PDF"),
                ]
            },
        ),
    ]
