# Generated by Django 5.1.1 on 2026-02-04 07:11

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 10, 54, 956678, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 10, 56, 409755, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 10, 57, 819858, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(
                    2026, 2, 4, 7, 10, 59, 224853, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
