# Generated by Django 5.1.1 on 2026-03-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_updated_at_alter_userprofile_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, db_index=True, max_length=201),
        ),
    ]
