# Generated by Django 5.1.1 on 2026-03-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=201, null=True
            ),
        ),
    ]
