# Generated by Django 5.1.1 on 2026-03-06 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scrap_transfer", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="scraptransfer",
            new_name="scrap_trans_transfe_68e813_idx",
            old_name="scrap_trans_transfer_8a1b2c_idx",
        ),
        migrations.RenameIndex(
            model_name="scraptransfer",
            new_name="scrap_trans_status_d0ea82_idx",
            old_name="scrap_trans_status_9d2e3f_idx",
        ),
        migrations.RenameIndex(
            model_name="scraptransfer",
            new_name="scrap_trans_transfe_f0c847_idx",
            old_name="scrap_trans_transfer_4e5f6g_idx",
        ),
        migrations.RenameIndex(
            model_name="scraptransfer",
            new_name="scrap_trans_from_st_e8df4f_idx",
            old_name="scrap_trans_from_st_7h8i9j_idx",
        ),
        migrations.RenameIndex(
            model_name="scraptransfer",
            new_name="scrap_trans_to_plan_3c2218_idx",
            old_name="scrap_trans_to_pla_0k1l2m_idx",
        ),
        migrations.RenameIndex(
            model_name="scraptransfer",
            new_name="scrap_trans_to_stor_deffc8_idx",
            old_name="scrap_trans_to_sto_3n4o5p_idx",
        ),
        migrations.RenameIndex(
            model_name="scraptransfer",
            new_name="scrap_trans_is_arch_514660_idx",
            old_name="scrap_trans_is_arch_6q7r8s_idx",
        ),
        migrations.RenameIndex(
            model_name="scraptransfer",
            new_name="scrap_trans_status_5124e1_idx",
            old_name="scrap_trans_status_9t0u1v_idx",
        ),
        migrations.RenameIndex(
            model_name="scraptransferitem",
            new_name="scrap_trans_scrap_t_890e04_idx",
            old_name="scrap_trans_scrap_t_2w3x4y_idx",
        ),
        migrations.RenameIndex(
            model_name="scraptransferitem",
            new_name="scrap_trans_scrap_i_0be98f_idx",
            old_name="scrap_trans_scrap_i_5z6a7b_idx",
        ),
    ]
