# Generated by Django 5.1.1 on 2026-06-19 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material_request", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialrequestdetail",
            name="material_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_request_detail",
                to="material_request.materialrequest",
            ),
        ),
    ]
