# Generated by Django 5.1.1 on 2025-09-25 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConversionRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                (
                    "conversion",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                ("remarks", models.TextField(null=True)),
            ],
            options={
                "db_table": "conversion_rate",
                "permissions": [
                    (
                        "download_conversion_rate_pdf_copy",
                        "Can download conversion rate PDF",
                    ),
                    (
                        "download_conversion_rate_excel_copy",
                        "Can download conversion rate Excel",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Die",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                ("die_number", models.CharField(db_index=True, max_length=255)),
                (
                    "dimension1",
                    models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
                ),
                (
                    "dimension2",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "dimension3",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "dimension4",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "min_wt_kg_p_mt",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                ("wt_kg_p_mt", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "max_wt_kg_p_mt",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                ("die_diagram", models.CharField(max_length=250, null=True)),
                ("die_detail_diagram", models.CharField(max_length=250, null=True)),
                (
                    "customer_approved_diagram",
                    models.CharField(max_length=250, null=True),
                ),
                ("autocad_drawing", models.CharField(max_length=250, null=True)),
                ("die_manufacturing", models.CharField(max_length=255, null=True)),
                ("die_sop", models.CharField(max_length=250, null=True)),
                ("total_running_qty", models.FloatField(default=0.0, null=True)),
                (
                    "total_running_ton",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "customer_reference_number",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "die_type",
                    models.CharField(
                        choices=[
                            ("Solid", "Solid"),
                            ("Hollow", "Hollow"),
                            ("Semi Hollow", "Semi Hollow"),
                        ],
                        default="Solid",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "die",
                "permissions": [
                    ("print_profile_pdf_copy", "Can print profile"),
                    (
                        "print_profile_workorder_report_pdf_copy",
                        "Can print profile workorder report",
                    ),
                    ("download_profile_pdf_copy", "Can download profile PDF"),
                    ("download_profile_excel_copy", "Can download profile Excel"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DieCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=50)),
                ("deleted", models.IntegerField(default=0)),
            ],
            options={
                "permissions": [
                    (
                        "download_profile_category_pdf_copy",
                        "Can download profile category PDF",
                    ),
                    (
                        "download_profile_category_excel_copy",
                        "Can download profile category Excel",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DieGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=50)),
                ("deleted", models.IntegerField(default=0)),
            ],
            options={
                "permissions": [
                    (
                        "download_profile_group_pdf_copy",
                        "Can download profile group PDF",
                    ),
                    (
                        "download_profile_group_excel_copy",
                        "Can download profile group Excel",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DiePress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=50)),
                ("deleted", models.IntegerField(default=0)),
            ],
            options={
                "permissions": [
                    (
                        "download_profile_press_pdf_copy",
                        "Can download profile press PDF",
                    ),
                    (
                        "download_profile_press_excel_copy",
                        "Can download profile press Excel",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DieSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                ("deleted", models.IntegerField(default=0)),
                (
                    "die_height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "die_width",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("download_profile_size_pdf_copy", "Can download profile size PDF"),
                    (
                        "download_profile_size_excel_copy",
                        "Can download profile size Excel",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DieSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=50)),
                ("deleted", models.IntegerField(default=0)),
            ],
            options={
                "permissions": [
                    (
                        "download_profile_sub_category_pdf_copy",
                        "Can download profile sub category PDF",
                    ),
                    (
                        "download_profile_sub_category_excel_copy",
                        "Can download profile sub category Excel",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DieTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                ("current_kg", models.CharField(max_length=150, null=True)),
                ("tool_number", models.CharField(max_length=25)),
                (
                    "die_cavity",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(10)],
                    ),
                ),
                (
                    "developer_ref_no",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("received_date", models.DateField(null=True)),
                ("order_date", models.DateField(null=True)),
                (
                    "total_running_qty",
                    models.FloatField(default=0.0, help_text="Total Kilometer"),
                ),
                (
                    "total_running_ton",
                    models.FloatField(default=0.0, help_text="Total Ton"),
                ),
                ("purchase_price", models.FloatField(default=0.0)),
                (
                    "run_under_deviation",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("inactive", "inactive"),
                            ("under development", "under development"),
                        ],
                        default="under development",
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "run_under_deviation_inactive",
                    models.CharField(
                        choices=[
                            ("die_broken", "die_broken"),
                            ("die_absolute", "die_absolute"),
                            ("die_shift", "die_shift"),
                            ("other", "other"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "run_under_deviation_reason",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "ownership",
                    models.CharField(
                        choices=[("hepl", "hepl"), ("customer", "customer")],
                        max_length=150,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("remarks", models.CharField(blank=True, max_length=170, null=True)),
                ("drawing_no", models.CharField(max_length=150, null=True)),
                ("rac_no", models.CharField(max_length=50, null=True)),
                ("row_no", models.CharField(max_length=50, null=True)),
                ("column_no", models.CharField(max_length=50, null=True)),
                ("die_location", models.CharField(max_length=50, null=True)),
                ("die_option", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "diameter",
                    models.FloatField(
                        blank=True,
                        help_text="Diameter value for Insert option.",
                        null=True,
                    ),
                ),
                (
                    "thickness",
                    models.FloatField(
                        blank=True,
                        help_text="Thickness value for Insert option.",
                        null=True,
                    ),
                ),
                (
                    "backer_number",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
            ],
            options={
                "db_table": "die_tool",
                "permissions": [
                    ("download_profile_tool_pdf_copy", "Can download profile tool PDF"),
                    (
                        "download_profile_tool_excel_copy",
                        "Can download profile tool Excel",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DieType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_id", models.IntegerField(default=0)),
                ("approve", models.BooleanField(default=False)),
                ("reject", models.BooleanField(default=False)),
                ("approve_remarks", models.TextField(null=True)),
                ("done_flag", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("approved_by", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("deleted", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
