# Generated by Django 5.1.1 on 2025-12-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0005_conversionrate_created_at_conversionrate_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diepress",
            name="billet_diameter_max",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diepress",
            name="billet_diameter_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diepress",
            name="billet_length_max",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diepress",
            name="billet_length_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diepress",
            name="billet_weight",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diepress",
            name="capacity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diepress",
            name="code",
            field=models.CharField(default="NA", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="diepress",
            name="extrusion_length_max",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diepress",
            name="extrusion_length_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="diepress",
            name="name",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
    ]
