# Generated by Django 5.1.1 on 2025-12-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0006_diepress_billet_diameter_max_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="die",
            name="cutting_dimensions",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="die",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
