# Generated by Django 5.2.5 on 2025-12-17 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0007_die_cutting_dimensions_die_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diepress",
            name="billet_diameter_max",
        ),
        migrations.RemoveField(
            model_name="diepress",
            name="billet_diameter_min",
        ),
    ]
