# Generated by Django 5.2.5 on 2025-12-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0008_remove_diepress_billet_diameter_max_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diepress",
            name="billet_diameter",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
