# Generated by Django 5.2.5 on 2025-12-17 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0009_diepress_billet_diameter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="die",
            name="total_running_qty",
        ),
        migrations.RemoveField(
            model_name="die",
            name="total_running_ton",
        ),
        migrations.CreateModel(
            name="SectionBallonDimensions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ballon_no", models.IntegerField(blank=True, null=True, unique=True)),
                (
                    "dim_type",
                    models.CharField(blank=True, max_length=60, null=True, unique=True),
                ),
                ("nominal_value", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "tolerance_plus",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "tolerance_minus",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_inspection", models.BooleanField(default=True)),
                ("is_critical", models.BooleanField(default=False)),
                (
                    "pos_x",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "pos_y",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="section_ballon_dimensions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="section_ballon_dimensions_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ballon_dimensions",
                        to="die.die",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="section_ballon_dimensions_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "section_ballon_dimensions",
            },
        ),
    ]
