# Generated by Django 5.2.5 on 2025-12-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0010_remove_die_total_running_qty_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dietool",
            name="total_running_qty",
        ),
        migrations.AlterField(
            model_name="sectionballondimensions",
            name="dim_type",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
