# Generated by Django 5.2.5 on 2025-12-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0011_remove_dietool_total_running_qty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionballondimensions",
            name="ballon_no",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
