# Generated by Django 5.2.5 on 2025-12-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0012_alter_sectionballondimensions_ballon_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="die",
            name="autocad_drawing",
            field=models.FileField(
                blank=True, null=True, upload_to="die/autocad_drawing/"
            ),
        ),
        migrations.AlterField(
            model_name="die",
            name="customer_approved_diagram",
            field=models.FileField(
                blank=True, null=True, upload_to="die/customer_approved_diagram/"
            ),
        ),
        migrations.AlterField(
            model_name="die",
            name="die_detail_diagram",
            field=models.FileField(
                blank=True, null=True, upload_to="die/die_detail_diagram/"
            ),
        ),
        migrations.AlterField(
            model_name="die",
            name="die_diagram",
            field=models.FileField(blank=True, null=True, upload_to="die/die_diagram/"),
        ),
        migrations.AlterField(
            model_name="die",
            name="die_manufacturing",
            field=models.FileField(
                blank=True, null=True, upload_to="die/die_manufacturing/"
            ),
        ),
        migrations.AlterField(
            model_name="die",
            name="die_sop",
            field=models.FileField(blank=True, null=True, upload_to="die/die_sop/"),
        ),
    ]
