# Generated by Django 5.2.5 on 2025-12-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0013_alter_die_autocad_drawing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="die",
            name="autocad_drawing",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="die",
            name="customer_approved_diagram",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="die",
            name="die_detail_diagram",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="die",
            name="die_diagram",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="die",
            name="die_manufacturing",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="die",
            name="die_sop",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
