# Generated by Django 5.2.5 on 2025-12-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0014_alter_die_autocad_drawing_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectionballondimensions",
            name="section",
        ),
    ]
