# Generated by Django 5.2.5 on 2025-12-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0016_sectionballondimensions_section"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectionballondimensions",
            name="nominal_value",
        ),
        migrations.RemoveField(
            model_name="sectionballondimensions",
            name="pos_x",
        ),
        migrations.RemoveField(
            model_name="sectionballondimensions",
            name="pos_y",
        ),
        migrations.RemoveField(
            model_name="sectionballondimensions",
            name="tolerance_minus",
        ),
        migrations.RemoveField(
            model_name="sectionballondimensions",
            name="tolerance_plus",
        ),
    ]
