# Generated by Django 5.2.5 on 2025-12-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0017_remove_sectionballondimensions_nominal_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionballondimensions",
            name="nominal_value",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="sectionballondimensions",
            name="pos_x",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="sectionballondimensions",
            name="pos_y",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="sectionballondimensions",
            name="tolerance_minus",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="sectionballondimensions",
            name="tolerance_plus",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
    ]
