# Generated by Django 5.2.5 on 2025-12-18 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0018_sectionballondimensions_nominal_value_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectionballondimensions",
            name="ballon_no",
        ),
    ]
