# Generated by Django 5.2.5 on 2025-12-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0019_remove_sectionballondimensions_ballon_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionballondimensions",
            name="balloon_no",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
