# Generated by Django 5.2.5 on 2025-12-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0020_sectionballondimensions_balloon_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectionballondimensions",
            name="section",
        ),
    ]
