# Generated by Django 5.2.5 on 2025-12-18 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0023_remove_sectionballondimensions_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionballondimensions",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ballon_drawing_dimensions",
                to="die.die",
            ),
        ),
    ]
