# Generated by Django 5.1.1 on 2025-12-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0024_sectionballondimensions_section"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectionballondimensions",
            name="section",
        ),
    ]
