# Generated by Django 5.1.1 on 2025-12-19 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0032_sectionballondimensions_section"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diepress",
            name="billet_diameter",
        ),
    ]
