# Generated by Django 5.1.1 on 2025-12-19 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0034_diepress_billet_diameter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diepress",
            name="billet_diameter",
        ),
        migrations.RemoveField(
            model_name="diepress",
            name="billet_weight",
        ),
    ]
