# Generated by Django 5.1.1 on 2025-12-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0035_remove_diepress_billet_diameter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diepress",
            name="billet_diameter",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diepress",
            name="billet_weight",
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
