# Generated by Django 5.1.1 on 2025-12-19 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0036_diepress_billet_diameter_diepress_billet_weight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diepress",
            name="billet_weight",
        ),
    ]
