# Generated by Django 5.1.1 on 2025-12-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0037_remove_diepress_billet_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="diepress",
            name="billet_weight",
            field=models.FloatField(null=True),
        ),
    ]
