# Generated by Django 5.1.1 on 2025-12-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0038_diepress_billet_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dietool",
            name="ownership",
            field=models.CharField(
                choices=[("aluka", "aluka"), ("customer", "customer")],
                max_length=150,
                null=True,
            ),
        ),
    ]
