# Generated by Django 5.1.1 on 2025-12-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0039_alter_dietool_ownership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diepress",
            name="billet_weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="diepress",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
