# Generated by Django 5.1.1 on 2025-12-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0040_alter_diepress_billet_weight_alter_diepress_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diegroup",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
