# Generated by Django 5.1.1 on 2025-12-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0041_alter_diegroup_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diecategory",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
