# Generated by Django 5.1.1 on 2026-01-06 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloster", "0003_remove_blostermaster_approve_and_more"),
        ("customer", "0010_alter_customer_company_type"),
        ("die", "0043_alter_diesubcategory_name"),
        ("product", "0015_alter_temper_name"),
        ("vendor", "0002_remove_vendor_approve_remove_vendor_approve_remarks_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversionrate",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="die",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="diecategory",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="diegroup",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="diepress",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="diesize",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="diesubcategory",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="dietool",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="dietype",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="sectionballondimensions",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="conversionrate",
            index=models.Index(
                fields=["-created_at", "deleted"], name="conversion__created_ef3af5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversionrate",
            index=models.Index(
                fields=["customer", "deleted"], name="conversion__custome_58b8a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversionrate",
            index=models.Index(
                fields=["die", "deleted"], name="conversion__die_id_e81ecf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="die",
            index=models.Index(
                fields=["-created_at", "deleted"], name="die_created_374e97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="die",
            index=models.Index(
                fields=["die_number", "deleted"], name="die_die_num_a7229b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="die",
            index=models.Index(
                fields=["die_type", "deleted"], name="die_die_typ_e6ea02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diecategory",
            index=models.Index(
                fields=["-created_at", "deleted"], name="die_diecate_created_4afc83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diegroup",
            index=models.Index(
                fields=["-created_at", "deleted"], name="die_diegrou_created_3a5de1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diepress",
            index=models.Index(
                fields=["-created_at", "deleted"], name="die_diepres_created_9cbef1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diepress",
            index=models.Index(
                fields=["name", "deleted"], name="die_diepres_name_5ce510_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diesize",
            index=models.Index(
                fields=["-created_at", "deleted"], name="die_diesize_created_9071a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diesubcategory",
            index=models.Index(
                fields=["-created_at", "deleted"], name="die_diesubc_created_20c7a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dietool",
            index=models.Index(
                fields=["-created_at", "deleted"], name="die_tool_created_b30fb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dietool",
            index=models.Index(
                fields=["die", "deleted"], name="die_tool_die_id_13a713_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dietool",
            index=models.Index(
                fields=["tool_number", "deleted"], name="die_tool_tool_nu_8fc38b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sectionballondimensions",
            index=models.Index(
                fields=["section", "deleted"], name="section_bal_section_77d93f_idx"
            ),
        ),
    ]
