# Generated by Django 5.1.1 on 2026-01-02 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0011_rename_account_customer_amount_and_more"),
        ("die", "0043_alter_diesubcategory_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dietool",
            name="developer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dietool_customer",
                to="customer.customer",
            ),
        ),
    ]
