# Generated by Django 5.1.1 on 2026-01-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0044_alter_conversionrate_deleted_alter_die_deleted_and_more"),
        ("die", "0044_alter_dietool_developer"),
    ]

    operations = []
