# Generated by Django 5.1.1 on 2026-01-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0045_merge_20260108_1600"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dietool",
            name="ownership",
            field=models.CharField(
                choices=[("own", "own"), ("customer", "customer")],
                max_length=150,
                null=True,
            ),
        ),
    ]
