# Generated by Django 5.1.1 on 2026-01-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0045_merge_20260108_1600"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diepress",
            name="billet_diameter",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="diepress",
            name="billet_length_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="diepress",
            name="billet_length_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="diepress",
            name="capacity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="diepress",
            name="extrusion_length_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="diepress",
            name="extrusion_length_min",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
