# Generated by Django 5.1.1 on 2026-01-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0046_alter_diepress_billet_diameter_and_more"),
        ("die", "0046_alter_dietool_ownership"),
    ]

    operations = []
