# Generated by Django 5.1.1 on 2026-01-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0047_merge_20260122_1513"),
    ]

    operations = [
        migrations.AddField(
            model_name="diepress",
            name="billet_wt_factor",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
