# Generated by Django 5.1.1 on 2026-02-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0049_alter_diecategory_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversionrate",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
