# Generated by Django 5.2.4 on 2026-02-10 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0021_alter_bankingdetails_updated_at_and_more"),
        ("die", "0050_alter_conversionrate_updated_at"),
        ("product", "0044_alter_temper_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="conversionrate",
            name="conversion__created_ef3af5_idx",
        ),
        migrations.AddIndex(
            model_name="conversionrate",
            index=models.Index(
                fields=["created_at", "deleted"], name="conversion__created_2c372c_idx"
            ),
        ),
    ]
