# Generated by Django 5.1.1 on 2026-02-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0051_fix_conversion_rate_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversionrate",
            name="conversion",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
