# Generated by Django 5.1.1 on 2026-02-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0051_fix_conversion_rate_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="die",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
