# Generated by Django 5.1.1 on 2026-02-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0052_alter_die_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionballondimensions",
            name="instrument_for_inspection",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
