# Generated by Django 5.1.1 on 2026-02-13 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0053_sectionballondimensions_instrument_for_inspection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectionballondimensions",
            name="instrument_for_inspection",
        ),
    ]
