# Generated by Django 5.1.1 on 2026-02-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0052_alter_conversionrate_conversion"),
        ("die", "0055_sectionballondimensions_instrument_used_for_inspection"),
    ]

    operations = []
