# Generated by Django 5.1.1 on 2026-02-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0056_merge_20260213_1508"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionballondimensions",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
