# Generated by Django 5.1.1 on 2026-02-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0057_alter_sectionballondimensions_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="die",
            name="joint_llh_mm",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="die",
            name="joint_rhs_mm",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="die",
            name="stretching_machining_end_loss_mm",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="die",
            name="tail_and_loss_mm",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="die",
            name="total_process_loss_kg",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="die",
            name="total_process_loss_meter",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="die",
            name="total_process_loss_mm",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="die",
            name="wt_kg_p_mt",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0, max_digits=10, null=True
            ),
        ),
    ]
