# Generated by Django 5.1.1 on 2026-02-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0058_die_joint_llh_mm_die_joint_rhs_mm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="die",
            name="total_process_loss_kg",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0, max_digits=10, null=True
            ),
        ),
    ]
