# Generated by Django 5.1.1 on 2026-02-26 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0059_alter_die_total_process_loss_kg"),
    ]

    operations = [
        migrations.RenameField(
            model_name="die",
            old_name="tail_and_loss_mm",
            new_name="tail_end_loss_mm",
        ),
    ]
