# Generated by Django 5.1.1 on 2026-03-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0060_rename_tail_and_loss_mm_die_tail_end_loss_mm"),
    ]

    operations = [
        migrations.AddField(
            model_name="diegroup",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
