# Generated by Django 5.1.1 on 2026-03-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0061_diegroup_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="diecategory",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diesubcategory",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
