# Generated by Django 5.1.1 on 2026-03-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0062_diecategory_description_diesubcategory_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="diepress",
            name="container_area",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="diepress",
            name="container_diameter",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
