# Generated by Django 5.1.1 on 2026-03-09 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0063_diepress_container_area_diepress_container_diameter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="die",
            old_name="joint_llh_mm",
            new_name="back_end_process_loss_mm",
        ),
        migrations.RenameField(
            model_name="die",
            old_name="joint_rhs_mm",
            new_name="front_end_process_loss_mm",
        ),
        migrations.RenameField(
            model_name="die",
            old_name="stretching_machining_end_loss_mm",
            new_name="stretching_head_loss_mm",
        ),
        migrations.RenameField(
            model_name="die",
            old_name="tail_end_loss_mm",
            new_name="stretching_tail_loss_mm",
        ),
    ]
