# Generated by Django 5.1.1 on 2026-03-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0064_rename_joint_llh_mm_die_back_end_process_loss_mm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="die",
            name="area",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="die",
            name="cavity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="die",
            name="ccd_mm",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="die",
            name="container_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="die",
            name="perimeter_outer",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="die",
            name="process_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="die",
            name="reference_drawing_number",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="die",
            name="revision",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="die",
            name="revision_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
