# Generated by Django 5.1.1 on 2026-03-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0065_die_area_die_cavity_die_ccd_mm_die_container_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="die",
            name="extrusion_ratio",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
