# Generated by Django 5.1.1 on 2026-03-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0066_die_extrusion_ratio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionballondimensions",
            name="nominal_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
