# Generated by Django 5.1.1 on 2026-03-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0067_alter_sectionballondimensions_nominal_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionballondimensions",
            name="max_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sectionballondimensions",
            name="min_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sectionballondimensions",
            name="pos_x",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sectionballondimensions",
            name="pos_y",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sectionballondimensions",
            name="tolerance_minus",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sectionballondimensions",
            name="tolerance_plus",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
