# Generated by Django 4.2.8 on 2026-03-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloster", "0008_alter_blostermaster_size"),
        ("die", "0068_alter_sectionballondimensions_max_value_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dietool",
            name="eligible_bloster",
        ),
        migrations.AddField(
            model_name="dietool",
            name="eligible_bloster",
            field=models.ManyToManyField(
                blank=True, related_name="dietool_bloster", to="bloster.blostermaster"
            ),
        ),
    ]
