# Generated by Django 5.1.1 on 2026-03-10 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0069_remove_dietool_eligible_bloster_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dietool",
            name="correction_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dietool",
            name="die_nitriding_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dietool",
            name="die_oblique_number",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="dietool",
            name="drawing_weight",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="dietool",
            name="first_trial_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dietool",
            name="last_polishing_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dietool",
            name="no_of_regrinds",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dietool",
            name="scrap_approved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dietool_scrap_approved_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dietool",
            name="scrap_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dietool",
            name="trial_result",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ok", "ok"),
                    ("correction", "correction"),
                    ("failed", "failed"),
                ],
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dietool",
            name="weight_diff",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dietool",
            name="run_under_deviation",
            field=models.CharField(
                choices=[
                    ("active", "active"),
                    ("inactive", "inactive"),
                    ("under development", "under development"),
                    ("scrapped", "scrapped"),
                    ("repair", "repair"),
                ],
                default="under development",
                max_length=25,
                null=True,
            ),
        ),
    ]
