# Generated by Django 5.1.1 on 2026-03-10 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0070_dietool_correction_history_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dietool",
            old_name="run_under_deviation",
            new_name="tool_status",
        ),
        migrations.RemoveField(
            model_name="dietool",
            name="current_kg",
        ),
    ]
