# Generated by Django 5.1.1 on 2026-03-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0071_rename_run_under_deviation_dietool_tool_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietool",
            name="actual_weight",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
