# Generated by Django 5.1.1 on 2026-03-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0072_dietool_actual_weight"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dietool",
            old_name="total_running_ton",
            new_name="total_running_mt",
        ),
    ]
