# Generated by Django 5.1.1 on 2026-03-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0073_rename_total_running_ton_dietool_total_running_mt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dietool",
            name="purchase_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
