# Generated by Django 5.1.1 on 2026-03-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0074_alter_dietool_purchase_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dietool",
            old_name="actual_weight",
            new_name="actual_kg",
        ),
        migrations.RenameField(
            model_name="dietool",
            old_name="drawing_weight",
            new_name="drawing_kg",
        ),
    ]
