# Generated by Django 5.1.1 on 2026-03-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0075_rename_actual_weight_dietool_actual_kg_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dietool",
            old_name="run_under_deviation_inactive",
            new_name="tool_status_inactive",
        ),
        migrations.RenameField(
            model_name="dietool",
            old_name="run_under_deviation_reason",
            new_name="tool_status_reason",
        ),
        migrations.AddField(
            model_name="dietool",
            name="max_die_life",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="dietool",
            name="remaining_life",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dietool",
            name="total_running_mt",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
