# Generated by Django 5.1.1 on 2026-03-10 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "die",
            "0076_rename_run_under_deviation_inactive_dietool_tool_status_inactive_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dietool",
            unique_together={("rac_no", "row_no", "column_no")},
        ),
    ]
