# Generated by Django 5.1.1 on 2026-03-10 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0077_alter_dietool_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dietool",
            old_name="die_nitriding_date",
            new_name="nitriding_date",
        ),
    ]
