# Generated by Django 4.2.8 on 2026-03-10 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0078_rename_die_nitriding_date_dietool_nitriding_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dietool",
            old_name="no_of_regrinds",
            new_name="regrinds",
        ),
    ]
