# Generated by Django 5.1.1 on 2026-04-08 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0025_remove_customer_customer_cu_custome_d3a0b9_idx_and_more"),
        ("die", "0080_alter_die_autocad_drawing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="die",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dies",
                to="customer.customer",
            ),
        ),
        migrations.AddField(
            model_name="die",
            name="ownership_type",
            field=models.CharField(
                choices=[
                    ("Exclusive", "Exclusive"),
                    ("Non_Exclusive", "Non_Exclusive"),
                ],
                default="Non_Exclusive",
                max_length=20,
            ),
        ),
    ]
