# Generated by Django 5.1.1 on 2026-04-08 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0081_die_customer_die_ownership_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="die",
            name="cavity",
        ),
    ]
