# Generated by Django 5.1.1 on 2026-04-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0082_remove_die_cavity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="die",
            name="ownership_type",
            field=models.CharField(
                choices=[
                    ("exclusive", "exclusive"),
                    ("non_exclusive", "non_exclusive"),
                ],
                default="non_exclusive",
                max_length=20,
            ),
        ),
    ]
