# Generated by Django 5.1.1 on 2026-04-09 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0083_alter_die_ownership_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="conversionrate",
            name="conversion__custome_58b8a2_idx",
        ),
        migrations.RemoveIndex(
            model_name="conversionrate",
            name="conversion__die_id_e81ecf_idx",
        ),
        migrations.RemoveIndex(
            model_name="conversionrate",
            name="conversion__created_2c372c_idx",
        ),
        migrations.RemoveField(
            model_name="conversionrate",
            name="alloy",
        ),
        migrations.RemoveField(
            model_name="conversionrate",
            name="conversion",
        ),
        migrations.RemoveField(
            model_name="conversionrate",
            name="die",
        ),
        migrations.RemoveField(
            model_name="conversionrate",
            name="remarks",
        ),
        migrations.RemoveField(
            model_name="conversionrate",
            name="temper",
        ),
        migrations.AlterField(
            model_name="conversionrate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="conversionrate",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="conversionrate",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="conversionrate",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
