# Generated by Django 5.1.1 on 2026-04-09 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0085_conversionrateitems_conversionrateversions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversionrateitems",
            name="conversion_rate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="die.conversionrate",
            ),
        ),
        migrations.AlterField(
            model_name="conversionrateversions",
            name="conversion_rate_items",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="die.conversionrateitems",
            ),
        ),
    ]
