# Generated by Django 5.1.1 on 2026-04-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0086_alter_conversionrateitems_conversion_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversionrateversions",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
