# Generated by Django 5.1.1 on 2026-04-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0087_conversionrateversions_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversionrateversions",
            name="new_conversion",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="conversionrateversions",
            name="old_conversion",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
