# Generated by Django 5.1.1 on 2026-04-23 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0088_conversionrateversions_new_conversion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DieInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_drawing_number",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("revision", models.CharField(blank=True, max_length=250, null=True)),
                ("revision_date", models.DateField(blank=True, null=True)),
                ("container_size", models.IntegerField(blank=True, null=True)),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="information",
                        to="die.die",
                    ),
                ),
            ],
            options={
                "db_table": "die_information",
            },
        ),
    ]
