# Generated by Django 5.1.1 on 2026-04-23 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0090_alter_die_created_by_alter_die_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="die",
            name="container_size",
        ),
        migrations.RemoveField(
            model_name="die",
            name="reference_drawing_number",
        ),
        migrations.RemoveField(
            model_name="die",
            name="revision",
        ),
        migrations.RemoveField(
            model_name="die",
            name="revision_date",
        ),
    ]
