# Generated by Django 5.1.1 on 2026-04-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0092_alter_sectionballondimensions_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dieinformation",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
