# Generated by Django 5.1.1 on 2026-04-23 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0093_dieinformation_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="die",
            name="area",
        ),
        migrations.RemoveField(
            model_name="die",
            name="ccd_mm",
        ),
        migrations.RemoveField(
            model_name="die",
            name="perimeter_outer",
        ),
    ]
