# Generated by Django 5.1.1 on 2026-04-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0094_remove_die_area_remove_die_ccd_mm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="die",
            name="area",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="die",
            name="ccd_mm",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="die",
            name="perimeter_outer",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
