# Generated by Django 5.1.1 on 2026-04-23 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0095_die_area_die_ccd_mm_die_perimeter_outer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dieinformation",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extrusion_die_info",
                to="die.die",
            ),
        ),
    ]
