# Generated by Django 5.1.1 on 2026-04-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0096_alter_dieinformation_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="die",
            name="back_end_process_loss_mm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="die",
            name="front_end_process_loss_mm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="die",
            name="stretching_head_loss_mm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="die",
            name="stretching_tail_loss_mm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="die",
            name="total_process_loss_kg",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="die",
            name="total_process_loss_meter",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="die",
            name="total_process_loss_mm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="die",
            name="wt_kg_p_mt",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
