# Generated by Django 5.1.1 on 2026-04-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0097_alter_die_back_end_process_loss_mm_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="die",
            name="extrusion_ratio",
        ),
    ]
