# Generated by Django 5.1.1 on 2026-04-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0098_remove_die_extrusion_ratio"),
    ]

    operations = [
        migrations.AddField(
            model_name="die",
            name="extrusion_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
