# Generated by Django 5.1.1 on 2026-04-24 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0099_die_extrusion_ratio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="die",
            name="extrusion_ratio",
        ),
    ]
