# Generated by Django 5.1.1 on 2026-04-27 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0100_remove_die_extrusion_ratio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dietool",
            name="correction_history",
        ),
        migrations.RemoveField(
            model_name="dietool",
            name="first_trial_date",
        ),
        migrations.RemoveField(
            model_name="dietool",
            name="last_polishing_date",
        ),
        migrations.RemoveField(
            model_name="dietool",
            name="nitriding_date",
        ),
        migrations.RemoveField(
            model_name="dietool",
            name="regrinds",
        ),
        migrations.RemoveField(
            model_name="dietool",
            name="trial_result",
        ),
    ]
