# Generated by Django 5.1.1 on 2026-04-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0101_remove_dietool_correction_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietool",
            name="extrusion_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
