# Generated by Django 5.1.1 on 2026-05-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0102_dietool_extrusion_ratio"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dieinformation",
            old_name="description",
            new_name="revision_description",
        ),
    ]
