# Generated by Django 5.1.1 on 2026-05-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0103_rename_description_dieinformation_revision_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dietool",
            old_name="developer",
            new_name="customer",
        ),
        migrations.AddField(
            model_name="dietool",
            name="broken_part",
            field=models.CharField(
                blank=True,
                choices=[
                    ("die_plate", "Die Plate"),
                    ("mandrill", "Mandrill"),
                    ("backer", "Backer"),
                    ("bolster", "Bolster"),
                    ("full_set", "Full Set"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dietool",
            name="damage_severity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("minor", "Minor"),
                    ("major", "Major"),
                    ("critical", "Critical"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dietool",
            name="die_broken_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dietool",
            name="material_grade",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
