# Generated by Django 5.1.1 on 2026-05-08 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0104_rename_developer_dietool_customer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DieToolBrokenImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "die_tool",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="die_broken_images",
                        to="die.dietool",
                    ),
                ),
            ],
            options={
                "db_table": "die_tool_broken_image",
            },
        ),
    ]
