# Generated by Django 5.1.1 on 2026-05-08 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0025_remove_customer_customer_cu_custome_d3a0b9_idx_and_more"),
        ("die", "0105_dietoolbrokenimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietool",
            name="vendor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dietool_vendor",
                to="customer.customer",
            ),
        ),
    ]
