# Generated by Django 5.1.1 on 2026-05-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0106_dietool_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dietool",
            name="broken_part",
            field=models.CharField(
                blank=True,
                choices=[
                    ("die_plate", "Die Plate"),
                    ("mandrel", "Mandrel"),
                    ("backer", "Backer"),
                    ("bolster", "Bolster"),
                    ("feeder", "Feeder"),
                    ("die_ring", "Die Ring"),
                    ("pocket", "Pocket"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
