# Generated by Django 5.1.1 on 2026-05-08 09:30

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0107_alter_dietool_broken_part"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dietool",
            name="broken_part",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("die_plate", "Die Plate"),
                    ("mandrel", "Mandrel"),
                    ("backer", "Backer"),
                    ("bolster", "Bolster"),
                    ("feeder", "Feeder"),
                    ("die_ring", "Die Ring"),
                    ("pocket", "Pocket"),
                ],
                max_length=55,
                null=True,
            ),
        ),
    ]
