# Generated by Django 5.1.1 on 2026-05-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0108_alter_dietool_broken_part"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietool",
            name="scrap_weight",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
