# Generated by Django 5.1.1 on 2026-05-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0110_alter_diecategory_name_alter_diegroup_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diecategory",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="diegroup",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="diesubcategory",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
