# Generated by Django 5.1.1 on 2026-05-14 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0111_alter_diecategory_name_alter_diegroup_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dietool",
            unique_together=set(),
        ),
    ]
