# Generated by Django 5.1.1 on 2026-06-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0112_alter_dietool_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diesize",
            old_name="die_height",
            new_name="diameter",
        ),
        migrations.RenameField(
            model_name="diesize",
            old_name="die_width",
            new_name="thickness",
        ),
    ]
