# Generated by Django 5.1.1 on 2026-06-15 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0113_rename_die_height_diesize_diameter_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectionballondimensions",
            name="nominal_value",
        ),
    ]
