# Generated by Django 5.1.1 on 2026-06-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0114_remove_sectionballondimensions_nominal_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionballondimensions",
            name="nominal_value",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
