# Generated by Django 5.1.1 on 2026-07-28 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0115_sectionballondimensions_nominal_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dietool",
            name="eligible_bloster",
        ),
    ]
