# Generated by Django 5.1.1 on 2026-07-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloster", "0012_blostermaster_diameter_mm_blostermaster_thickness_mm"),
        ("die", "0116_remove_dietool_eligible_bloster"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietool",
            name="first_bloster",
            field=models.ManyToManyField(
                blank=True,
                related_name="dietool_bloster_first",
                to="bloster.blostermaster",
            ),
        ),
        migrations.AddField(
            model_name="dietool",
            name="second_bloster",
            field=models.ManyToManyField(
                blank=True,
                related_name="dietool_bloster_second",
                to="bloster.blostermaster",
            ),
        ),
        migrations.AddField(
            model_name="dietool",
            name="third_bloster",
            field=models.ManyToManyField(
                blank=True,
                related_name="dietool_bloster_third",
                to="bloster.blostermaster",
            ),
        ),
    ]
