# Generated by Django 5.1.1 on 2026-07-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0117_dietool_first_bloster_dietool_second_bloster_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dietool",
            old_name="weight_diff",
            new_name="weight_diff_percent",
        ),
        migrations.AddField(
            model_name="dietool",
            name="weight_diff_kg",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
