# Generated by Django 5.1.1 on 2026-07-28 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0118_rename_weight_diff_dietool_weight_diff_percent_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dietool",
            old_name="weight_diff_percent",
            new_name="weight_diff_per",
        ),
    ]
