# Generated by Django 5.1.1 on 2026-07-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0119_rename_weight_diff_percent_dietool_weight_diff_per"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietool",
            name="feeder_number",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
