# Generated by Django 5.1.1 on 2026-07-30 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0120_dietool_feeder_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dietool",
            old_name="total_running_mt",
            new_name="total_running_kg",
        ),
    ]
