# Generated by Django 5.1.1 on 2026-07-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0121_rename_total_running_mt_dietool_total_running_kg"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietool",
            name="location",
            field=models.CharField(
                choices=[
                    ("Die_Tool_Room", "Die_Tool_Room"),
                    ("Press", "Press"),
                    ("Maintenance", "Maintenance"),
                    ("QC_Inspection", "QC_Inspection"),
                    ("Vendor", "Vendor"),
                    ("Scrap", "Scrap"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
