# Generated by Django 5.1.1 on 2026-07-31 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die", "0122_dietool_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietool",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Reserved", "Reserved"),
                    ("In_Production", "In_Production"),
                    ("Under_Maintenance", "Under_Maintenance"),
                    ("Under_Correction", "Under_Correction"),
                    ("Under_Inspection", "Under_Inspection"),
                    ("Scrapped", "Scrapped"),
                ],
                default="Available",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dietool",
            name="location",
            field=models.CharField(
                choices=[
                    ("Die_Tool_Room", "Die_Tool_Room"),
                    ("Press", "Press"),
                    ("Maintenance", "Maintenance"),
                    ("QC_Inspection", "QC_Inspection"),
                    ("Vendor", "Vendor"),
                    ("Scrap", "Scrap"),
                ],
                default="Die_Tool_Room",
                max_length=50,
            ),
        ),
    ]
