# Generated by Django 5.1.1 on 2025-12-03 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("die", "0006_diepress_billet_diameter_max_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DieRequisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_no", models.CharField(blank=True, max_length=100, null=True)),
                ("quantity", models.IntegerField(blank=True, null=True)),
                ("no_of_die_requirements", models.IntegerField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="die_requisition_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="die_requisition_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="die_requisition_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "die_profile",
                    models.ManyToManyField(
                        blank=True, related_name="die_requisition", to="die.die"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="die_requisition_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    (
                        "download_die_requisition_pdf_copy",
                        "Can download die requisition PDF",
                    ),
                    (
                        "download_die_requisition_excel_copy",
                        "Can download die requisition Excel",
                    ),
                ],
            },
        ),
    ]
