# Generated by Django 5.1.1 on 2026-01-29 11:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0021_alter_bankingdetails_updated_at_and_more"),
        ("die", "0049_alter_diecategory_created_by_and_more"),
        ("die_requisition", "0001_initial"),
        ("planning", "0010_alter_planning_pcsperblt"),
        ("workorder", "0013_alter_workorder_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dierequisition",
            options={
                "permissions": [
                    (
                        "can_download_die_requisition_pdf",
                        "Can Download Die Requisition PDF",
                    ),
                    (
                        "can_download_die_requisition_excel",
                        "Can Download Die Requisition Excel",
                    ),
                ]
            },
        ),
        migrations.RemoveField(
            model_name="dierequisition",
            name="assigned_by",
        ),
        migrations.RemoveField(
            model_name="dierequisition",
            name="die_profile",
        ),
        migrations.RemoveField(
            model_name="dierequisition",
            name="no_of_die_requirements",
        ),
        migrations.RemoveField(
            model_name="dierequisition",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="dierequisition",
            name="section_no",
        ),
        migrations.AddField(
            model_name="dierequisition",
            name="customer",
            field=models.ForeignKey(
                default=14,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="die_requisition_customer",
                to="customer.customer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dierequisition",
            name="planning",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="die_requisitions_planning",
                to="planning.planning",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dierequisition",
            name="priority",
            field=models.CharField(
                choices=[("Normal", "Normal"), ("Urgent", "Urgent")],
                default="Normal",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="dierequisition",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dierequisition",
            name="required_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dierequisition",
            name="requisition_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="dierequisition",
            name="requisition_no",
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dierequisition",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Requested", "Requested"),
                    ("Issued", "Issued"),
                    ("Rejected", "Rejected"),
                    ("Closed", "Closed"),
                ],
                default="Draft",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="dierequisition",
            name="workorder_no",
            field=models.ForeignKey(
                default=43,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="die_requisitions_workorder",
                to="workorder.workorder",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dierequisition",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dierequisition",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dierequisition",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dierequisition",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="DieRequisitionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("die_number", models.CharField(blank=True, max_length=30, null=True)),
                ("cavity", models.PositiveIntegerField(default=1)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Store", "Store"),
                            ("Press", "Press"),
                            ("Toolroom", "Toolroom"),
                        ],
                        default="Store",
                        max_length=10,
                    ),
                ),
                ("life_balance", models.IntegerField(blank=True, null=True)),
                (
                    "expected_output_kg",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Approved", "Approved")],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "die",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="die_requisition_dietool",
                        to="die.dietool",
                    ),
                ),
                (
                    "press",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="die_requisition_press",
                        to="die.diepress",
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="die_requisition",
                        to="die_requisition.dierequisition",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
