# Generated by Django 5.1.1 on 2026-01-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die_requisition", "0002_alter_dierequisition_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dierequisition",
            name="status",
            field=models.CharField(
                choices=[
                    ("Requested", "Requested"),
                    ("Issued", "Issued"),
                    ("Rejected", "Rejected"),
                    ("Closed", "Closed"),
                ],
                default="Requested",
                max_length=15,
            ),
        ),
    ]
