# Generated by Django 5.1.1 on 2026-02-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die_requisition", "0003_alter_dierequisition_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dierequisitiondetail",
            old_name="die",
            new_name="die_tool",
        ),
        migrations.RenameField(
            model_name="dierequisitiondetail",
            old_name="die_number",
            new_name="profile_number",
        ),
    ]
