# Generated by Django 5.1.1 on 2026-02-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die_requisition", "0004_rename_die_dierequisitiondetail_die_tool_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dierequisitiondetail",
            name="actual_qty_produced",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="dierequisitiondetail",
            name="billets_used",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dierequisitiondetail",
            name="die_condition_after",
            field=models.CharField(
                choices=[("Ok", "Ok"), ("Repair", "Repair")],
                default="Ok",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="dierequisitiondetail",
            name="die_return_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dierequisitiondetail",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
