# Generated by Django 5.1.1 on 2026-02-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die_requisition", "0005_dierequisitiondetail_actual_qty_produced_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dierequisitiondetail",
            name="reject_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
