# Generated by Django 5.1.1 on 2026-02-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("die_requisition", "0006_dierequisitiondetail_reject_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dierequisitiondetail",
            name="reject_reason",
        ),
        migrations.AddField(
            model_name="dierequisition",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
