# Generated by Django 5.1.1 on 2026-02-03 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die_requisition", "0007_remove_dierequisitiondetail_reject_reason_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dierequisition",
            name="planning",
        ),
    ]
