# Generated by Django 5.1.1 on 2026-02-13 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("die_requisition", "0008_remove_dierequisition_planning"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dierequisition",
            options={
                "permissions": [
                    (
                        "can_download_die_requisition_pdf",
                        "Can Download Die Requisition PDF",
                    ),
                    (
                        "can_download_die_requisition_excel",
                        "Can Download Die Requisition Excel",
                    ),
                    ("can_issue_die_tool", "Can Issue Die Tool"),
                ]
            },
        ),
    ]
