# Generated by Django 5.1.1 on 2025-11-06 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_weight_entry", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="firstweightentry",
            name="purchaser",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"groups__name": "Purchaser", "is_active": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchaser_weight_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="firstweightentry",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"groups__name": "seller", "is_active": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seller_weight_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
