# Generated by Django 5.1.1 on 2025-11-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_weight_entry", "0002_alter_firstweightentry_purchaser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="firstweightentry",
            name="cash_party_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="firstweightentry",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=50, null=True
            ),
        ),
    ]
