# Generated by Django 5.1.1 on 2025-11-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_weight_entry", "0003_firstweightentry_cash_party_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firstweightentry",
            name="weight_for",
            field=models.CharField(
                choices=[
                    ("gross weight", "Gross weight"),
                    ("tare weight", "Tare weight"),
                ],
                default="gross weight",
                max_length=50,
            ),
        ),
    ]
