# Generated by Django 5.2.5 on 2025-12-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_weight_entry", "0004_alter_firstweightentry_weight_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="firstweightentry",
            name="capture_photo",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
