# Generated by Django 5.1.1 on 2026-03-13 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_weight_entry", "0007_alter_firstweightentry_seller"),
        ("transporter", "0011_alter_transporter_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firstweightentry",
            name="party_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transporter.transporter",
            ),
        ),
    ]
