# Generated by Django 5.1.1 on 2026-03-16 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("first_weight_entry", "0008_alter_firstweightentry_party_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="firstweightentry",
            options={
                "permissions": [
                    (
                        "download_first_weight_entry_excel_copy",
                        "Can download first weight entry Excel",
                    ),
                    (
                        "download_first_weight_entry_pdf_copy",
                        "Can download first weight entry PDF",
                    ),
                ]
            },
        ),
    ]
