# Generated by Django 5.1.1 on 2026-03-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_weight_entry", "0009_alter_firstweightentry_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firstweightentry",
            name="date_time_second",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
