# Generated by Django 5.1.1 on 2026-03-23 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_weight_entry", "0010_alter_firstweightentry_date_time_second"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="firstweightentry",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seller_weight_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
