# Generated by Django 5.1.1 on 2026-03-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_weight_entry", "0011_alter_firstweightentry_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firstweightentry",
            name="date_time_first",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
