# Generated by Django 5.1.1 on 2026-03-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_weight_entry", "0012_alter_firstweightentry_date_time_first"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firstweightentry",
            name="serial_no",
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
