# Generated by Django 5.1.1 on 2026-03-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_weight_entry", "0013_alter_firstweightentry_serial_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firstweightentry",
            name="serial_no",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
