# Generated by Django 5.1.1 on 2026-03-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_weight_entry", "0014_alter_firstweightentry_serial_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="firstweightentry",
            name="is_second_entry_done",
            field=models.BooleanField(default=False),
        ),
    ]
