# Generated by Django 5.1.1 on 2026-03-25 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("first_weight_entry", "0015_firstweightentry_is_second_entry_done"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firstweightentry",
            name="weight",
        ),
    ]
