# Generated by Django 5.1.1 on 2026-03-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_weight_entry", "0017_alter_firstweightentry_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="firstweightentry",
            name="capture_photo_2",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
